steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/ban-on-fire/strudelboogie:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/ban-on-fire/strudelboogie:latest'
images:
  - 'gcr.io/ban-on-fire/strudelboogie:latest'
