steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - '${{ secrets.STRUDEL_BOOGIE }}:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${{ secrets.STRUDEL_BOOGIE }}:latest'
images:
  - '${{ secrets.STRUDEL_BOOGIE }}:latest'
