package onepiece

// promoTypeLabels are the words a promo type reads as, for the datastores
// that publish it as the slug it is. A slug has no spaces left to put back,
// and title-casing one cannot invent them - nor the capitals in "LA Dodgers
// Promo" or "PSA Magazine", nor the dots in "Gol.D.Roger".
//
// The spellings are the catalog's own: each is the span of a product name's
// words whose slug is the tag. Four have no such span, because the builder
// folded them - the year sits inside "LA Dodgers 2026 Promo", the volume
// inside "Tin Pack Set Vol. 1 Gol.D.Roger", and "SP" is the abbreviation
// punk-records files as the rarity "Special".
var promoTypeLabels = map[string]string{
	"1stplace":                     "1st Place",
	"2ndplace":                     "2nd Place",
	"3brotherspack":                "3 Brothers Pack",
	"3d":                           "3D",
	"3dtext":                       "3D Text",
	"3on3cup":                      "3-on-3 Cup",
	"3rdplace":                     "3rd Place",
	"alphapreerrata":               "Alpha Pre-Errata",
	"alternateart":                 "Alternate Art",
	"animeexpo":                    "Anime Expo",
	"anniversary":                  "Anniversary",
	"anniversarydoncardpack":       "Anniversary DON!! Card Pack",
	"anniversaryleadercard":        "Anniversary Leader Card",
	"anniversaryset":               "Anniversary Set",
	"anniversarystamped":           "Anniversary Stamped",
	"anniversarystampedpromo":      "Anniversary Stamped Promo",
	"anniversarytournament":        "Anniversary Tournament",
	"anniversarytreasure":          "Anniversary Treasure",
	"bandaicardgamesfest":          "BANDAI CARD GAMES Fest",
	"bandaicardgamesfestworldtour": "BANDAI CARD GAMES Fest World Tour",
	"beginnersdeckparty":           "Beginners Deck Party",
	"betapreerrata":                "Beta Pre-Errata",
	"binderset":                    "Binder Set",
	"blackandgold":                 "Black and Gold",
	"blackwhite":                   "Black & White",
	"boxtopper":                    "Box Topper",
	"bronze":                       "Bronze",
	"bvbxonepiececampaign":         "BVB x One Piece Campaign",
	"campaignpack":                 "Campaign Pack",
	"celebrationpack":              "Celebration Pack",
	"certificateofourcrew":         "Certificate of our crew",
	"championcardset":              "Champion Card Set",
	"championship":                 "Championship",
	"collegebasketballus":          "College Basketball US",
	"collegebasketballusvoyage":    "College Basketball US Voyage",
	"color":                        "Color",
	"conventionpromo":              "Convention Promo",
	"cs":                           "Championship Series",
	"dashpack":                     "Dash Pack",
	"deckbattle":                   "Deck Battle",
	"demodeck":                     "Demo Deck",
	"devilfruitscollection":        "Devil Fruits Collection",
	"dodgersxonepiece":             "Dodgers x ONE PIECE",
	"doublepackset":                "Double Pack Set",
	"eventpack":                    "Event Pack",
	"extragrandbattle":             "Extra Grand Battle",
	"extragrandbattleforstores":    "Extra Grand Battle for Stores",
	"finalist":                     "Finalist",
	"finalistcardset":              "Finalist Card Set",
	"fullart":                      "Full Art",
	"gencon":                       "Gen Con",
	"giftcollection":               "Gift Collection",
	"gold":                         "Gold",
	"goldstampedsignature":         "Gold-Stamped Signature",
	"heroinesbattle":               "Heroines Battle",
	"heroinesbattlepack":           "Heroines Battle Pack",
	"heroinesbattlewinner":         "Heroines Battle Winner",
	"ichibankujiexclusive":         "Ichiban Kuji Exclusive",
	"illustrationbox":              "Illustration Box",
	"illustrationboxex":            "Illustration Box EX",
	"jollyrogerfoil":               "Jolly Roger Foil",
	"judge":                        "Judge",
	"judgepack":                    "Judge Pack",
	"judgepromo":                   "Judge Promo",
	"jumbo":                        "Jumbo",
	"ladodgerspromo":               "LA Dodgers Promo",
	"leaderpack":                   "Leader Pack",
	"learntogetherdeckset":         "Learn Together Deck Set",
	"liveaction":                   "Live Action",
	"manga":                        "Manga",
	"newyearevent":                 "New Year Event",
	"odastampedsignature":          "Oda Stamped Signature",
	"officialplaymat":              "Official Playmat",
	"officialplaymatbandai":        "Official Playmat Bandai",
	"officialplaymatlimited":       "Official Playmat Limited",
	"offlineregional":              "Offline Regional",
	"onepiececardgame":             "One Piece Card Game",
	"onepiecedaydallas":            "One Piece Day Dallas",
	"onepiecefilmred":              "One Piece Film Red",
	"onlineregional":               "Online Regional",
	"onlineregionalchampion":       "Online Regional Champion",
	"onlineregionalfinalist":       "Online Regional Finalist",
	"oversized":                    "Oversized",
	"pandamanart":                  "Pandaman Art",
	"parallel":                     "Parallel",
	"participant":                  "Participant",
	"participationpack":            "Participation Pack",
	"piratefoil":                   "Pirate Foil",
	"piratesleaguefinals":          "Pirates League Finals",
	"piratesleaguestore":           "Pirates League Store",
	"piratesleaguestorequalifier":  "Pirates League Store Qualifier",
	"piratesparty":                 "Pirates Party",
	"preerrata":                    "Pre-Errata",
	"premiumcardcollection":        "Premium Card Collection",
	"prerelease":                   "Pre-Release",
	"prereleasetournament":         "Pre-Release Tournament",
	"promotionpack":                "Promotion Pack",
	"psamagazine":                  "PSA Magazine",
	"redbulldon":                   "Red Bull Don!!",
	"redbulldoubledon":             "Red Bull Double Don!!",
	"redsuperalternateart":         "Red Super Alternate Art",
	"regionalparticipation":        "Regional Participation",
	"regionals":                    "Regionals",
	"regionalschampioncard":        "Regionals Champion Card",
	"regionalsfinalistcard":        "Regionals Finalist Card",
	"regionalstexturedchase":       "Regionals Textured Chase",
	"releaseevent":                 "Release Event",
	"releaseeventpack":             "Release Event Pack",
	"releaseeventwinnerpack":       "Release Event Winner Pack",
	"reprint":                      "Reprint",
	"retailpromo":                  "Retail Promo",
	"round1promo":                  "Round 1 Promo",
	"sealedbattle":                 "Sealed Battle",
	"sealedbattlekit":              "Sealed Battle Kit",
	"serialnumbered":               "Serial Numbered",
	"setsailevent":                 "Set Sail Event",
	"sevenwarlordsofthesea":        "Seven Warlords of the Sea",
	"shattered":                    "Shattered",
	"silhouette":                   "Silhouette",
	"silver":                       "Silver",
	"soundloader":                  "Sound Loader",
	"soundloaderaceandsabo":        "Sound Loader Ace and Sabo",
	"soundloaderluffy":             "Sound Loader Luffy",
	"sp":                           "Special",
	"specialdoncardpack":           "Special DON!! Card Pack",
	"specialdonset":                "Special DON!! Set",
	"specialfoil":                  "Special Foil",
	"specialgoodsset":              "Special Goods Set",
	"specialgoodssetformer":        "Special Goods Set Former",
	"starterdeck11utadeck":         "Starter Deck 11: Uta Deck",
	"store":                        "Store",
	"store2on2battle":              "Store 2-on-2 Battle",
	"storechampionship":            "Store Championship",
	"storeregionals":               "Store Regionals",
	"storetournament":              "Store Tournament",
	"storetreasurecup":             "Store Treasure Cup",
	"superalternateart":            "Super Alternate Art",
	"superleaderalternate":         "Super Leader Alternate",
	"superleaderalternateart":      "Super Leader Alternate Art",
	"superprerelease":              "Super Pre-Release",
	"texturedchasepromo":           "Textured Chase Promo",
	"texturedfoil":                 "Textured Foil",
	"tinpackset":                   "Tin Pack Set",
	"tinpacksetgoldroger":          "Tin Pack Set Gol.D.Roger",
	"tinpacksetmonkeydluffy":       "Tin Pack Set Monkey.D.Luffy",
	"top16":                        "Top 16",
	"top64":                        "Top 64",
	"topplayerpack":                "Top Player Pack",
	"tournamentpack":               "Tournament Pack",
	"treasureboosterset":           "Treasure Booster Set",
	"treasurecup":                  "Treasure Cup",
	"trophycard":                   "Trophy Card",
	"twolegendsprerelease":         "Two Legends Pre-Release",
	"ultradeckthethree":            "Ultra Deck: The Three",
	"wantedposter":                 "Wanted Poster",
	"welcomepack":                  "Welcome Pack",
	"wholecakeislandarc":           "Whole Cake Island Arc",
	"winner":                       "Winner",
	"winnercardset":                "Winner Card Set",
	"winnerpack":                   "Winner Pack",
	"worldchampionship":            "World Championship",
	"worldchampionshipfinals":      "World Championship Finals",
	"worldfinal":                   "World Final",
}
