package mtgban

var EditionTable = map[string]string{
	/* Main expansions */
	"10th Edition":              "Tenth Edition",
	"3rd Edition/Revised":       "Revised Edition",
	"4th Edition":               "Fourth Edition",
	"5th Edition":               "Fifth Edition",
	"6th Edition":               "Classic Sixth Edition",
	"7th Edition":               "Seventh Edition",
	"8th Edition":               "Eighth Edition",
	"9th Edition":               "Ninth Edition",
	"Alpha":                     "Limited Edition Alpha",
	"Beta":                      "Limited Edition Beta",
	"Betrayers":                 "Betrayers of Kamigawa",
	"Champions":                 "Champions of Kamigawa",
	"Classic 6th Edition":       "Classic Sixth Edition",
	"ColdSnap":                  "Coldsnap",
	"Futuresight":               "Future Sight",
	"Hours of Devestation":      "Hour of Devastation",
	"Introductory 4th Edition":  "Introductory Two-Player Set",
	"Journey Into Nyx":          "Journey into Nyx",
	"Ravnica":                   "Ravnica: City of Guilds",
	"Revised":                   "Revised Edition",
	"Saviors":                   "Saviors of Kamigawa",
	"Shadows Over Innistrad":    "Shadows over Innistrad",
	"Time Spiral (Timeshifted)": "Time Spiral Timeshifted",
	"Time Spiral - Timeshifted": "Time Spiral Timeshifted",
	"Time Spiral Time Shifted":  "Time Spiral Timeshifted",
	"TimeShifted":               "Time Spiral Timeshifted",
	"Unlimited":                 "Unlimited Edition",

	/* Alternate versions */
	"Theros Beyond Death (Collector Edition)":   "Theros Beyond Death",
	"Theros Beyond Death: Extras":               "Theros Beyond Death",
	"Theros Beyond Death: Variants":             "Theros Beyond Death",
	"Throne of Eldraine (Collector Edition)":    "Throne of Eldraine",
	"Throne of Eldraine: Variants":              "Throne of Eldraine",
	"War of the Spark (Japanese Alternate Art)": "War of the Spark",

	/* Various promos and boxsets */
	"Battle Royale":                "Battle Royale Box Set",
	"Beatdown":                     "Beatdown Box Set",
	"Coldsnap Theme Deck Reprints": "Coldsnap Theme Decks",
	"Coldsnap Theme Deck":          "Coldsnap Theme Decks",
	"Conspiracy Take the Crown":    "Conspiracy: Take the Crown",
	"Game Night 2018":              "Game Night",
	"Gift Boxes: Anthologies":      "Anthologies",
	"Gift Boxes: Battle Royale":    "Battle Royale Box Set",
	"Gift Boxes: Beatdown":         "Beatdown Box Set",
	"Gift Boxes: Deckmaster":       "Deckmasters",
	"Mystery Booster Test Print":   "Mystery Booster Playtest Cards",
	"Mystery Booster Test Prints":  "Mystery Booster Playtest Cards",
	"Planechase (2009 Edition)":    "Planechase",
	"Planechase (2012 Edition)":    "Planechase 2012",
	"Planechase 2009":              "Planechase",
	"Portal 1":                     "Portal",
	"Portal 3 Kingdoms":            "Portal Three Kingdoms",
	"Promos: Apac Lands":           "Asia Pacific Land Program",
	"Promos: Euro Lands":           "European Land Program",
	"Promos: Grand Prix":           "Grand Prix Promos",
	"Promos: Guru Lands":           "Guru",
	"Promos: Ugin's Fate":          "Ugin's Fate",
	"Vanguard":                     "Vanguard Series",

	/* Guild kits */
	"Guild Kits: Guilds of Ravnica":  "GRN Guild Kit",
	"Guild Kits: Ravnica Allegiance": "RNA Guild Kit",
	"Guilds of Ravnica: Guild Kits":  "GRN Guild Kit",
	"Ravnica Allegiance: Guild Kits": "RNA Guild Kit",

	/* Commander */
	"Commander":                    "Commander 2011",
	"Commander 2017 Edition":       "Commander 2017",
	"Commander Anthology Volume 2": "Commander Anthology Volume II",
	"Commander Singles":            "Commander 2011",
	"Commander 2013 Edition":       "Commander 2013",
	"Commander 2014 Edition":       "Commander 2014",
	"Commander 2016 Edition":       "Commander 2016",

	/* Modern Masters */
	"Modern Event Deck":             "Modern Event Deck 2014",
	"Modern Masters 2013":           "Modern Masters",
	"Ultimate Box Toppers":          "Ultimate Box Topper",
	"Ultimate Masters: Box Toppers": "Ultimate Box Topper",

	/* Core sets */
	"M10 Core Set": "Magic 2010",
	"M11 Core Set": "Magic 2011",
	"M12 Core Set": "Magic 2012",
	"M13 Core Set": "Magic 2013",
	"M14 Core Set": "Magic 2014",
	"M15 Core Set": "Magic 2015",

	/* CE and IE editions */
	"Gift Boxes: International Edition":          "Intl. Collectors’ Edition",
	"Collectors' Edition - International":        "Intl. Collectors’ Edition",
	"International Collector's Edition":          "Intl. Collectors’ Edition",
	"Gift Boxes: Collector's Edition (Domestic)": "Collectors’ Edition",
	"Collector's Edition":                        "Collectors’ Edition",
	"Collectors' Edition":                        "Collectors’ Edition",

	/* Duel Decks */
	"Duel Deck Heros VS Monsters":            "Duel Decks: Heroes vs. Monsters",
	"Duel Decks: Kiora vs Elspeth":           "Duel Decks: Elspeth vs. Kiora",
	"Duel Decks: Phyrexia vs The Coalition":  "Duel Decks: Phyrexia vs. the Coalition",
	"Duel Decks: Phyrexia vs. The Coalition": "Duel Decks: Phyrexia vs. the Coalition",
	"Ajani vs. Nicol Bolas":                  "Duel Decks: Ajani vs. Nicol Bolas",
	"Blessed vs. Cursed":                     "Duel Decks: Blessed vs. Cursed",
	"Divine vs. Demonic":                     "Duel Decks: Divine vs. Demonic",
	"Elspeth vs. Kiora":                      "Duel Decks: Elspeth vs. Kiora",
	"Elspeth vs. Tezzeret":                   "Duel Decks: Elspeth vs. Tezzeret",
	"Elves vs. Goblins":                      "Duel Decks: Elves vs. Goblins",
	"Elves vs. Inventors":                    "Duel Decks: Elves vs. Inventors",
	"Garruk vs. Liliana":                     "Duel Decks: Garruk vs. Liliana",
	"Heroes vs. Monsters":                    "Duel Decks: Heroes vs. Monsters",
	"Izzet vs. Golgari":                      "Duel Decks: Izzet vs. Golgari",
	"Jace vs. Chandra":                       "Duel Decks: Jace vs. Chandra",
	"Jace vs. Vraska":                        "Duel Decks: Jace vs. Vraska",
	"Knights vs. Dragons":                    "Duel Decks: Knights vs. Dragons",
	"Merfolk vs. Goblins":                    "Duel Decks: Merfolk vs. Goblins",
	"Mind vs. Might":                         "Duel Decks: Mind vs. Might",
	"Nissa vs. Ob Nixilis":                   "Duel Decks: Nissa vs. Ob Nixilis",
	"Phyrexia vs. The Coalition":             "Duel Decks: Phyrexia vs. the Coalition",
	"Sorin vs. Tibalt":                       "Duel Decks: Sorin vs. Tibalt",
	"Speed vs. Cunning":                      "Duel Decks: Speed vs. Cunning",
	"Venser vs. Koth":                        "Duel Decks: Venser vs. Koth",
	"Zendikar vs. Eldrazi":                   "Duel Decks: Zendikar vs. Eldrazi",

	/* Various series */
	"Global Series: Jiang Yanggu & Mu Yanling":   "Global Series Jiang Yanggu & Mu Yanling",
	"Global Series: Jiang Yanggu and Mu Yanling": "Global Series Jiang Yanggu & Mu Yanling",
	"PDS: Fire & Lightning":                      "Premium Deck Series: Fire and Lightning",
	"PDS: Graveborn":                             "Premium Deck Series: Graveborn",
	"PDS: Slivers":                               "Premium Deck Series: Slivers",
	"Premium Deck Fire and Lightning":            "Premium Deck Series: Fire and Lightning",
	"Premium Deck Graveborn":                     "Premium Deck Series: Graveborn",
	"Premium Deck Series: Fire & Lightning":      "Premium Deck Series: Fire and Lightning",
	"Premium Deck Slivers":                       "Premium Deck Series: Slivers",

	/* Masterpiece and Mythic editions */
	"Masterpiece Series: Amonkhet Invocations": "Amonkhet Invocations",
	"Masterpiece Series: Kaladesh Inventions":  "Kaladesh Inventions",
	"Masterpiece Series: Zendikar Inventions":  "Zendikar Expeditions",
	"Masterpiece: Mythic Edition":              "Mythic Edition",
	"Guilds of Ravnica Mythic Edition":         "Mythic Edition",
	"Guilds of Ravnica: Mythic Edition":        "Mythic Edition",
	"Ravnica Allegiance Mythic Edition":        "Mythic Edition",
	"Ravnica Allegiance: Mythic Edition":       "Mythic Edition",
	"War of the Spark Mythic Edition":          "Mythic Edition",
	"War of the Spark: Mythic Edition":         "Mythic Edition",

	/* Foreign-only */
	"3rd Edition (Foreign Black Border)": "Foreign Black Border",

	/* Foreign translations */
	"Alleanze":                   "Alliances",
	"Apocalisse":                 "Apocalypse",
	"Ascesa Oscura":              "Dark Ascension",
	"Ascesa degli Eldrazi":       "Rise of the Eldrazi",
	"Assalto":                    "Onslaught",
	"Aurora":                     "Morningtide",
	"Campioni di Kamigawa":       "Champions of Kamigawa",
	"Caos Dimensionale":          "Planar Chaos",
	"Cavalcavento":               "Weatherlight",
	"Cicatrici di Mirrodin":      "Scars of Mirrodin",
	"Commander Arsenal":          "Commander's Arsenal",
	"Congiunzione":               "Planeshift",
	"Decima Edizione":            "Tenth Edition",
	"Destino di Urza":            "Urza's Destiny",
	"Discordia":                  "Dissension",
	"Draghi di Tarkir":           "Dragons of Tarkir",
	"Era Glaciale":               "Ice Age",
	"Eredità di Urza":            "Urza's Legacy",
	"Esodo":                      "Exodus",
	"Figli degli Dei":            "Born of the Gods",
	"Flagello":                   "Scourge",
	"Fortezza":                   "Stronghold",
	"Frammenti di Alara":         "Shards of Alara",
	"I Khan di Tarkir":           "Khans of Tarkir",
	"Il Patto delle Gilde":       "Guildpact",
	"Invasione":                  "Invasion",
	"Irruzione":                  "Gatecrash",
	"Labirinto del Drago":        "Dragon's Maze",
	"Landa Tenebrosa":            "Shadowmoor",
	"Leggende":                   "Legends",
	"Legioni":                    "Legions",
	"Liberatori di Kamigawa":     "Saviors of Kamigawa",
	"Maschere di Mercadia":       "Mercadian Masques",
	"Mirrodin Assediato":         "Mirrodin Besieged",
	"Nona Edizione":              "Ninth Edition",
	"Nuova Phyrexia":             "New Phyrexia",
	"Odissea":                    "Odyssey",
	"Ondata Glaciale":            "Coldsnap",
	"Origini":                    "Homelands",
	"Ottava Edizione":            "Eighth Edition",
	"Profezia":                   "Prophecy",
	"Quarta Edizione":            "Fourth Edition",
	"Quinta Alba":                "Fifth Dawn",
	"Quinta Edizione":            "Fifth Edition",
	"Ravnica: Città delle Gilde": "Ravnica: City of Guilds",
	"Revised EU FBB":             "Foreign Black Border",
	"Revised EU FWB":             "Foreign White Border",
	"Riforgiare il Destino":      "Fate Reforged",
	"Rinascita di Alara":         "Alara Reborn",
	"Ritorno a Ravnica":          "Return to Ravnica",
	"Ritorno di Avacyn":          "Avacyn Restored",
	"Saga di Urza":               "Urza's Saga",
	"Sentenza":                   "Judgment",
	"Sesta Edizione":             "Classic Sixth Edition",
	"Settima Edizione":           "Seventh Edition",
	"Spirale Temporale":          "Time Spiral",
	"Tempesta":                   "Tempest",
	"Timeshifted":                "Time Spiral Timeshifted",
	"Tormento":                   "Torment",
	"Traditori di Kamigawa":      "Betrayers of Kamigawa",
	"Vespro":                     "Eventide",
	"Viaggio Verso Nyx":          "Journey into Nyx",
	"Visione Futura":             "Future Sight",
	"Visioni":                    "Visions",

	"Mythic Edition Gilde di Ravnica":   "Mythic Edition",
	"Mythic Edition Fedeltà di Ravnica": "Mythic Edition",

	"Duel Deck: Elfi vs Goblin":       "Duel Decks: Elves vs. Goblins",
	"Duel Deck: Cavalieri vs Draghi":  "Duel Decks: Knights vs. Dragons",
	"Duel Deck: Ajani Vs Bolas":       "Duel Decks: Ajani vs. Nicol Bolas",
	"Duel Deck: Elspeth vs Tezzereth": "Duel Decks: Elspeth vs. Tezzeret",
}
