package pokemon

import (
	"strings"

	"github.com/mtgban/go-mtgban/mtgmatcher"
)

// promoTypeLabels are the words behind a token. The builder publishes a slug
// and nothing else, and a slug cannot give back the boundaries it dropped:
// "pokemoncenterexclusive" reads as "Pokemoncenterexclusive" to a
// title-caser and has to be written down instead.
//
// Only the tokens a title-caser gets wrong are here, which is most of them -
// a Pokemon label is several words far more often than not. A single word it
// gets right on its own ("staff", "prerelease", "holo") is not listed.
//
// The spellings are the catalog's own, down to the hyphens in "Non-Holo" and
// "e-League" and the capitals in "SNAP" and "SWSH215-218".
var promoTypeLabels = map[string]string{
	"10thanniversary":                       "10th Anniversary",
	"151metalcard":                          "151 Metal Card",
	"1stplace":                              "1st Place",
	"20042005":                              "2004-2005",
	"20062007":                              "2006-2007",
	"20072008":                              "2007-2008",
	"20082009":                              "2008-2009",
	"20thanniversary":                       "20th Anniversary",
	"25thanniversary":                       "25th Anniversary",
	"2ndplace":                              "2nd Place",
	"30thcelebration":                       "30th Celebration",
	"3rdplace":                              "3rd Place",
	"4thplace":                              "4th Place",
	"7elevenpromo":                          "7-Eleven Promo",
	"acetrainer":                            "Ace Trainer",
	"alolanninetaleshalfdeck":               "Alolan Ninetales Half-Deck",
	"alolanraichuhalfdeck":                  "Alolan Raichu Half-Deck",
	"alolansandslashhalfdeck":               "Alolan Sandslash Half-Deck",
	"alternateartsecret":                    "Alternate Art Secret",
	"alternatefullart":                      "Alternate Full Art",
	"alternateholo":                         "Alternate Holo",
	"ancientorigins":                        "Ancient Origins",
	"arenacupchampionships":                 "Arena Cup Championships",
	"asiachampionshipseries":                "Asia Championship Series",
	"asiapromo":                             "Asia Promo",
	"baseset":                               "Base Set",
	"battlearenadeckexclusive":              "Battle Arena Deck Exclusive",
	"battleroadautumn":                      "Battle Road Autumn",
	"battleroadspring":                      "Battle Road Spring",
	"bestbuyexclusive":                      "Best Buy Exclusive",
	"bestofgamepromo":                       "Best of Game Promo",
	"blackandwhitetourpromo":                "Black and White Tour Promo",
	"blackboltstamped":                      "Black Bolt Stamped",
	"blackdoterror":                         "Black Dot Error",
	"blackstarpromos":                       "Black Star Promos",
	"blueborder":                            "Blue Border",
	"boxtopper":                             "Box Topper",
	"brilliantstarsstamped":                 "Brilliant Stars Stamped",
	"buildabearworkshopexclusive":           "Build-A-Bear Workshop Exclusive",
	"bwblackstarpromos":                     "BW Black Star Promos",
	"celebrationsmetalcard":                 "Celebrations Metal Card",
	"championshippromo":                     "Championship Promo",
	"championshipseries":                    "Championship Series",
	"chaosrisingstamped":                    "Chaos Rising Stamped",
	"charizardstamped":                      "Charizard Stamped",
	"cinderacestamped":                      "Cinderace Stamped",
	"citychampionships":                     "City Championships",
	"collectionpromo":                       "Collection Promo",
	"collectorchest":                        "Collector Chest",
	"copyrightdate":                         "Copyright Date",
	"corocorogreystar":                      "CoroCoro Grey Star",
	"corocoropromo":                         "CoroCoro Promo",
	"cosmiceclipsestamped":                  "Cosmic Eclipse Stamped",
	"cosmosholo":                            "Cosmos Holo",
	"costcoexclusive":                       "Costco Exclusive",
	"crackedice":                            "Cracked Ice",
	"crackediceholo":                        "Cracked Ice Holo",
	"darknessablazestamped":                 "Darkness Ablaze Stamped",
	"decidueyegxchallengebox":               "Decidueye GX Challenge Box",
	"deltaspecies":                          "Delta Species",
	"deltaspeciesstamped":                   "Delta Species Stamped",
	"destinedrivalsstamp":                   "Destined Rivals Stamp",
	"detectivepikachustamped":               "Detective Pikachu Stamped",
	"diamondpearl":                          "Diamond & Pearl",
	"dpblackstarpromos":                     "DP Black Star Promos",
	"dpstylenonholo":                        "DP Style Non-Holo",
	"dreamleague":                           "Dream League",
	"duskball":                              "Dusk Ball",
	"dvdpromo":                              "DVD Promo",
	"e3stamped":                             "E3 Stamped",
	"e3stampedwithredcheeks":                "E3 Stamped with Red Cheeks",
	"ebgamesexclusive":                      "EB Games Exclusive",
	"ebgamesexclusiveapac":                  "EB Games Exclusive APAC",
	"eeveestamped":                          "Eevee Stamped",
	"eleague":                               "e-League",
	"energyholo":                            "Energy Holo",
	"energysymbolpattern":                   "Energy Symbol Pattern",
	"epiccollectionvalueboxes":              "Epic Collection Value Boxes",
	"europeanpromo":                         "European Promo",
	"europechampionships":                   "Europe Championships",
	"europeinternationalchampionship":       "Europe International Championship",
	"excollectorscarrytin":                  "EX Collector's Carry Tin",
	"excollectorstins":                      "EX Collector's Tins",
	"excollectorswindowtins":                "EX Collector's Window Tins",
	"exdecktin":                             "EX Deck Tin",
	"exrubysapphire":                        "EX Ruby & Sapphire",
	"exseriescollectorstin":                 "EX Series Collector's Tin",
	"exseriesvaluepack":                     "EX Series Value Pack",
	"forcesofnaturepromo":                   "Forces of Nature Promo",
	"fossilmuseumexclusive":                 "Fossil Museum Exclusive",
	"friendball":                            "Friend Ball",
	"fullart":                               "Full Art",
	"fullartpromo":                          "Full Art Promo",
	"fullartsecretrare":                     "Full Art Secret Rare",
	"gamesexpo":                             "Games Expo",
	"gamestopexclusive":                     "Gamestop Exclusive",
	"gencon":                                "GEN Con",
	"generalmills":                          "General Mills",
	"glossyfinish":                          "Glossy Finish",
	"goldborderedpromo":                     "Gold Bordered Promo",
	"goldenrodgamecorner":                   "Goldenrod Game Corner",
	"goldsignature":                         "Gold Signature",
	"goldstamped":                           "Gold Stamped",
	"grandprix":                             "Grand Prix",
	"greatballleague":                       "Great Ball League",
	"greentornadothemedeckexclusive":        "Green Tornado Theme Deck Exclusive",
	"gymchallenge":                          "Gym Challenge",
	"gymstampasiaexclusive":                 "Gym Stamp Asia Exclusive",
	"hgssstylenonholo":                      "HGSS Style Non-Holo",
	"highplains":                            "High Plains",
	"holidaycalendar":                       "Holiday Calendar",
	"illustrationcontest":                   "Illustration Contest",
	"inquestgamer":                          "InQuest Gamer",
	"instoreeventpromo":                     "In-Store Event Promo",
	"internationalchallenge":                "International Challenge",
	"japanese11thmoviecommemorationset":     "Japanese 11th Movie Commemoration Set",
	"japaneseexclusive":                     "Japanese Exclusive",
	"japanesemeijichocolateexclusivepromo":  "Japanese Meiji Chocolate Exclusive Promo",
	"jirachiwishmakerdvdrelease":            "Jirachi Wish Maker DVD Release",
	"journeytogetherstamped":                "Journey Together Stamped",
	"jreaststamprally":                      "Jr East Stamp Rally",
	"latinamericachampionships":             "Latin America Championships",
	"leaguechallenge":                       "League Challenge",
	"leaguecup":                             "League Cup",
	"leaguepromo":                           "League Promo",
	"leftstamp":                             "Left Stamp",
	"legendarypokemonstamped":               "Legendary Pokemon Stamped",
	"letsplayeevee":                         "Let's Play! Eevee",
	"letsplaypikachu":                       "Let's Play! Pikachu",
	"libraryexclusive":                      "Library Exclusive",
	"lineholo":                              "Line Holo",
	"lostoriginstamped":                     "Lost Origin Stamped",
	"loveball":                              "Love Ball",
	"lycanrochalfdeck":                      "Lycanroc Half-Deck",
	"masterballpattern":                     "Master Ball Pattern",
	"meddlingsparkspremiumcollection":       "Meddling Sparks Premium Collection",
	"megaevolutionstamped":                  "Mega Evolution Stamped",
	"metalcard":                             "Metal Card",
	"mewtwostamped":                         "Mewtwo Stamped",
	"mirageholo":                            "Mirage Holo",
	"mirrorreverseholo":                     "Mirror Reverse Holo",
	"moltreslegendarybattledeck":            "Moltres Legendary Battle Deck",
	"moviepromo":                            "Movie Promo",
	"nationalchampionships":                 "National Championships",
	"nintendoblackstarpromos":               "Nintendo Black Star Promos",
	"nintendopowermagazine":                 "Nintendo Power Magazine",
	"nintendoworldpromo":                    "Nintendo World Promo",
	"noereader":                             "No E-Reader",
	"nonholo":                               "Non-Holo",
	"northamericachampionships":             "North America Championships",
	"northamericainternationalchampionship": "North America International Championship",
	"obsidianflamesstamped":                 "Obsidian Flames Stamped",
	"oceaniachampionships":                  "Oceania Championships",
	"originsgamefair":                       "Origins Game Fair",
	"originsinternationalgameexpo":          "Origins International Game Expo",
	"paldeaevolvedstamp":                    "Paldea Evolved Stamp",
	"paldeanfatesstamped":                   "Paldean Fates Stamped",
	"paradoxriftstamped":                    "Paradox Rift Stamped",
	"peelableditto":                         "Peelable Ditto",
	"perfectorderstamped":                   "Perfect Order Stamped",
	"phantasmalflamesstamped":               "Phantasmal Flames Stamped",
	"pikachulibredeck":                      "Pikachu Libre Deck",
	"pikachustamped":                        "Pikachu Stamped",
	"pitchblackstamped":                     "Pitch Black Stamped",
	"pixelcosmosholo":                       "Pixel Cosmos Holo",
	"pixelholo":                             "Pixel Holo",
	"plantcloak":                            "Plant Cloak",
	"plasmafreeze":                          "Plasma Freeze",
	"playerrewards":                         "Player Rewards",
	"playpokemon":                           "Play! Pokemon",
	"pokeball":                              "Poke Ball",
	"pokeballpattern":                       "Poke Ball Pattern",
	"pokemoncenterexclusive":                "Pokemon Center Exclusive",
	"pokemoncenterny":                       "Pokemon Center NY",
	"pokemonday":                            "Pokemon Day",
	"pokemonfutsal":                         "Pokemon Futsal",
	"pokemongympromo":                       "Pokemon Gym Promo",
	"pokemonheroeslatioslatiasdvdrelease":   "Pokemon Heroes Latios & Latias DVD Release",
	"pokemonhorizonsstamped":                "Pokemon Horizons Stamped",
	"pokemonleague":                         "Pokemon League",
	"pokemonrocksamerica":                   "Pokemon Rocks America",
	"pokemontogether":                       "Pokemon Together",
	"poketour":                              "PokeTour",
	"poppromo":                              "POP Promo",
	"poptournament":                         "POP Tournament",
	"premiumcollection":                     "Premium Collection",
	"prismaticevolutionsstamped":            "Prismatic Evolutions Stamped",
	"prizepackseries":                       "Prize Pack Series",
	"professorrowan":                        "Professor Rowan",
	"quarterfinalist":                       "Quarter-Finalist",
	"quickball":                             "Quick Ball",
	"raincityshowcase":                      "Rain City Showcase",
	"rebelclash":                            "Rebel Clash",
	"redcheeks":                             "Red Cheeks",
	"regionalchampionships":                 "Regional Championships",
	"reversecosmosholo":                     "Reverse Cosmos Holo",
	"reverseholofoil":                       "Reverse Holofoil",
	"rightstamp":                            "Right Stamp",
	"rocketssecretmachine":                  "Rocket's Secret Machine",
	"scarletvioletstamp":                    "Scarlet & Violet Stamp",
	"scryemagazine":                         "Scrye Magazine",
	"sdcc":                                  "SDCC",
	"sdccstaff":                             "SDCC Staff",
	"sdccstamp":                             "SDCC Stamp",
	"semifinalist":                          "Semi-Finalist",
	"sheenholo":                             "Sheen Holo",
	"shinyfullart":                          "Shiny Full Art",
	"shroudedfablestamped":                  "Shrouded Fable Stamped",
	"silvertempeststamped":                  "Silver Tempest Stamped",
	"singleoversizedpromo":                  "Single Oversized Promo",
	"smblackstarpromos":                     "SM Black Star Promos",
	"smpjapaneseexclusive":                  "SM-P Japanese Exclusive",
	"snap":                                  "SNAP",
	"sparkleholo":                           "Sparkle Holo",
	"stadiumchallenge":                      "Stadium Challenge",
	"starlessholo":                          "Starless Holo",
	"statechampionships":                    "State Championships",
	"stellarcrownstamped":                   "Stellar Crown Stamped",
	"storeexclusive":                        "Store Exclusive",
	"suicunedeck":                           "Suicune Deck",
	"summercollectorchest":                  "Summer Collector Chest",
	"surgingsparksstamped":                  "Surging Sparks Stamped",
	"svscarletvioletpromocards":             "SV Scarlet & Violet Promo Cards",
	"swsh215218":                            "SWSH215-218",
	"swsh287290":                            "SWSH287-290",
	"swshrebelclash":                        "SWSH Rebel Clash",
	"targetpromo":                           "Target Promo",
	"teamflaregear":                         "Team Flare Gear",
	"teamflarehypergear":                    "Team Flare Hyper Gear",
	"teamplasma":                            "Team Plasma",
	"teamrocket":                            "Team Rocket",
	"teamupstamped":                         "Team Up Stamped",
	"temporalforcesstamped":                 "Temporal Forces Stamped",
	"texturefullart":                        "Texture Full Art",
	"thankyou":                              "Thank You",
	"tinselholo":                            "Tinsel Holo",
	"top16":                                 "Top 16",
	"top32":                                 "Top 32",
	"top8":                                  "Top 8",
	"toysrus":                               "Toys \"R\" Us",
	"trainerschallengeset":                  "Trainer's Challenge Set",
	"twilightmasqueradestamped":             "Twilight Masquerade Stamped",
	"ukexclusivepromo":                      "UK Exclusive Promo",
	"ultraballleague":                       "Ultra Ball League",
	"ultraprism":                            "Ultra Prism",
	"unbrokenbondsstamped":                  "Unbroken Bonds Stamped",
	"unovapostercollection":                 "Unova Poster Collection",
	"valuepack":                             "Value Pack",
	"vividvoltagestamped":                   "Vivid Voltage Stamped",
	"vstaruniversejapaneseexclusive":        "VSTAR Universe Japanese Exclusive",
	"warnerbrospromo":                       "Warner Bros Promo",
	"waterwebholo":                          "Water Web Holo",
	"wavefoil":                              "Wave Foil",
	"whatsyourfavoritestamp":                "What's Your Favorite Stamp",
	"whiteflarestamped":                     "White Flare Stamped",
	"withpokemongocode":                     "with Pokemon GO Code",
	"wizardworldchicago":                    "Wizard World Chicago",
	"worldchampionships":                    "World Championships",
	"worldofillusionspromo":                 "World of Illusions Promo",
	"wotcleaguepromo":                       "WotC League Promo",
	"wstamped":                              "W Stamped",
	"xyblackstarpromos":                     "XY Black Star Promos",
	"xyevolutionsprerelease":                "XY Evolutions Prerelease",
	"xysteamsiegeprerelease":                "XY Steam Siege Prerelease",
	"yunagaba":                              "Yu Nagaba",
}

// promoTypeWords spells the words title-casing cannot put back, for the
// labels that do not arrive as a token. A printing the builder left
// unlabelled is read back from its variant, which is words and spaces
// rather than a slug, so those still take the word-by-word path.
//
// The series prefixes are most of it, and they were most of what was
// missing: the catalog writes XY 165 times, SM 55 and CLB, CLC and CLV
// thirteen apiece, and without them "xy evolutions" read back as "Xy
// Evolutions" and the three Classic deck codes as "Clb", "Clc" and "Clv".
//
// The rest are words the game capitalises inside rather than in front:
// DPPt is Diamond & Pearl and Platinum, HeartGold and SoulSilver are two
// halves of a name, and BREAKthrough and BREAKpoint each shout the mechanic
// they are named for. Every spelling here is the catalog's own.
var promoTypeWords = map[string]string{
	"breakpoint":   "BREAKpoint",
	"breakthrough": "BREAKthrough",
	"bw":           "BW",
	"clb":          "CLB",
	"clc":          "CLC",
	"clv":          "CLV",
	"dp":           "DP",
	"dppt":         "DPPt",
	"ex":           "EX",
	"gx":           "GX",
	"heartgold":    "HeartGold",
	"hgss":         "HGSS",
	"pop":          "POP",
	"sm":           "SM",
	"soulsilver":   "SoulSilver",
	"swsh":         "SWSH",
	"tcg":          "TCG",
	"vs":           "VS",
	"wotc":         "WotC",
	"xy":           "XY",
}

// promoTypeLabel spells a promo type the way a reader should see it: the
// words written down above where the token is one the builder published,
// and the words of the label itself title-cased where it is not.
func promoTypeLabel(promoType string) string {
	if label, found := promoTypeLabels[promoType]; found {
		return label
	}
	words := strings.Split(mtgmatcher.Title(promoType), " ")
	for i, word := range words {
		if spelled, found := promoTypeWords[strings.ToLower(word)]; found {
			words[i] = spelled
		}
	}
	return strings.Join(words, " ")
}
