package mtgmatcher

var allVariants = map[string]map[string]string{
	"Aesthir Glider": map[string]string{
		"clouds":                "116a",
		"moon":                  "116b",
		"aesthirglider":         "116a",
		"az002":                 "116b",
		"facing left":           "116a",
		"facing right":          "116b",
		"facing left w/ clouds": "116a",
		"facing right w/ moon":  "116b",
	},
	"Agent of Stromgald": map[string]string{
		"arms crossed":             "64a",
		"holding staff":            "64b",
		"agentofstromgald":         "64a",
		"az003":                    "64b",
		"woman holding staff":      "64b",
		"person with arms crossed": "64a",
		"person with staff":        "64b",
	},
	"Arcane Denial": map[string]string{
		"1":            "22a",
		"2":            "22b",
		"axe":          "22a",
		"sword":        "22b",
		"arcanedenial": "22a",
		"az005":        "22b",
	},
	"Astrolabe": map[string]string{
		"globe/windows":                "118a",
		"map background":               "118b",
		"astrolabe":                    "118a",
		"az009":                        "118b",
		"full room view":               "118a",
		"close-up view":                "118b",
		"astrolabe in front of window": "118a",
		"astrolabe on map":             "118b",
	},
	"Awesome Presence": map[string]string{
		"arms spread":                        "23a",
		"man being chased":                   "23b",
		"awsomepresence":                     "23a",
		"az011":                              "23b",
		"open arms":                          "23a",
		"man being attacked":                 "23b",
		"wizard facing presence":             "23a",
		"wizard and presence facing forward": "23b",
	},
	"Balduvian War-Makers": map[string]string{
		"landscape in background": "66a",
		"green background":        "66b",
		"balduvianwar":            "66a",
		"az016":                   "66b",
		"two clubs, side view":    "66a",
		"sky background":          "66a",
		"3 beards":                "66a",
		"1 beard":                 "66b",
	},
	"Benthic Explorers": map[string]string{
		"sitting on rocks":        "24a",
		"swimming":                "24b",
		"benthicexplorers":        "24a",
		"az018":                   "24b",
		"facing forward":          "24a",
		"facing right":            "24b",
		"explorer facing forward": "24a",
		"explorer facing right":   "24b",
	},
	"Bestial Fury": map[string]string{
		"facing front":       "67a",
		"facing left":        "67b",
		"bestialfury":        "67a",
		"az020":              "67b",
		"ape facing forward": "67a",
		"ape facing left":    "67b",
	},
	"Carrier Pigeons": map[string]string{
		"hand":            "1a",
		"trees":           "1b",
		"carrierpigeons":  "1a",
		"az024":           "1b",
		"man with pigeon": "1a",
		"three pigeons":   "1b",
		"guy with pigeon": "1a",
		"pigeons flying":  "1b",
	},
	"Casting of Bones": map[string]string{
		"finger ornament":       "44a",
		"hooded figure":         "44b",
		"castingofbones":        "44a",
		"az027":                 "44b",
		"hand":                  "44a",
		"hand discarding bones": "44a",
		"person throwing bones": "44b",
	},
	"Deadly Insect": map[string]string{
		"bird":              "86a",
		"elf":               "86b",
		"hummingbird":       "86a",
		"red robe":          "86b",
		"deadlyinsect":      "86a",
		"az030":             "86b",
		"birds and flowers": "86a",
		"red cloak":         "86b",
	},
	"Elvish Ranger": map[string]string{
		"female":       "88a",
		"male":         "88b",
		"elvishranger": "88a",
		"az037":        "88b",
		"woman":        "88a",
		"man":          "88b",
	},
	"Enslaved Scout": map[string]string{
		"crouching":     "71a",
		"horses":        "71b",
		"enslavedscout": "71a",
		"az041":         "71b",
		"solo giant":    "71a",
		"with horse":    "71b",
	},
	"Errand of Duty": map[string]string{
		"page holding sword":        "2a",
		"with horse":                "2b",
		"errandofduty":              "2a",
		"az043":                     "2b",
		"bright red suit":           "2a",
		"horse":                     "2b",
		"person in front of window": "2a",
	},
	"False Demise": map[string]string{
		"rocks":                         "27a",
		"underwater":                    "27b",
		"falsedemise":                   "27a",
		"az046":                         "27b",
		"cave-in":                       "27a",
		"person crawling out of ground": "27a",
		"person underwater":             "27b",
	},
	"Feast or Famine": map[string]string{
		"falling into pit": "49a",
		"knife":            "49b",
		"feastorfamine":    "49a",
		"az049":            "49b",
		"person with dagger at throat": "49b",
	},
	"Fevered Strength": map[string]string{
		"lifting rock":         "50a",
		"foaming mouth":        "50b",
		"feveredstrength":      "50a",
		"az052":                "50b",
		"chains":               "50a",
		"foaming at mouth":     "50b",
		"lifting stone block":  "50a",
		"foaming at the mouth": "50b",
	},
	"Foresight": map[string]string{
		"mermaid with shiny shell":         "29a",
		"white dress":                      "29b",
		"foresight":                        "29a",
		"az056":                            "29b",
		"facing front":                     "29a",
		"facing right":                     "29b",
		"girl facing front with orb":       "29a",
		"mermaid facing right with object": "29b",
	},
	"Fyndhorn Druid": map[string]string{
		"facing left":           "90a",
		"facing right":          "90b",
		"fyndhorndriud":         "90a",
		"az058":                 "90b",
		"facing front":          "90b",
		"red magic aura druid":  "90a",
		"blue magic aura druid": "90b",
	},
	"Gift of the Woods": map[string]string{
		"female":         "92a",
		"male":           "92b",
		"giftofthewoods": "92a",
		"az061":          "92b",
		"woman":          "92a",
		"man/wolf":       "92b",
	},
	"Gorilla Berserkers": map[string]string{
		"closed mouth":      "93a",
		"attacking":         "93b",
		"peaceful":          "93a",
		"roaring":           "93b",
		"gorillaberserkers": "93a",
		"az062":             "93b",
		"holding spear":     "93b",
		"open mouth":        "93b",
	},
	"Gorilla Chieftain": map[string]string{
		"2 gorillas":       "94a",
		"4 gorillas":       "94b",
		"gorillachieftain": "94a",
		"az065":            "94b",
		"two gorillas":     "94a",
		"four gorillas":    "94b",
	},
	"Gorilla Shaman": map[string]string{
		"1":              "72a",
		"2":              "72b",
		"facing left":    "72a",
		"facing right":   "72b",
		"gorillashaman":  "72a",
		"az067":          "72b",
		"holding baby":   "72a",
		"skulls":         "72b",
		"cave drawings":  "72a",
		"skulls on rack": "72b",
	},
	"Gorilla War Cry": map[string]string{
		"colorful headdress":        "73a",
		"red club":                  "73b",
		"gorillawarcry":             "73a",
		"az069":                     "73b",
		"leaning left":              "73a",
		"leaning right":             "73b",
		"gorilla with rainbow neck": "73a",
		"gorilla with leopard neck": "73b",
	},
	"Guerrilla Tactics": map[string]string{
		"tripwire":         "74a",
		"cliff":            "74b",
		"az070":            "74a",
		"guerrillatactics": "74b",
		"kneeling knight":  "74a",
		"cliffside":        "74b",
		"trip wire":        "74a",
		"guy falling":      "74b",
	},
	"Insidious Bookworms": map[string]string{
		"bookshelf":          "51a",
		"single book":        "51b",
		"insidiousbookworms": "51a",
		"az077":              "51b",
		"multiple bookworms": "51a",
		"single bookworm":    "51b",
	},
	"Kjeldoran Escort": map[string]string{
		"green blanketed dog": "7a",
		"red blanketed dog":   "7b",
		"kjeldoranescort":     "7a",
		"az084":               "7b",
		"facing front":        "7a",
		"facing left":         "7b",
		"guy with bow":        "7a",
		"guy with spear":      "7b",
	},
	"Kjeldoran Pride": map[string]string{
		"facing left":     "9a",
		"facing right":    "9b",
		"kjeldoranpride":  "9a",
		"az087":           "9b",
		"kjeldoran pride": "9a",
		"eagle":           "9b",
		"bear":            "9a",
		"blue bear":       "9a",
		"yellow bird":     "9b",
	},
	"Lat-Nam's Legacy": map[string]string{
		"scroll":                 "30a",
		"bookshelf":              "30b",
		"open book":              "30b",
		"book":                   "30b",
		"wizard holding scroll":  "30a",
		"creatures holding book": "30b",
	},
	"Lim-Dûl's High Guard": map[string]string{
		"limdulhighguard": "55a",
		"az095":           "55b",
	},
	"Lim-Dul's High Guard": map[string]string{
		"red armor":    "55a",
		"two swords":   "55b",
		"yellow armor": "55b",
		"gold armor":   "55b",
	},
	"Martyrdom": map[string]string{
		"alive":     "10a",
		"dead":      "10b",
		"martyrdom": "10a",
		"az102":     "10b",
		"knight standing, holding sword": "10a",
		"knight wounded on ground":       "10b",
	},
	"Noble Steeds": map[string]string{
		"trees in forefront":  "11a",
		"two steeds close up": "11b",
		"noblesteeds":         "11a",
		"az110":               "11b",
		"trees":               "11a",
		"close-up view":       "11b",
		"steeds in forest":    "11a",
		"close up of steeds":  "11b",
	},
	"Phantasmal Fiend": map[string]string{
		"close-up":            "57a",
		"doorway":             "57b",
		"phantasmalfiend":     "57a",
		"az113":               "57b",
		"close-up view":       "57a",
		"close up of face":    "57a",
		"in front of doorway": "57b",
	},
	"Phyrexian Boon": map[string]string{
		"female":           "58a",
		"male":             "58b",
		"phyrexianboon":    "58a",
		"az118":            "58b",
		"monster on left":  "58a",
		"monster on right": "58b",
	},
	"Phyrexian War Beast": map[string]string{
		"propeller left":    "127a",
		"propeller right":   "127b",
		"phyrexianwarbeast": "127a",
		"az121":             "127b",
	},
	"Reinforcements": map[string]string{
		"not fighting orc": "12a",
		"fighting orc":     "12b",
		"reinforcements":   "12a",
		"az127":            "12b",
		"ladies":           "12a",
		"goblin":           "12b",
	},
	"Reprisal": map[string]string{
		"red dragon":    "13a",
		"green shark":   "13b",
		"az129":         "13a",
		"reprisal":      "13b",
		"red monster":   "13a",
		"green monster": "13b",
	},
	"Royal Herbalist": map[string]string{
		"female":           "15a",
		"male":             "15b",
		"royalherbalist":   "15a",
		"az133":            "15b",
		"female herbalist": "15a",
		"male herbalist":   "15b",
	},
	"Soldevi Adnate": map[string]string{
		"female":              "60a",
		"male":                "60b",
		"two eyes":            "60a",
		"soldeviadanate":      "60a",
		"az142":               "60b",
		"one eye":             "60b",
		"woman w/ face-paint": "60a",
		"man with cloak":      "60b",
	},
	"Soldevi Heretic": map[string]string{
		"blue robe":      "33a",
		"red robe":       "33b",
		"soldeviheretic": "33a",
		"az146":          "33b",
		"heretic pointing at other man": "33a",
		"heretic with both arms raised": "33b",
	},
	"Soldevi Sage": map[string]string{
		"2 candles":              "34a",
		"old woman sitting":      "34b",
		"soldevisage":            "34a",
		"az149":                  "34b",
		"male":                   "34a",
		"female":                 "34b",
		"wizard writing in book": "34b",
	},
	"Soldevi Sentry": map[string]string{
		"close up":               "132a",
		"silver sentry fighting": "132b",
		"soldevisentry":          "132a",
		"az150":                  "132b",
		"close-up view":          "132a",
		"attacking":              "132b",
		"sentry portrait":        "132a",
		"sentry in combat":       "132b",
	},
	"Soldevi Steam Beast": map[string]string{
		"beast in mountains": "133a",
		"purple sun":         "133b",
		"soldevisteambeast":  "133a",
		"az152":              "133b",
		"mountain":           "133a",
		"pink sun":           "133b",
	},
	"Stench of Decay": map[string]string{
		"hand covering nose": "61a",
		"red flower":         "61b",
		"stenchofdecay":      "61a",
		"az157":              "61b",
		"covering face":      "61a",
		"flower":             "61b",
		"holding flower":     "61b",
	},
	"Storm Crow": map[string]string{
		"flying left":       "36a",
		"flying right":      "36b",
		"stormcrow":         "36a",
		"az161":             "36b",
		"crow flying left":  "36a",
		"crow flying right": "36b",
	},
	"Storm Shaman": map[string]string{
		"female":               "81a",
		"male":                 "81b",
		"stormshaman":          "81a",
		"az163":                "81b",
		"woman":                "81a",
		"man with snake staff": "81b",
	},
	"Swamp Mosquito": map[string]string{
		"black trees":             "63a",
		"brown trees":             "63b",
		"swampmosquito":           "63a",
		"az169":                   "63b",
		"fallen tree":             "63a",
		"mosquito facing left":    "63a",
		"mosquito facing forward": "63b",
	},
	"Taste of Paradise": map[string]string{
		"woman alone":              "100a",
		"two people":               "100b",
		"tasteofparadise":          "100a",
		"az172":                    "100b",
		"one person holding fruit": "100a",
		"man and woman":            "100b",
		"one person":               "100a",
	},
	"Undergrowth": map[string]string{
		"fox and badger": "102a",
		"holding axe":    "102b",
		"undergrowth":    "102a",
		"az178":          "102b",
		"fox":            "102a",
		"elf":            "102b",
		"man with axe":   "102b",
	},
	"Varchild's Crusader": map[string]string{
		"black horse and hollow log": "82a",
		"brown horse and castle":     "82b",
		"varchildcrusader":           "82a",
		"az182":                      "82b",
		"forest":                     "82a",
		"castle":                     "82b",
		"in forest":                  "82a",
		"overlooking castle":         "82b",
	},
	"Veteran's Voice": map[string]string{
		"over the shoulder":          "84a",
		"side-by-side":               "84b",
		"veteranvoice":               "84a",
		"az185":                      "84b",
		"men standing together":      "84a",
		"men standing apart":         "84b",
		"men next to each other":     "84a",
		"men across from each other": "84b",
	},
	"Viscerid Armor": map[string]string{
		"crashing wave":         "41a",
		"humans in foreground":  "41b",
		"visceridarmor":         "41a",
		"az187":                 "41b",
		"alone":                 "41a",
		"attacking two men":     "41b",
		"armor in water":        "41a",
		"armor fighting people": "41b",
	},
	"Whip Vine": map[string]string{
		"3 vines":        "103a",
		"ensnared bird":  "103b",
		"whipvine":       "103a",
		"az192":          "103b",
		"no bird":        "103a",
		"bird":           "103b",
		"just vines":     "103a",
		"bird and vines": "103b",
	},
	"Wild Aesthir": map[string]string{
		"blue mountains":    "21a",
		"green background":  "21b",
		"wildaethir":        "21a",
		"az195":             "21b",
		"wings thrown back": "21b",
		"lightning":         "21a",
		"rain":              "21b",
	},
	"Yavimaya Ancients": map[string]string{
		"rearing horse":    "104a",
		"trees":            "104b",
		"yavimayaancients": "104a",
		"az197":            "104b",
		"horse":            "104a",
		"no horse":         "104b",
		"man on horse":     "104a",
		"person in tree":   "104b",
	},
}

var athVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a":        "84",
		"b":        "85",
		"arena":    "84",
		"portal 2": "85",
	},
	"Mountain": map[string]string{
		"a":                     "82",
		"b":                     "83",
		"arabian nights":        "82",
		"mirage":                "83",
		"#40 by douglas shuler": "82",
		"#41 by john avon":      "83",
	},
	"Plains": map[string]string{
		"a":                     "78",
		"b":                     "79",
		"mirage":                "78",
		"portal":                "79",
		"#86 by tom w":          "78",
		"#87 by douglas shuler": "79",
	},
	"Swamp": map[string]string{
		"a":                     "80",
		"b":                     "81",
		"ice age":               "80",
		"tempest":               "81",
		"#42 by douglas shuler": "80",
		"#43 by brom":           "81",
	},
}

var atqVariants = map[string]map[string]string{
	"Mishra's Factory": map[string]string{
		"aq044":                    "80a",
		"aq045":                    "80b",
		"atq-80c-mishra-s-factory": "80c",
		"aq046":                    "80d",

		"b spring": "80a",
		"c summer": "80b",
		"a fall":   "80c",
		"d winter": "80d",

		"spring": "80a",
		"summer": "80b",
		"autumn": "80c",
		"winter": "80d",

		"summer green":  "80b",
		"autumn orange": "80c",
		"winter snow":   "80d",

		"fall": "80c",

		"spring picture": "80a",
		"summer picture": "80b",
		"fall picture":   "80c",
		"winter picture": "80d",
	},
	"Strip Mine": map[string]string{
		"atq-82a-strip-mine": "82a",
		"atq-82b-strip-mine": "82b",
		"atq-82c-strip-mine": "82c",
		"aq070":              "82d",

		"no sky, no tower":    "82a",
		"sky, even terraces":  "82b",
		"no sky wth tower":    "82c",
		"sky uneven terraces": "82d",

		"no sky, no cave/tower": "82a",
		"cave":                  "82b",
		"tower":                 "82c",
		"sky, no cave or tower": "82d",

		"no horizon":    "82a",
		"even horizon":  "82b",
		"small tower":   "82c",
		"uneven stripe": "82d",

		"no sky, tower":        "82c",
		"sky, uneven terraces": "82d",

		"c no horizon": "82a",
		"a even":       "82b",
		"d tower":      "82c",
		"b uneven":     "82d",

		"uneven horizon": "82b",

		"even stripe":           "82b",
		"small tower in forest": "82c",

		"large steppes no tower no sky":  "82a",
		"cave no tower sky":              "82b",
		"tower no cave":                  "82c",
		"small steppes no cave no tower": "82d",
	},
	"Urza's Mine": map[string]string{
		"aq084": "83a",
		"aq085": "83b",
		"aq083": "83c",
		"aq086": "83d",

		"pulley":           "83a",
		"mouth":            "83b",
		"submerged sphere": "83c",
		"tower":            "83d",

		"mine face": "83b",
		"sphere":    "83c",
		"ladder":    "83d",

		"clawed sphere": "83c",

		"a bathyscape": "83c",
		"b mouth":      "83b",
		"c pulley":     "83a",
		"d tower":      "83d",

		"rope and pulley":              "83a",
		"mine's face":                  "83b",
		"ball lowered in lava":         "83c",
		"pillar with ladder and ropes": "83d",
	},
	"Urza's Power Plant": map[string]string{
		"aq089": "84a",
		"aq090": "84b",
		"aq088": "84c",
		"aq091": "84d",

		"sphere":  "84a",
		"columns": "84b",
		"bug":     "84c",
		"pot":     "84d",

		"sphere with tubes": "84a",
		"red columns":       "84b",
		"rock in pan":       "84d",

		"rock in pot": "84d",

		"c sphere": "84a",
		"b pillar": "84b",
		"a bug":    "84c",
		"d vat":    "84d",

		"ball in pit with tubes": "84a",
		"red pillars":            "84b",
		"electric fly":           "84c",
	},
	"Urza's Tower": map[string]string{
		"aq092": "85a",
		"aq093": "85b",
		"aq094": "85c",
		"aq095": "85d",

		"red leaves":            "85a",
		"sunset with shoreline": "85b",
		"plains":                "85c",
		"mountains":             "85d",

		"forest": "85a",
		"shore":  "85b",

		"a forest":   "85a",
		"d seashore": "85b",
		"c plains":   "85c",
		"b mountain": "85d",

		"fall leaves":                 "85a",
		"sun and water in background": "85b",
		"plains with wheat":           "85c",
	},
}

var pal01Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"arena 2001 foil":           "1",
		"arena 2002 foil":           "11",
		"arena ia":                  "1",
		"arena beta":                "11",
		"arena 2001 ice age":        "1",
		"arena 2002 beta":           "11",
		"ice age art arena 2001":    "1",
		"beta art arena 2001":       "11",
		"arena 2001":                "1",
		"arena 2002":                "11",
		"arena ice age":             "1",
		"arena ice age art 2001":    "1",
		"arena beta art 2001":       "11",
		"arena 2001 foil - ice age": "1",
		"arena 2001 foil - beta":    "11",
	},
}

var palpVariants = map[string]map[string]string{
	"Swamp": map[string]string{
		"ron spears, fireballs":                              "10",
		"ron spears, zombie":                                 "15",
		"apac b taiwan":                                      "10",
		"apac c australia":                                   "15",
		"indonesia":                                          "15",
		"ron spears, graveyard":                              "10",
		"ron spears, small person":                           "15",
		"apac set red pack graveyard":                        "10",
		"apac set clear pack person in swamp":                "15",
		"apac land japan fire in graveyard, ron spears art":  "10",
		"apac land indonesia zombie in swamp ron spears art": "15",
		"apac blue taiwan":                                   "10",
		"apac clear australia":                               "15",
		"japan apac two ron spears art":                      "10",
		"indonesia apac three ron spears art":                "15",
		"apac land ron spears, fireballs":                    "10",
		"apac land ron spears, zombie":                       "15",
	},
}

var brbVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a": "103",
		"b": "104",
		"c": "109",
		"d": "107",
		"e": "108",
		"f": "101",
		"g": "102",
		"h": "105",
		"i": "106",
		"1": "101",
		"2": "102",
		"3": "103",
		"4": "104",
		"5": "105",
		"6": "106",
		"7": "107",
		"8": "108",
		"9": "109",
	},
	"Island": map[string]string{
		"a": "112",
		"b": "114",
		"c": "113",
		"d": "111",
		"e": "110",
		"1": "110",
		"2": "111",
		"3": "112",
		"4": "114",
		"5": "113",
	},
	"Mountain": map[string]string{
		"a": "118",
		"b": "119",
		"c": "115",
		"d": "116",
		"e": "117",
		"f": "120",
		"g": "121",
		"h": "122",
		"i": "123",
		"1": "115",
		"2": "116",
		"3": "117",
		"4": "118",
		"5": "119",
		"6": "120",
		"7": "121",
		"8": "122",
		"9": "123",
	},
	"Plains": map[string]string{
		"a": "127",
		"b": "128",
		"c": "130",
		"d": "131",
		"e": "132",
		"f": "125",
		"g": "124",
		"h": "126",
		"i": "129",
		"1": "124",
		"2": "125",
		"3": "126",
		"4": "127",
		"5": "128",
		"6": "129",
		"7": "130",
		"8": "131",
		"9": "132",
	},
	"Swamp": map[string]string{
		"a": "133",
		"b": "134",
		"c": "136",
		"d": "135",
		"1": "133",
		"2": "134",
		"3": "135",
		"4": "136",
	},
}

var chkVariants = map[string]map[string]string{
	"Brothers Yamazaki": map[string]string{
		"facing left":         "160a",
		"facing right":        "160b",
		"a":                   "160a",
		"b":                   "160b",
		"art a 2 swords":      "160a",
		"art b with pole arm": "160b",
	},
}

var oldLandVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a": "300",
		"b": "301",
		"c": "302",

		"a rocks":     "300",
		"b path":      "301",
		"c dark tree": "302",

		"b - not tournament legal": "300",
		"a - not tournament legal": "301",
		"c - not tournament legal": "302",

		"b rocks":            "300",
		"a pathway":          "301",
		"c eyes in treehole": "302",

		"boulders foreground": "300",
		"brown dirt road":     "301",
		"dark and gloomy":     "302",

		"b not tournament legal": "300",
		"a not tournament legal": "301",
		"c not tournament legal": "302",

		"#280 by christopher rush": "300",
		"#281 by christopher rush": "301",
		"#282 by christopher rush": "302",
	},
	"Island": map[string]string{
		"a": "291",
		"b": "292",
		"c": "293",

		"a purple":       "291",
		"b light purple": "292",
		"c dark purple":  "293",

		"b - not tournament legal": "291",
		"a - not tournament legal": "292",
		"c - not tournament legal": "293",

		"b purple island, gold horizon":   "291",
		"a green island":                  "292",
		"c purple island, orange horizon": "293",

		"golden horizon":      "291",
		"clear blue daylight": "292",
		"pink & orange dusk":  "293",

		"b not tournament legal": "291",
		"a not tournament legal": "292",
		"c not tournament legal": "293",

		"#283 by mark poole": "291",
		"#284 by mark poole": "292",
		"#285 by mark poole": "293",
	},
	"Mountain": map[string]string{
		"a": "297",
		"b": "298",
		"c": "299",

		"a small tree": "297",
		"b snowy":      "298",
		"c dark red":   "299",

		"b - not tournament legal": "297",
		"a - not tournament legal": "298",
		"c - not tournament legal": "299",

		"b gray mountains":            "297",
		"a blue mountains":            "298",
		"c brown mountain, green sky": "299",

		"grey mountain / red sky":    "297",
		"light blue sky/snow":        "298",
		"dark green clouds/blue sky": "299",

		"b not tournament legal": "297",
		"a not tournament legal": "298",
		"c not tournament legal": "299",

		"#288 by douglas schuler": "297",
		"#286 by douglas schuler": "298",
		"#287 by douglas shuler":  "299",
	},
	"Plains": map[string]string{
		"b": "288",
		"a": "289",
		"c": "290",

		"a light":        "288",
		"b little trees": "289",
		"c dark":         "290",

		"b - not tournament legal": "288",
		"a - not tournament legal": "289",
		"c - not tournament legal": "290",

		"b no trees on plain":   "288",
		"a trees on plain":      "289",
		"c cliff in background": "290",

		"six trees":               "288",
		"four peaks clear meadow": "289",
		"pink horizon":            "290",

		"b not tournament legal": "288",
		"a not tournament legal": "289",
		"c not tournament legal": "290",

		"#289 by jesper myrfors": "289",
		"#290 by jesper myrfors": "288",
		"#291 by jesper myrfors": "290",
	},
	"Swamp": map[string]string{
		"a": "294",
		"b": "295",
		"c": "296",

		"5219":   "294",
		"un248":  "295",
		"swamp2": "296",

		"a light":        "294",
		"b two branches": "295",
		"c dark":         "296",

		"b - not tournament legal": "294",
		"a - not tournament legal": "295",
		"c - not tournament legal": "296",

		"b one branch in foreground": "294",
		"a brown, two branches":      "295",
		"c black, two branches":      "296",

		"blue and foggy":       "294",
		"brown and foggy":      "295",
		"dark grey foreground": "296",

		"b not tournament legal": "294",
		"a not tournament legal": "295",
		"c not tournament legal": "296",

		"#295 by dan frazier": "294",
		"#296 by dan frazier": "295",
		"#297 by dan frazier": "296",
	},
}

var cm2Variants = map[string]map[string]string{
	"Golgari Signet": map[string]string{
		"/it/info-prodotto/284/1214/259602/commander-anthology-2018-golgari-signet": "191",
		"/it/info-prodotto/284/1214/259603/commander-anthology-2018-golgari-signet": "192",
		"cm2v2": "191",
		"cm2":   "192",
	},
	"Simic Signet": map[string]string{
		"/it/info-prodotto/284/1214/259716/commander-anthology-2018-simic-signet": "215",
		"/it/info-prodotto/284/1214/259717/commander-anthology-2018-simic-signet": "216",
		"":   "215",
		"v3": "216",
	},
	"Solemn Simulacrum": map[string]string{
		"/it/info-prodotto/284/1214/259722/commander-anthology-2018-solemn-simulacrum": "218",
		"/it/info-prodotto/284/1214/259723/commander-anthology-2018-solemn-simulacrum": "219",
		".":       "218",
		"__219v2": "219",
	},
	"Temple of the False God": map[string]string{
		"/it/info-prodotto/284/1214/259753/commander-anthology-2018-temple-of-the-false-god": "271",
		"/it/info-prodotto/284/1214/259754/commander-anthology-2018-temple-of-the-false-god": "272",

		"templeofthefalse_god271": "271",
		".": "272",
	},
}

var chrVariants = map[string]map[string]string{
	"Urza's Mine": map[string]string{
		"ch094": "114a",
		"ch095": "114b",
		"ch096": "114c",
		"ch097": "114d",

		"mine face": "114a",
		"sphere":    "114b",
		"pulley":    "114c",
		"tower":     "114d",

		"mouth":            "114a",
		"submerged sphere": "114b",
		"ladder":           "114d",

		"clawed sphere": "114b",
		"watchtower":    "114d",

		"b mouth":      "114a",
		"a bathyscape": "114b",
		"c pully":      "114c",
		"d tower":      "114d",

		"mine's face":          "114a",
		"ball lowered in lava": "114b",
		"rope and pulley":      "114c",
		"tower with ladder":    "114d",
	},
	"Urza's Power Plant": map[string]string{
		"ch098": "115a",
		"ch099": "115b",
		"ch101": "115c",
		"ch100": "115d",

		"pot":     "115a",
		"columns": "115b",
		"sphere":  "115c",
		"bug":     "115d",

		"rock in pan":       "115a",
		"red columns":       "115b",
		"sphere with tubes": "115c",

		"rock in pot": "115a",

		"d vat":    "115a",
		"b pillar": "115b",
		"c sphere": "115c",
		"a bug":    "115d",

		"red pillars":  "115b",
		"ball in pit":  "115c",
		"electric fly": "115d",

		"rock pot": "115a",
	},
	"Urza's Tower": map[string]string{
		"ch105": "116a",
		"ch103": "116b",
		"ch104": "116c",
		"ch102": "116d",

		"forest":     "116a",
		"plains":     "116b",
		"mountains":  "116c",
		"red leaves": "116d",

		"sunset with shoreline": "116a",
		"shore":                 "116d",

		"a forest":   "116a",
		"c plains":   "116b",
		"b mountain": "116c",
		"d seashore": "116d",

		"fall leaves":                 "116a",
		"cloudy skies wheat field":    "116b",
		"mountain in background":      "116c",
		"sun and water in background": "116d",
	},
}

var cn2Variants = map[string]map[string]string{
	"Kaya, Ghost Assassin": map[string]string{
		"cn2075":               "75",
		"kaya_ghost_assassin2": "222",
	},
}

var dkmVariants = map[string]map[string]string{
	"Guerrilla Tactics": map[string]string{
		"man kneeling near tree": "13a",
		"man falling off clif":   "13b",
	},
	"Lim-Dul's High Guard": map[string]string{
		"red armor": "6a",
		"2 swords":  "6b",
	},
	"Phantasmal Fiend": map[string]string{
		"black background": "8a",
		"brick background": "8b",
	},
	"Phyrexian War Beast": map[string]string{
		"facing left":  "37a",
		"facing right": "37b",
	},
	"Storm Shaman": map[string]string{
		"red cloak":   "21a",
		"green cloak": "21b",
	},
	"Yavimaya Ancients": map[string]string{
		"rearing horse":  "31a",
		"trees":          "31b",
		"man on horse":   "31a",
		"person in tree": "31b",
	},
}

var femVariants = map[string]map[string]string{
	"Armor Thrull": map[string]string{
		"fe001": "33a",
		"fe002": "33b",
		"fe003": "33c",
		"fe004": "33d",
	},
	"Basal Thrull": map[string]string{
		"fe005": "34a",
		"fe006": "34b",
		"fe007": "34c",
		"fe008": "34d",
	},
	"Brassclaw Orcs": map[string]string{
		"fe100":                       "49a",
		"fe101":                       "49b",
		"fe102":                       "49c",
		"fe103":                       "49d",
		"rob alexander, spear":        "49a",
		"rob alexander, no spear":     "49c",
		"rob alexander, gloved fist":  "49c",
		"rob alexander spear":         "49a",
		"rob alexander winged helmet": "49c",
	},
	"Combat Medic": map[string]string{
		"fe133": "1a",
		"fe134": "1b",
		"fe135": "1c",
		"fe136": "1d",
	},
	"Dwarven Soldier": map[string]string{
		"fe107":           "53a",
		"fe108":           "53b",
		"fe109":           "53c",
		"douglas schuler": "53c",
	},
	"Elven Fortress": map[string]string{
		"fe067": "65a",
		"fe068": "65b",
		"fe069": "65c",
		"fe070": "65d",
	},
	"Elvish Hunter": map[string]string{
		"fe072": "67a",
		"fe073": "67b",
		"fe074": "67c",
	},
	"Elvish Scout": map[string]string{
		"fe075": "68a",
		"fe076": "68b",
		"fe077": "68c",
	},
	"Farrel's Zealot": map[string]string{
		"fe139": "3a",
		"fe140": "3b",
		"fe141": "3c",
	},
	"Goblin Chirurgeon": map[string]string{
		"fe110": "54a",
		"fe111": "54b",
		"fe112": "54c",
	},
	"Goblin Grenade": map[string]string{
		"1":     "56b",
		"2":     "56c",
		"fe114": "56a",
		"fe115": "56b",
		"fe116": "56c",
	},
	"Goblin War Drums": map[string]string{
		"fe119": "58a",
		"fe120": "58b",
		"fe121": "58c",
		"fe122": "58d",
	},
	"High Tide": map[string]string{
		"fe035": "18a",
		"fe036": "18b",
		"fe037": "18c",
		"2":     "18a",
		"1":     "18b",
		"3":     "18c",
	},
	"Homarid": map[string]string{
		"fe038": "19a",
		"fe039": "19b",
		"fe040": "19c",
		"fe041": "19d",
		"18c":   "19c",
	},
	"Homarid Warrior": map[string]string{
		"fe044": "22a",
		"fe045": "22b",
		"fe046": "22c",
	},
	"Hymn to Tourach": map[string]string{
		"4":     "38a",
		"1":     "38b",
		"2":     "38c",
		"3":     "38d",
		"fe012": "38a",
		"fe013": "38b",
		"fe014": "38c",
		"fe015": "38d",
	},
	"Icatian Infantry": map[string]string{
		"fe144": "7a",
		"fe145": "7b",
		"fe146": "7c",
		"fe147": "7d",
	},
	"Icatian Javelineers": map[string]string{
		"fe148": "8a",
		"fe149": "8b",
		"fe150": "8c",
	},
	"Icatian Moneychanger": map[string]string{
		"fe152": "10a",
		"fe153": "10b",
		"fe154": "10c",
	},
	"Icatian Scout": map[string]string{
		"fe157": "13a",
		"fe158": "13b",
		"fe159": "13c",
		"fe160": "13d",
	},
	"Initiates of the Ebon Hand": map[string]string{
		"fe016": "39a",
		"fe017": "39b",
		"fe018": "39c",
	},
	"Merseine": map[string]string{
		"fe047": "23a",
		"fe048": "23b",
		"fe049": "23c",
		"fe050": "23d",
	},
	"Mindstab Thrull": map[string]string{
		"fe019": "40a",
		"fe020": "40b",
		"fe021": "40c",
	},
	"Necrite": map[string]string{
		"fe022": "41a",
		"fe023": "41b",
		"fe024": "41c",
	},
	"Night Soil": map[string]string{
		"fe080": "71a",
		"fe081": "71b",
		"fe082": "71c",
	},
	"Orcish Spy": map[string]string{
		"fe124": "61a",
		"fe125": "61b",
		"fe126": "61c",
	},
	"Orcish Veteran": map[string]string{
		"fe127": "62a",
		"fe128": "62b",
		"fe129": "62c",
		"fe130": "62d",
	},
	"Order of the Ebon Hand": map[string]string{
		"fe025": "42a",
		"fe026": "42b",
		"fe027": "42c",
		"centaur with sword and shield":       "42a",
		"girl with sword imbedded in ground":  "42b",
		"guy with jagged shield and hand axe": "42c",
	},
	"Order of Leitbur": map[string]string{
		"fe163": "16a",
		"fe164": "16b",
		"fe165": "16c",
		"facing right, bryon wackwitz":  "16a",
		"facing left, bryon wackwitz":   "16b",
		"bryon wackwitz, female knight": "16a",
		"bryon wackwitz, male knight":   "16b",
		"girl with standard on horse":   "16a",
		"guy with shield on horse":      "16b",
	},
	"Spore Cloud": map[string]string{
		"fe083": "72a",
		"62b":   "72b",
		"fe084": "72b",
		"fe085": "72c",
	},
	"Thallid": map[string]string{
		"fe087": "74a",
		"fe088": "74b",
		"fe089": "74c",
		"fe090": "74d",
	},
	"Thorn Thallid": map[string]string{
		"fe096": "80a",
		"fe097": "80b",
		"fe098": "80c",
		"fe099": "80d",
	},
	"Tidal Flats": map[string]string{
		"fe054": "27a",
		"fe055": "27b",
		"fe056": "27c",
		"rob alexander lush horizon":       "27a",
		"rob alexander sun through clouds": "27b",
		"rob alexander, lake":              "27a",
		"rob alexander, sun":               "27b",
		"rob alexander no sun":             "27a",
		"rob alexander sun visible":        "27b",
	},
	"Vodalian Mage": map[string]string{
		"poole": "30b",
		"fe059": "30a",
		"fe060": "30b",
		"fe061": "30c",
	},
	"Vodalian Soldiers": map[string]string{
		"fe062": "31a",
		"fe063": "31b",
		"fe064": "31c",
		"fe065": "31d",
	},
}

var ed5Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"a":                             "446",
		"c":                             "447",
		"b":                             "448",
		"d":                             "449",
		"417":                           "446",
		"418 night":                     "447",
		"419 blue sky // yellow clouds": "448",
		"420 snow":                      "449",
	},
	"Island": map[string]string{
		"a":   "434",
		"d":   "435",
		"c":   "436",
		"b":   "437",
		"425": "434",
		"426": "435",
		"427": "436",
		"428": "437",
	},
	"Mountain": map[string]string{
		"a":               "442",
		"d":               "443",
		"c":               "444",
		"b":               "445",
		"430":             "442",
		"432 brown trees": "443",
		"431 fog":         "444",
		"433 flowers":     "445",
	},
	"Plains": map[string]string{
		"a":                         "430",
		"d":                         "431",
		"b":                         "432",
		"c":                         "433",
		"434 winter":                "430",
		"435 lone tree in distance": "431",
		"436 wheat":                 "432",
		"437 rippling hill":         "433",
	},
	"Swamp": map[string]string{
		"d":                     "438",
		"b":                     "439",
		"a":                     "440",
		"c":                     "441",
		"442 broken trees":      "438",
		"443 center right tree": "439",
		"444 fallen tree":       "440",
		"445 center left tree":  "441",
	},
}

var ed4Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"a":                       "376",
		"b":                       "377",
		"c":                       "378",
		"a rocks":                 "376",
		"b path":                  "377",
		"c dark tree":             "378",
		"177 boulders foreground": "376",
		"175 brown dirt road":     "377",
		"176 dark and gloomy":     "378",
	},
	"Island": map[string]string{
		"a":                       "367",
		"b":                       "368",
		"c":                       "369",
		"a purple":                "367",
		"b light purple":          "368",
		"c dark purple":           "369",
		"179 golden horizon":      "367",
		"178 clear blue daylight": "368",
		"180 pink & orange dusk":  "369",
	},
	"Mountain": map[string]string{
		"a":                              "373",
		"b":                              "374",
		"c":                              "375",
		"a small tree":                   "373",
		"b snowy":                        "374",
		"c dark red":                     "375",
		"183 grey mountain / red sky":    "373",
		"184 light blue sky/snow":        "374",
		"182 dark green clouds/blue sky": "375",
	},
	"Plains": map[string]string{
		"a":                           "364",
		"b":                           "365",
		"c":                           "366",
		"a light":                     "364",
		"b little trees":              "365",
		"c dark":                      "366",
		"188 four peaks clear meadow": "364",
		"187 six trees":               "365",
		"186 pink horizon":            "366",
	},
	"Swamp": map[string]string{
		"a":                        "370",
		"b":                        "371",
		"c":                        "372",
		"a light":                  "370",
		"b two branches":           "371",
		"c dark":                   "372",
		"192 blue and foggy":       "370",
		"190 brown and foggy":      "371",
		"191 dark grey foreground": "372",
	},
}

var prwkVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"ravnica weekend golgari":  "A06",
		"ravnica weekend selesnya": "A09",
	},
	"Island": map[string]string{
		"ravnica weekend dimir": "A01",
		"ravnica weekend izzet": "A03",
	},
	"Mountain": map[string]string{
		"ravnica weekend izzet": "A04",
		"ravnica weekend boros": "A07",
	},
	"Plains": map[string]string{
		"ravnica weekend boros":    "A08",
		"ravnica weekend selesnya": "A10",
	},
	"Swamp": map[string]string{
		"ravnica weekend dimir":   "A02",
		"ravnica weekend golgari": "A05",
	},
}

var hmlVariants = map[string]map[string]string{
	"Abbey Matron": map[string]string{
		"hood":                    "2a",
		"no hood":                 "2b",
		"or003":                   "2a",
		"abbeymatron":             "2b",
		"hair covered":            "2a",
		"pointing to bottom left": "2b",
		"pointing straight ahead": "2a",
		"pointing down":           "2b",
	},
	"Aliban's Tower": map[string]string{
		"glowing tower":     "61a",
		"knights on horses": "61b",
		"or006":             "61a",
		"alibanstower":      "61b",
		"black":             "61a",
		"horses":            "61b",
		"rider on horse":    "61b",
	},
	"Ambush Party": map[string]string{
		"doorway":        "63a",
		"mountain":       "63b",
		"or007":          "63a",
		"ambushparty":    "63b",
		"torch":          "63a",
		"mountainside":   "63b",
		"doorway ambush": "63a",
		"mountain path":  "63b",
	},
	"Anaba Bodyguard": map[string]string{
		"alone":              "66a",
		"with human":         "66b",
		"or012":              "66a",
		"anababodyguard":     "66b",
		"green cloak":        "66a",
		"tongue out":         "66b",
		"bodyguard alone":    "66a",
		"with hooded figure": "66b",
	},
	"Anaba Shaman": map[string]string{
		"facing right": "67b",
		"facing left":  "67a",
		"anabashaman":  "67a",
		"or014":        "67b",
	},
	"Aysen Bureaucrats": map[string]string{
		"one bureaucrat":   "3a",
		"two bureaucrats":  "3b",
		"or023":            "3a",
		"aysenbureaucrats": "3b",
		"a person":         "3a",
		"two people":       "3b",
	},
	"Carapace": map[string]string{
		"purple carapace":  "84a",
		"red carapace":     "84b",
		"or033":            "84a",
		"carapace":         "84b",
		"in a tree":        "84a",
		"sword":            "84b",
		"person on tree":   "84a",
		"woman with sword": "84b",
	},
	"Cemetery Gate": map[string]string{
		"no zombie":      "44a",
		"zombie":         "44b",
		"or035":          "44a",
		"cemeterygate":   "44b",
		"just the gate":  "44a",
		"vamp in red":    "44b",
		"gate with mist": "44a",
		"zombie at gate": "44b",
	},
	"Dark Maze": map[string]string{
		"man kneeling":     "25a",
		"man laying down":  "25b",
		"darkmaze":         "25a",
		"or043":            "25b",
		"sword & shield":   "25a",
		"laying on ground": "25b",
		"warrior kneeling": "25a",
		"warrior fallen":   "25b",
	},
	"Dry Spell": map[string]string{
		"fish bones":       "46a",
		"skull with helm":  "46b",
		"dryspell":         "46a",
		"or050":            "46b",
		"fish":             "46a",
		"skull":            "46b",
		"helmet and skull": "46b",
	},
	"Dwarven Trader": map[string]string{
		"man and woman":    "72a",
		"woman and horse":  "72b",
		"or054":            "72a",
		"dwarventrader":    "72b",
		"two people":       "72a",
		"horse":            "72b",
		"woman with horse": "72b",
	},
	"Feast of the Unicorn": map[string]string{
		"goblins":           "47a",
		"horse head":        "47b",
		"or059":             "47a",
		"unicornfeast":      "47b",
		"green creature":    "47a",
		"head on a platter": "47b",
		"goblin with horn":  "47a",
		"head on platter":   "47b",
	},
	"Folk of An-Havva": map[string]string{
		"dancing":         "87a",
		"sitting on wall": "87b",
		"or062":           "87a",
		"folkofan":        "87b",
		"hoedown":         "87a",
		"pensive":         "87b",
		"people dancing":  "87a",
	},
	"Giant Albatross": map[string]string{
		"ship's mast":      "27a",
		"clouds":           "27b",
		"or068":            "27a",
		"giantalbatro":     "27b",
		"over a ship":      "27a",
		"over ocean":       "27b",
		"ship":             "27a",
		"saddle":           "27b",
		"flying near ship": "27a",
		"flying right":     "27b",
	},
	"Hungry Mist": map[string]string{
		"lantern":          "88a",
		"no lantern":       "88b",
		"hungrymist":       "88a",
		"or075":            "88b",
		"on roof":          "88a",
		"attacking neck":   "88b",
		"above house":      "88a",
		"attacking person": "88b",
	},
	"Labyrinth Minotaur": map[string]string{
		"maze background":   "30a",
		"black background":  "30b",
		"or086":             "30a",
		"labyrinthminotaur": "30b",
		"miner":             "30a",
		"tattooed face":     "30b",
		"with pickaxe":      "30a",
		"minotaur's face":   "30b",
	},
	"Memory Lapse": map[string]string{
		"female":       "32a",
		"male":         "32b",
		"or093":        "32a",
		"memorylapse":  "32b",
		"woman's head": "32a",
		"man's head":   "32b",
		"puzzle woman": "32a",
		"bald man":     "32b",
	},
	"Mesa Falcon": map[string]string{
		"flying":          "10a",
		"perched":         "10b",
		"or096":           "10a",
		"mesafalcon":      "10b",
		"blue sky":        "10a",
		"perched in tree": "10b",
	},
	"Reef Pirates": map[string]string{
		"zombies":     "36a",
		"ships":       "36b",
		"or104":       "36a",
		"reefpirates": "36b",
		"two pirates": "36a",
		"two ships":   "36b",
		"pirate ship": "36b",
	},
	"Samite Alchemist": map[string]string{
		"window":           "13a",
		"green beaker":     "13b",
		"or112":            "13a",
		"samitealchemist":  "13b",
		"with window":      "13a",
		"no window":        "13b",
		"alchemist's face": "13a",
		"purple vest":      "13b",
	},
	"Sengir Bats": map[string]string{
		"perching":   "57a",
		"flying":     "57b",
		"or118":      "57a",
		"sengirbats": "57b",
		"perched":    "57a",
		"hanging":    "57a",
		"green bats": "57a",
		"orange bat": "57b",
	},
	"Shrink": map[string]string{
		"man in shadow":        "97a",
		"giant woman":          "97b",
		"or125":                "97a",
		"shrink":               "97b",
		"in shadow looking up": "97a",
		"female with sword":    "97b",
		"person in shadow":     "97a",
	},
	"Torture": map[string]string{
		"man with markings":     "59a",
		"hooded figure":         "59b",
		"or130":                 "59a",
		"torture":               "59b",
		"back":                  "59a",
		"table and tools":       "59b",
		"hooded torturer":       "59a",
		"drawing on man's back": "59b",
	},
	"Trade Caravan": map[string]string{
		"giraffe on right":   "19a",
		"moon top left":      "19b",
		"tradecaravan":       "19a",
		"or132":              "19b",
		"no moon":            "19a",
		"moon":               "19b",
		"giraffe":            "19a",
		"full moon":          "19b",
		"large white spider": "19b",
	},
	"Willow Faerie": map[string]string{
		"male":          "99a",
		"female":        "99b",
		"or137":         "99a",
		"willowfaerie":  "99b",
		"deer":          "99a",
		"holding acorn": "99b",
		"male faerie":   "99a",
		"female faerie": "99b",
	},
}

var iceVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a": "380",
		"b": "381",
		"c": "382",
		"white trees, yellow sun": "380",
		"pink sky, pink river":    "381",
		"knobby trees":            "382",
	},
	"Island": map[string]string{
		"a":                      "368",
		"b":                      "369",
		"c":                      "370",
		"iceberg":                "368",
		"icy island, green land": "369",
		"trees on snowy island":  "370",
	},
	"Mountain": map[string]string{
		"a":                "376",
		"b":                "377",
		"c":                "378",
		"trees along base": "376",
		"barren tree":      "377",
		"heavy snow":       "378",
	},
	"Plains": map[string]string{
		"a": "364",
		"b": "365",
		"c": "366",
		"creepy eyes bottom left": "364",
		"branch bottom right":     "365",
		"butterfly":               "366",
	},
	"Swamp": map[string]string{
		"a": "373",
		"b": "374",
		"c": "375",
		"straight through creepy trees": "373",
		"tall grass":                    "374",
		"stump in swamp":                "375",
	},
}

var itpVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a rocks":     "65",
		"b path":      "66",
		"c dark tree": "67",
	},
	"Island": map[string]string{
		"a purple":       "56",
		"b light purple": "57",
		"c dark purple":  "58",
	},
	"Mountain": map[string]string{
		"a small tree": "62",
		"b snowy":      "63",
		"c dark red":   "64",
	},
	"Plains": map[string]string{
		"a light":        "53",
		"b little trees": "54",
		"c dark":         "55",
	},
	"Swamp": map[string]string{
		"a light":        "59",
		"b two branches": "60",
		"c dark":         "61",
	},
}

var leaVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a rocks":         "294",
		"b path":          "295",
		"brown dirt road": "295",
		"#279":            "294",
		"#280":            "295",
	},
	"Island": map[string]string{
		"a purple":            "288",
		"b light purple":      "289",
		"clear blue daylight": "289",
		"#281":                "288",
		"#282":                "289",
	},
	"Mountain": map[string]string{
		"a small tree":            "292",
		"b snowy":                 "293",
		"grey mountain / red sky": "292",
		"#283": "292",
		"#284": "293",
	},
	"Plains": map[string]string{
		"a light":        "286",
		"b little trees": "287",
		"#285":           "286",
		"#286":           "287",
	},
	"Swamp": map[string]string{
		"a light":         "290",
		"b two branches":  "291",
		"blue and foggy":  "290",
		"brown and foggy": "291",
	},
}

var pmpsVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"the golgari swarm":     "303",
		"the gruul clans":       "305",
		"the selesnya conclave": "304",
		"the simic combine":     "306",
	},
	"Island": map[string]string{
		"the azorius senate": "291",
		"the house dimir":    "294",
		"the izzet league":   "292",
		"the simic combine":  "293",
	},
	"Mountain": map[string]string{
		"the boros legion":   "302",
		"the gruul clans":    "300",
		"the izzet league":   "301",
		"the cult of rakdos": "299",
	},
	"Plains": map[string]string{
		"the azorius senate":    "289",
		"the boros legion":      "290",
		"the orzhov syndicate":  "287",
		"the selesnya conclave": "288",
	},
	"Swamp": map[string]string{
		"the house dimir":      "296",
		"the golgari swarm":    "295",
		"the orzhov syndicate": "297",
		"the cult of rakdos":   "298",
	},
}

var mirVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a": "347",
		"b": "348",
		"c": "349",
		"d": "350",
		"white flowers red pattern": "347",
		"waterfall centered":        "348",
		"waterfall left side":       "349",
		"red foliage pink flowers":  "350",
	},
	"Island": map[string]string{
		"a":                  "335",
		"b":                  "336",
		"c":                  "337",
		"d":                  "338",
		"palm tree":          "335",
		"shallow foreground": "336",
		"light fog":          "337",
		"pink sky":           "338",
	},
	"Mountain": map[string]string{
		"a":                  "343",
		"b":                  "344",
		"c":                  "345",
		"d":                  "346",
		"green hills":        "343",
		"blue sky/red dunes": "344",
		"purple hue":         "345",
		"black foreground":   "346",
	},
	"Plains": map[string]string{
		"a":             "331",
		"b":             "332",
		"c":             "333",
		"d":             "334",
		"watering hole": "331",
		"oxen":          "332",
		"zebra":         "333",
		"bird":          "334",
	},
	"Swamp": map[string]string{
		"a":             "339",
		"b":             "340",
		"c":             "341",
		"d":             "342",
		"sunset":        "339",
		"moonlight":     "340",
		"green light":   "341",
		"purple clouds": "342",
	},
}

var ogwVariants = map[string]map[string]string{
	"Wastes": map[string]string{
		"ogw183": "183",
		"ogw185": "183a",
		"ogw184": "184",
		"ogw186": "184a",
	},
}

var po2Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"a": "163",
		"b": "164",
		"c": "165",
		"waterfall background": "163",
		"creek":                "164",
		"blue sky":             "165",
	},
	"Island": map[string]string{
		"a":                     "154",
		"b":                     "155",
		"c":                     "156",
		"dragon":                "154",
		"hot air balloon":       "155",
		"single ship left side": "156",
	},
	"Mountain": map[string]string{
		"a":                    "160",
		"b":                    "161",
		"c":                    "162",
		"red mist":             "160",
		"fog - foreground":     "161",
		"archway - right side": "162",
	},
	"Plains": map[string]string{
		"a":                "151",
		"b":                "152",
		"c":                "153",
		"farmhouses":       "151",
		"palace at sunset": "152",
		"flock of birds":   "153",
	},
	"Swamp": map[string]string{
		"a": "157",
		"b": "158",
		"c": "159",
		"ash white trees background": "157",
		"animal skeleton":            "158",
		"decrepit observatory":       "159",
	},
}

var porVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a": "212",
		"b": "213",
		"c": "214",
		"d": "215",
		"thick tree center foreground":  "212",
		"leaning tree center midground": "213",
		"three dark trees foreground":   "214",
		"violet sky":                    "215",
	},
	"Island": map[string]string{
		"a":               "200",
		"b":               "201",
		"c":               "202",
		"d":               "203",
		"waterfall":       "200",
		"pointed peaks":   "201",
		"unbroken beach":  "202",
		"sun upper-right": "203",
	},
	"Mountain": map[string]string{
		"a": "208",
		"b": "209",
		"c": "210",
		"d": "211",
		"two peaks / distant trees":  "208",
		"no peaks upper-left":        "209",
		"big trees foreground":       "210",
		"three peaks / left tallest": "211",
	},
	"Plains": map[string]string{
		"a":                    "196",
		"b":                    "197",
		"c":                    "198",
		"d":                    "199",
		"many distant trees":   "196",
		"left tree cut-off":    "197",
		"full tree foreground": "198",
		"branches upper-right": "199",
	},
	"Swamp": map[string]string{
		"a":                      "204",
		"b":                      "205",
		"c":                      "206",
		"d":                      "207",
		"copper sky":             "204",
		"gray sky":               "205",
		"white tree / green sky": "206",
		"gold sun upper-right":   "207",
	},
}

var ptcVariants = map[string]map[string]string{
	"Circle of Protection: Green": map[string]string{
		"ice age sideboard bertrand lestree":     "bl14sb",
		"ice age sideboard michael locanto":      "ml14sb",
		"4th edition sideboard bertrand lestree": "bl16sb",
		"4th edition sideboard michael locanto":  "ml16sb",
	},
	"Circle of Protection: Red": map[string]string{
		"ice age sideboard bertrand lestree":     "bl15sb",
		"ice age sideboard michael locanto":      "ml15sb",
		"4th edition sideboard bertrand lestree": "bl17sb",
		"4th edition sideboard michael locanto":  "ml17sb",
	},
	"Forest": map[string]string{
		"4th edition path bertrand lestree 1996":      "bl377",
		"4th edition path preston poulter 1996":       "pp377",
		"4th edition rock bertrand lestree 1996":      "bl376",
		"4th edition rock preston poulter 1996":       "pp376",
		"4th edition dark tree bertrand lestree 1996": "bl378",
		"4th edition dark tree preston poulter 1996":  "pp378",
	},
	"Island": map[string]string{
		"4th edition purple shawn hammer regnier 1996":       "shr367",
		"4th edition purple michael locanto 1996":            "ml367",
		"4th edition light purple michael locanto 1996":      "ml368",
		"4th edition light purple shawn hammer regnier 1996": "shr368",
		"4th edition dark purple shawn hammer regnier 1996":  "shr369",
		"4th edition dark purple michael locanto 1996":       "ml369",
	},
	"Mountain": map[string]string{
		"4th edition little trees eric tam":     "et373",
		"4th edition little trees mark justice": "mj373",
		"4th edition snowy eric tam":            "et374",
		"4th edition snowy mark justice":        "mj374",
		"4th edition dark red eric tam":         "et375",
		"4th edition dark red mark justice":     "mj375",
	},
	"Plains": map[string]string{
		"4th edition light bertrand lestree 1996":            "bl364",
		"4th edition light eric tam 1996":                    "et364",
		"4th edition light mark justice 1996":                "mj364",
		"4th edition light michael locanto 1996":             "ml364",
		"4th edition light preston poulter 1996":             "pp364",
		"4th edition light shawn hammer regnier 1996":        "shr364",
		"4th edition little trees bertrand lestree 1996":     "bl365",
		"4th edition little trees eric tam 1996":             "et365",
		"4th edition little trees mark justice 1996":         "mj365",
		"4th edition little trees michael locanto 1996":      "ml365",
		"4th edition little trees preston poulter 1996":      "pp365",
		"4th edition little trees shawn hammer regnier 1996": "shr365",
		"4th edition dark bertrand lestree 1996":             "bl366",
		"4th edition dark eric tam 1996":                     "et366",
		"4th edition dark mark justice 1996":                 "mj366",
		"4th edition dark michael locanto 1996":              "ml366",
		"4th edition dark preston poulter 1996":              "pp366",
		"4th edition dark shawn hammer regnier 1996":         "shr366",
	},
	"Swamp": map[string]string{
		"4th edition light george baxter 1996":        "gb370",
		"4th edition light leon lindback 1996":        "ll370",
		"4th edition two branches leon lindback 1996": "ll371",
		"4th edition two branches george baxter 1996": "gb371",
		"4th edition dark leon lindback 1996":         "ll372",
		"4th edition dark george baxter 1996":         "gb372",
	},
}

var rinVariants = map[string]map[string]string{
	"Urza's Mine": map[string]string{
		"ri053":     "175",
		"miniera53": "176",
		"miniera56": "177",
		"miniera54": "178",
	},
	"Urza's Power Plant": map[string]string{
		"centrale57": "179",
		"centrale60": "180",
		"centrale58": "181",
		"ri054":      "182",
	},
	"Urza's Tower": map[string]string{
		"ri055":   "183",
		"torre63": "184",
		"torre62": "185",
		"torre64": "186",
	},
}

var prw2Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"ravnica weekend gruul": "B08",
		"ravnica weekend simic": "B09",
	},
	"Island": map[string]string{
		"ravnica weekend azorius": "B02",
		"ravnica weekend simic":   "B10",
	},
	"Mountain": map[string]string{
		"ravnica weekend rakdos": "B06",
		"ravnica weekend gruul":  "B07",
	},
	"Plains": map[string]string{
		"ravnica weekend azorius": "B01",
		"ravnica weekend orzhov":  "B03",
	},
	"Swamp": map[string]string{
		"ravnica weekend orzhov": "B04",
		"ravnica weekend rakdos": "B05",
	},
}

var ed3Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"a": "304",
		"b": "305",
		"c": "306",

		"a rocks":     "304",
		"b path":      "305",
		"c dark tree": "306",

		"b rocks":            "304",
		"a pathway":          "305",
		"c eyes in treehole": "306",

		"boulders foreground": "304",
		"brown dirt road":     "305",
		"dark and gloomy":     "306",
	},
	"Island": map[string]string{
		"a": "295",
		"b": "296",
		"c": "297",

		"a purple":       "295",
		"b light purple": "296",
		"c dark purple":  "297",

		"b purple island, gold horizon":   "295",
		"a green island":                  "296",
		"c purple island, orange horizon": "297",

		"golden horizon":      "295",
		"clear blue daylight": "296",
		"pink & orange dusk":  "297",
	},
	"Mountain": map[string]string{
		"a": "301",
		"b": "302",
		"c": "303",

		"a small tree": "301",
		"b snowy":      "302",
		"c dark red":   "303",

		"b gray mountains":            "301",
		"a blue mountains":            "302",
		"c brown mountain, green sky": "303",

		"grey mountain / red sky":    "301",
		"light blue sky/snow":        "302",
		"dark green clouds/blue sky": "303",
	},
	"Plains": map[string]string{
		"a": "292",
		"b": "293",
		"c": "294",

		"a light":        "292",
		"b little trees": "293",
		"c dark":         "294",

		"c cliff in background": "292",
		"b no trees on plain":   "293",
		"a trees on plain":      "294",

		"four peaks clear meadow": "292",
		"pink horizon":            "293",
		"six trees":               "294",
	},
	"Swamp": map[string]string{
		"a": "298",
		"b": "299",
		"c": "300",

		"a light":        "298",
		"b two branches": "299",
		"c dark":         "300",

		"b one branch in foreground": "298",
		"a brown, two branches":      "299",
		"c black, two branches":      "300",

		"blue and foggy":       "298",
		"brown and foggy":      "299",
		"dark grey foreground": "300",
	},
}

var sldVariants = map[string]map[string]string{
	"Serum Visions": map[string]string{
		"secret lair 29 collantes": "29",
		"secret lair 30 dxtr":      "30",
		"secret lair 31 ys":        "31",
		"secret lair 32 zuverza":   "32",
		"versione 1":               "29",
		"versione 2":               "30",
		"versione 3":               "31",
		"versione 4":               "32",
	},
}

var soiVariants = map[string]map[string]string{
	"Tamiyo's Journal": map[string]string{
		"":          "265",
		"foil":      "265†a",
		"entry 434": "265",
		"entry 546": "265†",
		"entry 653": "265†a",
		"entry 711": "265†b",
		"entry 855": "265†c",
		"entry 922": "265†d",
	},
}

var psoiVariants = map[string]map[string]string{
	"Tamiyo's Journal": map[string]string{
		"prerelease promo entry 855":              "265s",
		"shadows over innistrad prerelease promo": "265s†",
	},
}

var tmpVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"a": "347",
		"b": "348",
		"c": "349",
		"d": "350",
		"looking up to light":     "347",
		"thick roots":             "348",
		"wavy clouds":             "349",
		"branch going horizontal": "350",
	},
	"Island": map[string]string{
		"a": "335",
		"b": "336",
		"c": "337",
		"d": "338",
		"island with trailing islands, bright ocean": "335",
		"cave, crashing waves":                       "336",
		"lots of islands, bright ocean":              "338",
		"large island, purple foggy sky":             "337",
	},
	"Mountain": map[string]string{
		"a":                                  "343",
		"b":                                  "344",
		"c":                                  "345",
		"d":                                  "346",
		"spiky mountains":                    "343",
		"two spiky mountains pointing right": "344",
		"arch-like mountain":                 "345",
		"spiky mountains pointing left":      "346",
	},
	"Plains": map[string]string{
		"a": "331",
		"b": "332",
		"c": "333",
		"d": "334",
		"black and grey sky, two rocks": "331",
		"swirly grey sky, barren tree":  "332",
		"bush on the left, grey sky":    "333",
		"three tall rocks":              "334",
	},
	"Swamp": map[string]string{
		"a": "339",
		"b": "340",
		"c": "341",
		"d": "342",
		"two tree stumps, pink sky":          "339",
		"fallen tree, stump in background":   "340",
		"rock, yellow fog":                   "341",
		"tree in far background, yellow fog": "342",
	},
}

var ustVariants = map[string]map[string]string{
	"Amateur Auteur": map[string]string{
		"ravnica":        "3a",
		"innistrad":      "3b",
		"theros":         "3c",
		"zendikar":       "3d",
		"version 1":      "3a",
		"ravnica silver": "3a",
		"innistrad blue": "3b",
		"theros red":     "3c",
		"zendikar green": "3d",
	},
	"Beast in Show": map[string]string{
		"tyrranax":  "103a",
		"gnarlid":   "103b",
		"baloth":    "103c",
		"thragtusk": "103d",
		"version 1": "103a",
	},
	"Everythingamajig": map[string]string{
		"move":               "147a",
		"draw":               "147b",
		"flip":               "147c",
		"add":                "147d",
		"sacrifice":          "147e",
		"scry":               "147f",
		"version 1":          "147a",
		"move a counter..":   "147a",
		"draw a card..":      "147b",
		"flip a coin..":      "147c",
		"add one mana..":     "147d",
		"sacrifice a land..": "147e",
		"scry 2..":           "147f",
		"proliferate":        "147a",
		"draw a card":        "147b",
		"flip a coin":        "147c",
		"add one mana":       "147d",
		"sacrifice a land":   "147e",
		"scry 2":             "147f",
	},
	"Extremely Slow Zombie": map[string]string{
		"summer":    "54a",
		"fall":      "54b",
		"winter":    "54c",
		"spring":    "54d",
		"version 1": "54a",
		"autumn":    "54b",
	},
	"Garbage Elemental": map[string]string{
		"2/4":                     "82a",
		"3/1":                     "82b",
		"3/2":                     "82c",
		"3/3":                     "82d",
		"4/3":                     "82e",
		"6/5":                     "82f",
		"version 1":               "82a",
		"a 2/4":                   "82a",
		"b 3/1":                   "82b",
		"c 3/2":                   "82c",
		"d 3/3":                   "82d",
		"e 4/3":                   "82e",
		"f 6/5":                   "82f",
		"frenzy":                  "82a",
		"assembles a contraption": "82b",
		"battle cry":              "82c",
		"cascade":                 "82d",
		"unleash":                 "82e",
		"last strike":             "82f",
	},
	"Ineffable Blessing": map[string]string{
		"choose flavor":                  "113a",
		"choose artist":                  "113b",
		"choose border":                  "113c",
		"choose rarity":                  "113d",
		"choose odd or even":             "113e",
		"choose a number":                "113f",
		"version 1":                      "113a",
		"flavor text":                    "113a",
		"artist":                         "113b",
		"border":                         "113c",
		"rarity":                         "113d",
		"collector number":               "113e",
		"name":                           "113f",
		"flavorful/bland":                "113a",
		"choose an artist":               "113b",
		"white-bordered/silver-bordered": "113c",
		"choose a rarity":                "113d",
		"odd/even":                       "113e",
	},
	"Knight of the Kitchen Sink": map[string]string{
		"black borders":                            "12a",
		"even collector numbers":                   "12b",
		"loose lips":                               "12c",
		"odd collector numbers":                    "12d",
		"two-word names":                           "12e",
		"watermarks":                               "12f",
		"version 1":                                "12a",
		"protection from black borders":            "12a",
		"protection from even collector's numbers": "12b",
		"protection from loose lips":               "12c",
		"protection from odd collector's numbers":  "12d",
		"protection from two-word names":           "12e",
		"protection from watermarks":               "12f",
	},
	"Novellamental": map[string]string{
		"''my grandmother…''": "41a",
		"''this pendant…''":   "41b",
		"''the chain…''":      "41c",
		"''my heart…''":       "41d",
		"version 1":           "41a",
		"sold":                "41a",
		"pendant":             "41b",
		"chain":               "41c",
		"heart":               "41d",
	},
	"Secret Base": map[string]string{
		"order of the widget":      "165a",
		"agents of s.n.e.a.k.":     "165b",
		"league of dastardly doom": "165c",
		"goblin explosioneers":     "165d",
		"crossbreed labs":          "165e",
		"version 2":                "165b",
		"s.n.e.a.k.":               "165b",
		"john thacker art":         "165a",
		"matt gaser art":           "165b",
		"seb mckinnon art":         "165c",
		"dave allsop art":          "165d",
		"simon dominic art":        "165e",
	},
	"Sly Spy": map[string]string{
		"reveal hand":                          "67a",
		"destroy creature facing left":         "67b",
		"lose a finger":                        "67c",
		"destroy creature facing right":        "67d",
		"reveal top of library":                "67e",
		"roll six-sided die":                   "67f",
		"version 1":                            "67a",
		"reveals hand":                         "67a",
		"destroy target creature facing left":  "67b",
		"loses a finger":                       "67c",
		"destroy target creature facing right": "67d",
		"library":                                    "67e",
		"player loses life":                          "67f",
		"reveals his or her hand":                    "67a",
		"reveals the top card of his or her library": "67e",
		"roll a six-sided die":                       "67f",
	},
	"Target Minotaur": map[string]string{
		"ice":       "98a",
		"rain":      "98b",
		"fire":      "98c",
		"roots":     "98d",
		"version 1": "98a",
		"winter":    "98a",
		"fall":      "98b",
		"summer":    "98c",
		"spring":    "98d",
	},
	"Very Cryptic Command": map[string]string{
		"switch":                    "49a",
		"untap":                     "49b",
		"draw":                      "49c",
		"return":                    "49d",
		"counter":                   "49e",
		"scry":                      "49f",
		"version 2":                 "49b",
		"monochrome alternate art":  "49a",
		"return target / untap two": "49b",
		"return target/untap two":   "49b",
		"gnome":                     "49c",
		"turn over":                 "49d",
		"roll two":                  "49e",
		"return all artifacts":      "49f",
	},
}

var wc97Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"5th edition a svend geertsen 1997": "sg446",
		"5th edition b svend geertsen 1997": "sg447",
		"5th edition c svend geertsen 1997": "sg448",
		"5th edition d svend geertsen 1997": "sg449",
	},
	"Island": map[string]string{
		"5th edition a janosch kuehn 1997": "jk434",
		"5th edition b janosch kuehn 1997": "jk435",
		"5th edition c janosch kuehn 1997": "jk436",
		"5th edition d janosch kuehn 1997": "jk437",
		"5th edition a paul mccabe 1997":   "pm434",
		"5th edition b paul mccabe 1997":   "pm435",
		"5th edition c paul mccabe 1997":   "pm436",
		"5th edition d paul mccabe 1997":   "pm437",
	},
	"Mountain": map[string]string{
		"5th edition a paul mccabe 1997":   "pm442",
		"5th edition b paul mccabe 1997":   "pm443",
		"5th edition c paul mccabe 1997":   "pm444",
		"5th edition d paul mccabe 1997":   "pm445",
		"5th edition a janosch kuehn 1997": "jk442",
		"5th edition b janosch kuehn 1997": "jk443",
		"5th edition c janosch kuehn 1997": "jk444",
		"5th edition d janosch kuehn 1997": "jk445",
	},
	"Plains": map[string]string{
		"5th edition a janosch kuehn 1997": "jk430",
		"5th edition b janosch kuehn 1997": "jk431",
		"5th edition c janosch kuehn 1997": "jk432",
		"5th edition d janosch kuehn 1997": "jk433",
	},
	"Swamp": map[string]string{
		"5th edition a jakub slemr 1997": "js438",
		"5th edition b jakub slemr 1997": "js439",
		"5th edition c jakub slemr 1997": "js440",
		"5th edition d jakub slemr 1997": "js441",
	},
}

var wc98Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"tempest a brian seldon 1998": "bs347",
		"tempest b brian seldon 1998": "bs348",
		"tempest c brian seldon 1998": "bs349",
		"tempest d brian seldon 1998": "bs350",
	},
	"Island": map[string]string{
		"tempest a randy buehler 1998": "rb335",
		"tempest b randy buehler 1998": "rb336",
		"tempest c randy buehler 1998": "rb337",
		"tempest d randy buehler 1998": "rb338",
	},
	"Mountain": map[string]string{
		"tempest a ben rubin 1998": "br343",
		"tempest b ben rubin 1998": "br344",
		"tempest c ben rubin 1998": "br345",
		"tempest d ben rubin 1998": "br346",
	},
	"Plains": map[string]string{
		"tempest a brian hacker 1998": "bh331",
		"tempest b brian hacker 1998": "bh332",
		"tempest c brian hacker 1998": "bh333",
		"tempest d brian hacker 1998": "bh334",
	},
	"Firestorm": map[string]string{
		"brian seldon 1998":        "bs101",
		"sideboard ben rubin 1998": "br101sb",
	},
}

var wc99Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"tempest a matt linde 1999":       "ml347a",
		"6th edition 347 matt linde 1999": "ml347b",
	},
	"Mountain": map[string]string{
		"6th edition 346 mark le pine 1999": "mlp346a",
		"urza's saga 346 mark le pine 1999": "mlp346b",
		"tempest a mark le pine 1999":       "mlp344a",
		"tempest b mark le pine 1999":       "mlp344",
		"tempest a kai budde 1999":          "kb343",
		"tempest b kai budde 1999":          "kb344",
		"tempest c kai budde 1999":          "kb345",
	},
	"Swamp": map[string]string{
		"urza's saga 346 jakub slemr 1999": "js340",
		"tempest b jakub slemr 1999":       "js340a",
		"6th edition 340 jakub slemr 1999": "js340b",
	},
}

var wc01Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"mercadian masques 347 jan tomcani 2001": "jt347",
		"invasion 347 jan tomcani 2001":          "jt347a",
		"mercadian masques 348 jan tomcani 2001": "jt348",
		"invasion 348 jan tomcani 2001":          "jt348a",
		"mercadian masques 349 jan tomcani 2001": "jt349",
		"invasion 349 jan tomcani 2001":          "jt349a",
	},
	"Island": map[string]string{
		"7th edition 335 alex borteh 2001":        "ab335",
		"invasion 335 alex borteh 2001":           "ab335a",
		"mercadian masques 335 alex borteh 2001":  "ab335b",
		"7th edition 335 antoine ruel 2001":       "ar335",
		"invasion 335 antoine ruel 2001":          "ar335a",
		"mercadian masques 335 antoine ruel 2001": "ar335b",
		"invasion 336 antoine ruel 2001":          "ar336",
		"mercadian masques 336 antoine ruel 2001": "ar336a",
		"mercadian masques 336 alex borteh 2001":  "ab336",
		"invasion 336 alex borteh 2001":           "ab336a",
		"invasion 337 alex borteh 2001":           "ab337",
		"mercadian masques 337 alex borteh 2001":  "ab337a",
		"mercadian masques 338 alex borteh 2001":  "ab338",
		"invasion 338 alex borteh 2001":           "ab338a",
	},
	"Mountain": map[string]string{
		"invasion 343 jan tomcani 2001":              "jt343",
		"mercadian masques 343 jan tomcani 2001":     "jt343a",
		"invasion 343 tom van de logt 2001":          "tvdl343",
		"mercadian masques 343 tom van de logt 2001": "tvdl343b",
	},
	"Swamp": map[string]string{
		"invasion 339 tom van de logt 2001":          "tvdl339",
		"mercadian masques 339 tom van de logt 2001": "tvdl339a",
	},
	"Counterspell": map[string]string{
		"7th edition alex borteh 2001":        "ab67",
		"mercadian masques alex borteh 2001":  "ab69",
		"7th edition antoine ruel 2001":       "ar67",
		"mercadian masques antoine ruel 2001": "ar69",
	},
}

var wc02Variants = map[string]map[string]string{
	"Island": map[string]string{
		"odyssey 335 carlos romao 2002":     "cr335",
		"invasion 335 carlos romao 2002":    "cr335a",
		"7th edition 335 carlos romao 2002": "cr335b",
		"invasion 336 raphael levy 2002":    "rl336",
		"odyssey 336 raphael levy 2002":     "rl336a",
		"odyssey 336 sim han how 2002":      "shh336a",
		"invasion 337 carlos romao 2002":    "cr337",
		"odyssey 337 carlos romao 2002":     "cr337a",
		"odyssey 337 raphael levy 2002":     "rl337",
		"invasion 337 raphael levy 2002":    "rl337a",
	},
}

var VariantsTable = map[string]map[string]map[string]string{
	"Alliances":                     allVariants,
	"Anthologies":                   athVariants,
	"Antiquities":                   atqVariants,
	"Arena League 2001":             pal01Variants,
	"Asia Pacific Land Program":     palpVariants,
	"Battle Royale Box Set":         brbVariants,
	"Champions of Kamigawa":         chkVariants,
	"Chronicles":                    chrVariants,
	"Collectors’ Edition":           oldLandVariants,
	"Commander Anthology Volume II": cm2Variants,
	"Conspiracy: Take the Crown":    cn2Variants,
	"Deckmasters":                   dkmVariants,
	"Fallen Empires":                femVariants,
	"Fifth Edition":                 ed5Variants,
	"Fourth Edition":                ed4Variants,
	"GRN Ravnica Weekend":           prwkVariants,
	"Homelands":                     hmlVariants,
	"Ice Age":                       iceVariants,
	"Intl. Collectors’ Edition":     oldLandVariants,
	"Introductory Two-Player Set":   itpVariants,
	"Limited Edition Alpha":         leaVariants,
	"Limited Edition Beta":          oldLandVariants,
	"Magic Premiere Shop 2005":      pmpsVariants,
	"Mirage":                        mirVariants,
	"Oath of the Gatewatch":         ogwVariants,
	"Portal Second Age":             po2Variants,
	"Portal":                        porVariants,
	"Pro Tour Collector Set":        ptcVariants,
	"Rinascimento":                  rinVariants,
	"RNA Ravnica Weekend":           prw2Variants,
	"Revised Edition":               ed3Variants,
	"Secret Lair Drop":              sldVariants,
	"Shadows over Innistrad Promos": psoiVariants,
	"Shadows over Innistrad":        soiVariants,
	"Tempest":                       tmpVariants,
	"Unlimited Edition":             oldLandVariants,
	"Unstable":                      ustVariants,
	"World Championship Decks 1997": wc97Variants,
	"World Championship Decks 1998": wc98Variants,
	"World Championship Decks 1999": wc99Variants,
	"World Championship Decks 2001": wc01Variants,
	"World Championship Decks 2002": wc02Variants,
}
