package mtgjson

const (
	LayoutAftermath = "aftermath"
	LayoutFlip      = "flip"
	LayoutMeld      = "meld"
	LayoutNormal    = "normal"
	LayoutSplit     = "split"
	LayoutTransform = "transform"

	FinishNonfoil = "nonfoil"
	FinishFoil    = "foil"
	FinishEtched  = "etched"

	FrameEffectExtendedArt = "extendedart"
	FrameEffectInverted    = "inverted"
	FrameEffectShowcase    = "showcase"
	FrameEffectShattered   = "shatteredglass"

	PromoTypeBundle     = "bundle"
	PromoTypeBuyABox    = "buyabox"
	PromoTypeGameDay    = "gameday"
	PromoTypeIntroPack  = "intropack"
	PromoTypePrerelease = "prerelease"
	PromoTypePromoPack  = "promopack"
	PromoTypeRelease    = "release"
	PromoTypeBoosterfun = "boosterfun"
	PromoTypeGodzilla   = "godzillaseries"
	PromoTypeDracula    = "draculaseries"
	PromoTypePlayPromo  = "playpromo"
	PromoTypeWPN        = "wizardsplaynetwork"
	PromoTypeGilded     = "gilded"
	PromoTypeTextured   = "textured"
	PromoTypeNeonInk    = "neonink"
	PromoTypeGalaxyFoil = "galaxyfoil"
	PromoTypeSurgeFoil  = "surgefoil"
	PromoTypeGlossy     = "glossy"
	PromoTypeEmbossed   = "embossed"
	PromoTypeSerialized = "serialized"
	PromoTypeHaloFoil   = "halofoil"
	PromoTypeScroll     = "scroll"
	PromoTypePoster     = "poster"
	PromoTypeSilverFoil = "silverfoil"
	PromoTypeRippleFoil = "ripplefoil"
	PromoTypeRaisedFoil = "raisedfoil"
	PromoTypeFNM        = "fnm"

	PromoTypeStoreChampionship = "storechampionship"

	PromoTypeStepAndCompleat = "stepandcompleat"
	PromoTypeOilSlick        = "oilslick"
	PromoTypeConcept         = "concept"
	PromoTypeConfettiFoil    = "confettifoil"
	PromoTypeDoubleRainbow   = "doublerainbow"
	PromoTypeRainbowFoil     = "rainbowfoil"
	PromoTypeFractureFoil    = "fracturefoil"
	PromoTypeManaFoil        = "manafoil"

	PromoTypeThickDisplay  = "thick"
	PromoTypeJudgeGift     = "judgegift"
	PromoTypeArenaLeague   = "arenaleague"
	PromoTypePlayerRewards = "playerrewards"
	PromoTypeStarterDeck   = "starterdeck"
	PromoTypeDraftWeekend  = "draftweekend"
	PromoTypeInvisibleInk  = "invisibleink"

	PromoTypeSChineseAltArt = "schinesealtart"
	PromoTypeDoubleExposure = "doubleexposure"

	BorderColorBorderless = "borderless"
	BorderColorGold       = "gold"

	LanguageJapanese  = "Japanese"
	LanguagePhyrexian = "Phyrexian"

	SuffixSpecial = "★"
	SuffixVariant = "†"
	SuffixPhiLow  = "φ"
)
