package magic

// promoTypeLabels spells a promo type the way a reader knows it. MTGJSON
// writes them as single lower-case words, so unlike the games that keep a
// storefront's own wording there is nothing to recover them from: "Booster
// Fun" cannot be got back out of "boosterfun" by any rule, and title-casing
// gives "Boosterfun".
//
// A type missing from this list still reads as something - the backend falls
// back on title-casing the token - so a promo type MTGJSON adds tomorrow
// shows up unlabelled rather than not at all.
var promoTypeLabels = map[string]string{
	"alchemy":             "Alchemy",
	"arenaleague":         "Arena League",
	"beginnerbox":         "Beginner Box",
	"boosterfun":          "Booster Fun",
	"boxtopper":           "Box Topper",
	"brawldeck":           "Brawl Deck",
	"bringafriend":        "Bring-a-Friend",
	"bundle":              "Bundle",
	"buyabox":             "Buy-a-Box",
	"chocobotrackfoil":    "Chocobo Track Foil",
	"commanderparty":      "Commander Party",
	"commanderpromo":      "Commander Promo",
	"concept":             "Concept art",
	"confettifoil":        "Confetti foil",
	"convention":          "Convention",
	"cosmicfoil":          "Cosmic Foil",
	"datestamped":         "Date Stamped",
	"dazzlefoil":          "Dazzle Foil",
	"dossier":             "Dossier",
	"doubleexposure":      "Double Exposure",
	"doublerainbow":       "Double Rainbow",
	"draculaseries":       "Dracula series",
	"draftweekend":        "Draft Weekend",
	"dragonscalefoil":     "Dragon Scale Foil",
	"duels":               "Duels of the Planeswalkers",
	"embossed":            "Embossed foil",
	"emeraldblue":         "Emerald Blue",
	"emeraldcyan":         "Emerald Cyan",
	"emeraldgreen":        "Emerald Green",
	"emeraldpurple":       "Emerald Purple",
	"emeraldred":          "Emerald Red",
	"emeraldwhite":        "Emerald White",
	"emeraldyellow":       "Emerald Yellow",
	"event":               "Event",
	"facetfoil":           "Facet Foil",
	"ffi":                 "FF I",
	"ffii":                "FF II",
	"ffiii":               "FF III",
	"ffiv":                "FF IV",
	"ffix":                "FF IX",
	"ffv":                 "FF V",
	"ffvi":                "FF VI",
	"ffvii":               "FF VII",
	"ffviii":              "FF VIII",
	"ffx":                 "FF X",
	"ffxi":                "FF XI",
	"ffxii":               "FF XII",
	"ffxiii":              "FF XIII",
	"ffxiv":               "FF XIV",
	"ffxv":                "FF XV",
	"ffxvi":               "FF XVI",
	"firstplacefoil":      "First Place Foil",
	"fnm":                 "Friday Night Magic",
	"fracturefoil":        "Fracture foil",
	"galaxyfoil":          "Galaxy foil",
	"gameday":             "Game Day",
	"giftbox":             "Gift Box",
	"gilded":              "Gilded foil",
	"glossy":              "Glossy",
	"godzillaseries":      "Godzilla series",
	"halofoil":            "Halo foil",
	"headliner":           "Headliner",
	"imagine":             "Imagine",
	"instore":             "In-Store",
	"intropack":           "Intro Pack",
	"invisibleink":        "Invisible Ink foil",
	"japanshowcase":       "Japan Showcase",
	"jpwalker":            "Japanese Planeswalker",
	"judgegift":           "Judge Gift",
	"league":              "League",
	"magnified":           "Magnified",
	"manafoil":            "Mana foil",
	"mediainsert":         "Media Insert",
	"metal":               "Metal",
	"moonlitland":         "Moonlit Land",
	"neonink":             "Neon Ink",
	"neoninkblue":         "Neon Ink Blue",
	"neoninkgreen":        "Neon Ink Green",
	"neoninkmulticolor":   "Neon Ink Multicolor",
	"neoninkpink":         "Neon Ink Pink",
	"neoninkpurple":       "Neon Ink Purple",
	"neoninkrainbow":      "Neon Ink Rainbow",
	"neoninkred":          "Neon Ink Red",
	"neoninkthreecolor":   "Neon Ink Three-Color",
	"neoninkyellow":       "Neon Ink Yellow",
	"oilslick":            "Oil Slick foil",
	"openhouse":           "Open House",
	"planeswalkerstamped": "Planeswalker Stamped",
	"playerrewards":       "Player Rewards",
	"playpromo":           "Play Promo",
	"playtest":            "Playtest",
	"portrait":            "Portrait",
	"poster":              "Poster art",
	"premiereshop":        "Premiere Shop",
	"prerelease":          "Prerelease",
	"promopack":           "Promo Pack",
	"rainbowfoil":         "Rainbow foil",
	"raisedfoil":          "Raised foil",
	"ravnicacity":         "Ravnica City",
	"release":             "Release / launch",
	"resale":              "Resale",
	"ripplefoil":          "Ripple foil",
	"ruderiders":          "Rude Riders",
	"schinesealtart":      "S-Chinese alt art",
	"scroll":              "Scroll",
	"serialized":          "Serialized",
	"setextension":        "Set Extension",
	"setpromo":            "Set Promo",
	"silverfoil":          "Silver foil",
	"silverscroll":        "Silver Scroll",
	"singularityfoil":     "Singularity Foil",
	"sldbonus":            "Secret Lair Bonus",
	"sourcematerial":      "Source Material",
	"stamped":             "Stamped",
	"standardshowdown":    "Standard Showdown",
	"startercollection":   "Starter Collection",
	"starterdeck":         "Starter Deck",
	"stepandcompleat":     "Step-and-Compleat",
	"storechampionship":   "Store Championship",
	"surgefoil":           "Surge foil",
	"textured":            "Textured foil",
	"themepack":           "Theme Pack",
	"thick":               "Thick display",
	"tourney":             "Tournament",
	"universesbeyond":     "Universes Beyond",
	"upsidedown":          "Upside Down",
	"upsidedownback":      "Upside Down Back",
	"vault":               "Vault",
	"wizardsplaynetwork":  "WPN / Gateway",
}
