package mtgdb

var allVariants = map[string]map[string]string{
	"Aesthir Glider": map[string]string{
		"Clouds":        "116a",
		"Moon":          "116b",
		"AesthirGlider": "116a",
		"AZ002":         "116b",
		"Facing Left":   "116a",
		"Facing Right":  "116b",
	},
	"Agent of Stromgald": map[string]string{
		"Arms Crossed":        "64a",
		"Holding Staff":       "64b",
		"AgentOfStromgald":    "64a",
		"AZ003":               "64b",
		"Woman Holding Staff": "64b",
	},
	"Arcane Denial": map[string]string{
		"1":            "22a",
		"2":            "22b",
		"Axe":          "22a",
		"Sword":        "22b",
		"ArcaneDenial": "22a",
		"AZ005":        "22b",
	},
	"Astrolabe": map[string]string{
		"Globe/Windows":  "118a",
		"Map Background": "118b",
		"Astrolabe":      "118a",
		"AZ009":          "118b",
		"Full Room View": "118a",
		"Close-Up View":  "118b",
	},
	"Awesome Presence": map[string]string{
		"Arms Spread":        "23a",
		"Man Being Chased":   "23b",
		"AwsomePresence":     "23a",
		"AZ011":              "23b",
		"Open Arms":          "23a",
		"Man Being Attacked": "23b",
	},
	"Balduvian War-Makers": map[string]string{
		"Landscape in Background": "66a",
		"Green Background":        "66b",
		"BalduvianWar":            "66a",
		"AZ016":                   "66b",
		"Two Clubs, Side View":    "66a",
		"Sky Background":          "66a",
	},
	"Benthic Explorers": map[string]string{
		"Sitting on Rocks": "24a",
		"Swimming":         "24b",
		"BenthicExplorers": "24a",
		"AZ018":            "24b",
		"Facing Forward":   "24a",
		"Facing Right":     "24b",
	},
	"Bestial Fury": map[string]string{
		"Facing Front": "67a",
		"Facing Left":  "67b",
		"BestialFury":  "67a",
		"AZ020":        "67b",
	},
	"Carrier Pigeons": map[string]string{
		"Hand":            "1a",
		"Trees":           "1b",
		"CarrierPigeons":  "1a",
		"AZ024":           "1b",
		"Man With Pigeon": "1a",
		"Three Pigeons":   "1b",
	},
	"Casting of Bones": map[string]string{
		"Finger Ornament": "44a",
		"Hooded Figure":   "44b",
		"CastingOfBones":  "44a",
		"AZ027":           "44b",
		"Hand":            "44a",
	},
	"Deadly Insect": map[string]string{
		"Bird":         "86a",
		"Elf":          "86b",
		"Hummingbird":  "86a",
		"Red Robe":     "86b",
		"DeadlyInsect": "86a",
		"AZ030":        "86b",
	},
	"Elvish Ranger": map[string]string{
		"Female":       "88a",
		"Male":         "88b",
		"ElvishRanger": "88a",
		"AZ037":        "88b",
	},
	"Enslaved Scout": map[string]string{
		"Crouching":     "71a",
		"Horses":        "71b",
		"EnslavedScout": "71a",
		"AZ041":         "71b",
	},
	"Errand of Duty": map[string]string{
		"Page Holding Sword": "2a",
		"With Horse":         "2b",
		"ErrandOfDuty":       "2a",
		"AZ043":              "2b",
		"Bright Red Suit":    "2a",
		"Horse":              "2b",
	},
	"False Demise": map[string]string{
		"Rocks":       "27a",
		"Underwater":  "27b",
		"FalseDemise": "27a",
		"AZ046":       "27b",
		"Cave-In":     "27a",
	},
	"Feast or Famine": map[string]string{
		"Falling into Pit": "49a",
		"Knife":            "49b",
		"FeastOrFamine":    "49a",
		"AZ049":            "49b",
		"Falling Into Pit": "49a",
	},
	"Fevered Strength": map[string]string{
		"Lifting Rock":     "50a",
		"Foaming Mouth":    "50b",
		"FeveredStrength":  "50a",
		"AZ052":            "50b",
		"Chains":           "50a",
		"Foaming at Mouth": "50b",
	},
	"Foresight": map[string]string{
		"Mermaid With Shiny Shell": "29a",
		"White Dress":              "29b",
		"Foresight":                "29a",
		"AZ056":                    "29b",
		"Facing Front":             "29a",
		"Facing Right":             "29b",
	},
	"Fyndhorn Druid": map[string]string{
		"Facing Left":   "90a",
		"Facing Right":  "90b",
		"FyndhornDriud": "90a",
		"AZ058":         "90b",
		"Facing Front":  "90b",
	},
	"Gift of the Woods": map[string]string{
		"Female":         "92a",
		"Male":           "92b",
		"giftOfTheWoods": "92a",
		"AZ061":          "92b",
	},
	"Gorilla Berserkers": map[string]string{
		"Closed Mouth":      "93a",
		"Attacking":         "93b",
		"Peaceful":          "93a",
		"Roaring":           "93b",
		"GorillaBerserkers": "93a",
		"AZ062":             "93b",
		"Holding Spear":     "93b",
	},
	"Gorilla Chieftain": map[string]string{
		"2 Gorillas":       "94a",
		"4 Gorillas":       "94b",
		"GorillaChieftain": "94a",
		"AZ065":            "94b",
		"Two Gorillas":     "94a",
		"Four Gorillas":    "94b",
	},
	"Gorilla Shaman": map[string]string{
		"1":             "72a",
		"2":             "72b",
		"Facing Left":   "72a",
		"Facing Right":  "72b",
		"GorillaShaman": "72a",
		"AZ067":         "72b",
		"Holding Baby":  "72a",
		"Skulls":        "72b",
	},
	"Gorilla War Cry": map[string]string{
		"Colorful Headdress": "73a",
		"Red Club":           "73b",
		"GOrillaWarCry":      "73a",
		"AZ069":              "73b",
		"Leaning Left":       "73a",
		"Leaning Right":      "73b",
	},
	"Guerrilla Tactics": map[string]string{
		"Tripwire":         "74a",
		"Cliff":            "74b",
		"AZ070":            "74a",
		"GuerrillaTactics": "74b",
		"Kneeling Knight":  "74a",
		"Cliffside":        "74b",
	},
	"Insidious Bookworms": map[string]string{
		"Bookshelf":          "51a",
		"Single Book":        "51b",
		"InsidiousBookworms": "51a",
		"AZ077":              "51b",
	},
	"Kjeldoran Escort": map[string]string{
		"Green Blanketed Dog": "7a",
		"Red Blanketed Dog":   "7b",
		"KjeldoranEscort":     "7a",
		"AZ084":               "7b",
		"Facing Front":        "7a",
		"Facing Left":         "7b",
	},
	"Kjeldoran Pride": map[string]string{
		"Facing Left":     "9a",
		"Facing Right":    "9b",
		"KjeldoranPride":  "9a",
		"AZ087":           "9b",
		"Kjeldoran Pride": "9a",
		"Eagle":           "9b",
		"Bear":            "9a",
	},
	"Lat-Nam's Legacy": map[string]string{
		"Scroll":    "30a",
		"Bookshelf": "30b",
		"Open Book": "30b",
		"Book":      "30b",
	},
	"Lim-Dûl's High Guard": map[string]string{
		"LimDulHighGuard": "55a",
		"AZ095":           "55b",
	},
	"Lim-Dul's High Guard": map[string]string{
		"Red Armor":    "55a",
		"Two Swords":   "55b",
		"Yellow Armor": "55b",
	},
	"Martyrdom": map[string]string{
		"Alive":     "10a",
		"Dead":      "10b",
		"Martyrdom": "10a",
		"AZ102":     "10b",
		"Knight standing, holding sword": "10a",
		"Knight wounded on ground":       "10b",
	},
	"Noble Steeds": map[string]string{
		"Trees in Forefront":  "11a",
		"Two Steeds Close Up": "11b",
		"NobleSteeds":         "11a",
		"AZ110":               "11b",
		"Trees":               "11a",
		"Close-Up View":       "11b",
	},
	"Phantasmal Fiend": map[string]string{
		"Close-Up":        "57a",
		"Doorway":         "57b",
		"PhantasmalFiend": "57a",
		"AZ113":           "57b",
		"Close-Up View":   "57a",
	},
	"Phyrexian Boon": map[string]string{
		"Female":        "58a",
		"Male":          "58b",
		"PhyrexianBoon": "58a",
		"AZ118":         "58b",
	},
	"Phyrexian War Beast": map[string]string{
		"Propeller Left":    "127a",
		"Propeller Right":   "127b",
		"PhyrexianWarBeast": "127a",
		"AZ121":             "127b",
	},
	"Reinforcements": map[string]string{
		"Not Fighting Orc": "12a",
		"Fighting Orc":     "12b",
		"Reinforcements":   "12a",
		"AZ127":            "12b",
	},
	"Reprisal": map[string]string{
		"Red Dragon":    "13a",
		"Green Shark":   "13b",
		"AZ129":         "13a",
		"Reprisal":      "13b",
		"Red Monster":   "13a",
		"Green Monster": "13b",
	},
	"Royal Herbalist": map[string]string{
		"Female":         "15a",
		"Male":           "15b",
		"RoyalHerbalist": "15a",
		"AZ133":          "15b",
	},
	"Soldevi Adnate": map[string]string{
		"Female":   "60a",
		"Male":     "60b",
		"Two Eyes": "60a",
		"One Eye":  "60b",
	},
	"Soldevi Heretic": map[string]string{
		"Blue Robe":      "33a",
		"Red Robe":       "33b",
		"SoldeviHeretic": "33a",
		"AZ146":          "33b",
	},
	"Soldevi Sage": map[string]string{
		"2 Candles":         "34a",
		"Old Woman Sitting": "34b",
		"SoldeviSage":       "34a",
		"AZ149":             "34b",
		"Male":              "34a",
		"Female":            "34b",
	},
	"Soldevi Sentry": map[string]string{
		"Close Up":               "132a",
		"Silver Sentry Fighting": "132b",
		"SoldeviSentry":          "132a",
		"AZ150":                  "132b",
		"Close-Up View":          "132a",
		"Attacking":              "132b",
	},
	"Soldevi Steam Beast": map[string]string{
		"Beast in Mountains": "133a",
		"Purple Sun":         "133b",
		"SoldeviSteamBeast":  "133a",
		"AZ152":              "133b",
		"Mountain":           "133a",
		"Pink Sun":           "133b",
	},
	"Stench of Decay": map[string]string{
		"Hand Covering Nose": "61a",
		"Red Flower":         "61b",
		"StenchOfDecay":      "61a",
		"AZ157":              "61b",
		"Covering Face":      "61a",
		"Flower":             "61b",
		"Holding Flower":     "61b",
	},
	"Storm Crow": map[string]string{
		"Flying Left":  "36a",
		"Flying Right": "36b",
		"StormCrow":    "36a",
		"AZ161":        "36b",
	},
	"Storm Shaman": map[string]string{
		"Female":      "81a",
		"Male":        "81b",
		"StormShaman": "81a",
		"AZ163":       "81b",
	},
	"Swamp Mosquito": map[string]string{
		"Black Trees":   "63a",
		"Brown Trees":   "63b",
		"SwampMosquito": "63a",
		"AZ169":         "63b",
		"Fallen Tree":   "63a",
	},
	"Taste of Paradise": map[string]string{
		"Woman Alone":              "100a",
		"Two People":               "100b",
		"TasteOfParadise":          "100a",
		"AZ172":                    "100b",
		"One Person Holding Fruit": "100a",
		"Man and Woman":            "100b",
	},
	"Undergrowth": map[string]string{
		"Fox and Badger": "102a",
		"Holding Axe":    "102b",
		"Undergrowth":    "102a",
		"AZ178":          "102b",
		"Fox":            "102a",
		"Elf":            "102b",
	},
	"Varchild's Crusader": map[string]string{
		"Black Horse and Hollow Log": "82a",
		"Brown Horse and Castle":     "82b",
		"VarchildCrusader":           "82a",
		"AZ182":                      "82b",
		"Forest":                     "82a",
		"Castle":                     "82b",
	},
	"Veteran's Voice": map[string]string{
		"Over the Shoulder":     "84a",
		"Side-by-Side":          "84b",
		"VeteranVoice":          "84a",
		"AZ185":                 "84b",
		"Men Standing Together": "84a",
		"Men Standing Apart":    "84b",
	},
	"Viscerid Armor": map[string]string{
		"Crashing Wave":        "41a",
		"Humans in Foreground": "41b",
		"VisceridArmor":        "41a",
		"AZ187":                "41b",
		"Alone":                "41a",
		"Attacking Two Men":    "41b",
	},
	"Whip Vine": map[string]string{
		"3 Vines":       "103a",
		"Ensnared Bird": "103b",
		"WhipVine":      "103a",
		"AZ192":         "103b",
		"No Bird":       "103a",
		"Bird":          "103b",
	},
	"Wild Aesthir": map[string]string{
		"Blue Mountains":    "21a",
		"Green Background":  "21b",
		"WildAethir":        "21a",
		"AZ195":             "21b",
		"Wings Thrown Back": "21b",
	},
	"Yavimaya Ancients": map[string]string{
		"Rearing Horse":    "104a",
		"Trees":            "104b",
		"YavimayaAncients": "104a",
		"AZ197":            "104b",
		"Horse":            "104a",
		"No Horse":         "104b",
	},
}

var athVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A":        "84",
		"B":        "85",
		"Arena":    "84",
		"Portal 2": "85",
	},
	"Mountain": map[string]string{
		"A":              "82",
		"B":              "83",
		"Arabian Nights": "82",
		"Mirage":         "83",
	},
	"Plains": map[string]string{
		"A":      "78",
		"B":      "79",
		"Mirage": "78",
		"Portal": "79",
	},
	"Swamp": map[string]string{
		"A":       "80",
		"B":       "81",
		"Ice Age": "80",
		"Tempest": "81",
	},
}

var atqVariants = map[string]map[string]string{
	"Mishra's Factory": map[string]string{
		"AQ044":                    "80a",
		"AQ045":                    "80b",
		"atq-80c-mishra-s-factory": "80c",
		"AQ046":                    "80d",

		"b Spring": "80a",
		"c Summer": "80b",
		"a Fall":   "80c",
		"d Winter": "80d",

		"Spring": "80a",
		"Summer": "80b",
		"Autumn": "80c",
		"Winter": "80d",

		"Summer Green":  "80b",
		"Autumn Orange": "80c",
		"Winter Snow":   "80d",

		"Fall": "80c",
	},
	"Strip Mine": map[string]string{
		"atq-82a-strip-mine": "82a",
		"atq-82b-strip-mine": "82b",
		"atq-82c-strip-mine": "82c",
		"AQ070":              "82d",

		"No Sky, No Tower":    "82a",
		"Sky, Even Terraces":  "82b",
		"No Sky wth Tower":    "82c",
		"Sky Uneven Terraces": "82d",

		"No Sky, No Cave/Tower": "82a",
		"Cave":                  "82b",
		"Tower":                 "82c",
		"Sky, No Cave or Tower": "82d",

		"No Horizon":    "82a",
		"Even Horizon":  "82b",
		"Small Tower":   "82c",
		"Uneven Stripe": "82d",

		"No Sky, Tower":        "82c",
		"Sky, Uneven Terraces": "82d",

		"c No Horizon": "82a",
		"a Even":       "82b",
		"d Tower":      "82c",
		"b Uneven":     "82d",
	},
	"Urza's Mine": map[string]string{
		"AQ084": "83a",
		"AQ085": "83b",
		"AQ083": "83c",
		"AQ086": "83d",

		"Pulley":           "83a",
		"Mouth":            "83b",
		"Submerged Sphere": "83c",
		"Tower":            "83d",

		"Mine Face": "83b",
		"Sphere":    "83c",
		"Ladder":    "83d",

		"Clawed Sphere": "83c",

		"a Bathyscape": "83c",
		"b Mouth":      "83b",
		"c Pulley":     "83a",
		"d Tower":      "83d",
	},
	"Urza's Power Plant": map[string]string{
		"AQ089": "84a",
		"AQ090": "84b",
		"AQ088": "84c",
		"AQ091": "84d",

		"Sphere":  "84a",
		"Columns": "84b",
		"Bug":     "84c",
		"Pot":     "84d",

		"Sphere with Tubes": "84a",
		"Red Columns":       "84b",
		"Rock In Pan":       "84d",

		"Rock in Pot": "84d",

		"c Sphere": "84a",
		"b Pillar": "84b",
		"a Bug":    "84c",
		"d Vat":    "84d",
	},
	"Urza's Tower": map[string]string{
		"AQ092": "85a",
		"AQ093": "85b",
		"AQ094": "85c",
		"AQ095": "85d",

		"Red Leaves":            "85a",
		"Sunset with Shoreline": "85b",
		"Plains":                "85c",
		"Mountains":             "85d",

		"Forest": "85a",
		"Shore":  "85b",

		"a Forest":   "85a",
		"d Seashore": "85b",
		"c Plains":   "85c",
		"b Mountain": "85d",
	},
}

var pal01Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"Arena 2001 Foil":        "1",
		"Arena 2002 Foil":        "11",
		"Arena IA":               "1",
		"Arena Beta":             "11",
		"Arena 2001 Ice Age":     "1",
		"Arena 2002 Beta":        "11",
		"Ice Age art Arena 2001": "1",
		"Beta Art Arena 2001":    "11",
		"Arena 2001":             "1",
		"Arena 2002":             "11",
	},
}

var palpVariants = map[string]map[string]string{
	"Swamp": map[string]string{
		"Ron Spears, Fireballs":               "10",
		"Ron Spears, Zombie":                  "15",
		"APAC b Taiwan":                       "10",
		"APAC c Australia":                    "15",
		"Indonesia":                           "15",
		"Ron Spears, Small Person":            "15",
		"APAC Set Red Pack Graveyard":         "10",
		"APAC Set Clear Pack Person in Swamp": "15",
	},
}

var brbVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A": "103",
		"B": "104",
		"C": "109",
		"D": "107",
		"E": "108",
		"F": "101",
		"G": "102",
		"H": "105",
		"I": "106",
		"1": "101",
		"2": "102",
		"3": "103",
		"4": "104",
		"5": "105",
		"6": "106",
		"7": "107",
		"8": "108",
		"9": "109",
	},
	"Island": map[string]string{
		"A": "112",
		"B": "114",
		"C": "113",
		"D": "111",
		"E": "110",
		"1": "110",
		"2": "111",
		"3": "112",
		"4": "114",
		"5": "113",
	},
	"Mountain": map[string]string{
		"A": "118",
		"B": "119",
		"C": "115",
		"D": "116",
		"E": "117",
		"F": "120",
		"G": "121",
		"H": "122",
		"I": "123",
		"1": "115",
		"2": "116",
		"3": "117",
		"4": "118",
		"5": "119",
		"6": "120",
		"7": "121",
		"8": "122",
		"9": "123",
	},
	"Plains": map[string]string{
		"A": "127",
		"B": "128",
		"C": "130",
		"D": "131",
		"E": "132",
		"F": "125",
		"G": "124",
		"H": "126",
		"I": "129",
		"1": "124",
		"2": "125",
		"3": "126",
		"4": "127",
		"5": "128",
		"6": "129",
		"7": "130",
		"8": "131",
		"9": "132",
	},
	"Swamp": map[string]string{
		"A": "133",
		"B": "134",
		"C": "136",
		"D": "135",
		"1": "133",
		"2": "134",
		"3": "135",
		"4": "136",
	},
}

var chkVariants = map[string]map[string]string{
	"Brothers Yamazaki": map[string]string{
		"Facing Left":  "160a",
		"Facing Right": "160b",
		"A":            "160a",
		"B":            "160b",
	},
}

var oldLandVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A": "300",
		"B": "301",
		"C": "302",

		"A Rocks":     "300",
		"B Path":      "301",
		"C Dark Tree": "302",

		"B - Not Tournament Legal": "300",
		"A - Not Tournament Legal": "301",
		"C - Not Tournament Legal": "302",

		"B Rocks":            "300",
		"A Pathway":          "301",
		"C Eyes in treehole": "302",

		"Boulders Foreground": "300",
		"Brown Dirt Road":     "301",
		"Dark and Gloomy":     "302",
	},
	"Island": map[string]string{
		"A": "291",
		"B": "292",
		"C": "293",

		"A Purple":       "291",
		"B Light Purple": "292",
		"C Dark Purple":  "293",

		"B - Not Tournament Legal": "291",
		"A - Not Tournament Legal": "292",
		"C - Not Tournament Legal": "293",

		"B Purple island, gold horizon":   "291",
		"A Green island":                  "292",
		"C Purple island, orange horizon": "293",

		"Golden Horizon":      "291",
		"Clear Blue Daylight": "292",
		"Pink & Orange Dusk":  "293",
	},
	"Mountain": map[string]string{
		"A": "297",
		"B": "298",
		"C": "299",

		"A Small Tree": "297",
		"B Snowy":      "298",
		"C Dark Red":   "299",

		"B - Not Tournament Legal": "297",
		"A - Not Tournament Legal": "298",
		"C - Not Tournament Legal": "299",

		"B Gray mountains":            "297",
		"A Blue mountains":            "298",
		"C Brown mountain, green sky": "299",

		"Grey Mountain / Red Sky":    "297",
		"Light Blue Sky/Snow":        "298",
		"Dark Green Clouds/Blue Sky": "299",
	},
	"Plains": map[string]string{
		"B": "288",
		"A": "289",
		"C": "290",

		"A Light":        "288",
		"B Little Trees": "289",
		"C Dark":         "290",

		"B - Not Tournament Legal": "288",
		"A - Not Tournament Legal": "289",
		"C - Not Tournament Legal": "290",

		"B No trees on plain":   "288",
		"A Trees on plain":      "289",
		"C Cliff in background": "290",

		"Six Trees":               "288",
		"Four Peaks Clear Meadow": "289",
		"Pink Horizon":            "290",
	},
	"Swamp": map[string]string{
		"A": "294",
		"B": "295",
		"C": "296",

		"5219":   "294",
		"UN248":  "295",
		"Swamp2": "296",

		"A Light":        "294",
		"B Two Branches": "295",
		"C Dark":         "296",

		"B - Not Tournament Legal": "294",
		"A - Not Tournament Legal": "295",
		"C - Not Tournament Legal": "296",

		"B One branch in foreground": "294",
		"A Brown, two branches":      "295",
		"C Black, two branches":      "296",

		"Blue and Foggy":       "294",
		"Brown and Foggy":      "295",
		"Dark Grey Foreground": "296",
	},
}

var cm2Variants = map[string]map[string]string{
	"Golgari Signet": map[string]string{
		"/it/info-prodotto/284/1214/259602/commander-anthology-2018-golgari-signet": "191",
		"/it/info-prodotto/284/1214/259603/commander-anthology-2018-golgari-signet": "192",
	},
	"Simic Signet": map[string]string{
		"/it/info-prodotto/284/1214/259716/commander-anthology-2018-simic-signet": "215",
		"/it/info-prodotto/284/1214/259717/commander-anthology-2018-simic-signet": "216",
	},
	"Solemn Simulacrum": map[string]string{
		"/it/info-prodotto/284/1214/259722/commander-anthology-2018-solemn-simulacrum": "218",
		"/it/info-prodotto/284/1214/259723/commander-anthology-2018-solemn-simulacrum": "219",
	},
	"Temple of the False God": map[string]string{
		"/it/info-prodotto/284/1214/259753/commander-anthology-2018-temple-of-the-false-god": "271",
		"/it/info-prodotto/284/1214/259754/commander-anthology-2018-temple-of-the-false-god": "272",
	},
}

var chrVariants = map[string]map[string]string{
	"Urza's Mine": map[string]string{
		"CH094": "114a",
		"CH095": "114b",
		"CH096": "114c",
		"CH097": "114d",

		"Mine Face": "114a",
		"Sphere":    "114b",
		"Pulley":    "114c",
		"Tower":     "114d",

		"Mouth":            "114a",
		"Submerged Sphere": "114b",
		"Ladder":           "114d",

		"Clawed Sphere": "114b",
		"Watchtower":    "114d",

		"b Mouth":      "114a",
		"a Bathyscape": "114b",
		"c Pully":      "114c",
		"d Tower":      "114d",
	},
	"Urza's Power Plant": map[string]string{
		"CH098": "115a",
		"CH099": "115b",
		"CH101": "115c",
		"CH100": "115d",

		"Pot":     "115a",
		"Columns": "115b",
		"Sphere":  "115c",
		"Bug":     "115d",

		"Rock In Pan":       "115a",
		"Red Columns":       "115b",
		"Sphere with Tubes": "115c",

		"Rock in Pot": "115a",

		"d Vat":    "115a",
		"b Pillar": "115b",
		"c Sphere": "115c",
		"a Bug":    "115d",
	},
	"Urza's Tower": map[string]string{
		"CH105": "116a",
		"CH103": "116b",
		"CH104": "116c",
		"CH102": "116d",

		"Forest":     "116a",
		"Plains":     "116b",
		"Mountains":  "116c",
		"Red Leaves": "116d",

		"Sunset with Shoreline": "116a",
		"Shore":                 "116d",

		"a Forest":   "116a",
		"c Plains":   "116b",
		"b Mountain": "116c",
		"d Seashore": "116d",
	},
}

var cn2Variants = map[string]map[string]string{
	"Kaya, Ghost Assassin": map[string]string{
		"CN2075":               "75",
		"kaya_ghost_assassin2": "222",
	},
}

var dkmVariants = map[string]map[string]string{
	"Yavimaya Ancients": map[string]string{
		"Rearing Horse": "31a",
		"Trees":         "31b",
	},
}

var femVariants = map[string]map[string]string{
	"Armor Thrull": map[string]string{
		"FE001": "33a",
		"FE002": "33b",
		"FE003": "33c",
		"FE004": "33d",
	},
	"Basal Thrull": map[string]string{
		"FE005": "34a",
		"FE006": "34b",
		"FE007": "34c",
		"FE008": "34d",
	},
	"Brassclaw Orcs": map[string]string{
		"FE100":                      "49a",
		"FE101":                      "49b",
		"FE102":                      "49c",
		"FE103":                      "49d",
		"Rob Alexander, Spear":       "49a",
		"Rob Alexander, No Spear":    "49c",
		"Rob Alexander, Gloved Fist": "49c",
	},
	"Combat Medic": map[string]string{
		"FE133": "1a",
		"FE134": "1b",
		"FE135": "1c",
		"FE136": "1d",
	},
	"Dwarven Soldier": map[string]string{
		"FE107":           "53a",
		"FE108":           "53b",
		"FE109":           "53c",
		"Douglas Schuler": "53c",
	},
	"Elven Fortress": map[string]string{
		"FE067": "65a",
		"FE068": "65b",
		"FE069": "65c",
		"FE070": "65d",
	},
	"Elvish Hunter": map[string]string{
		"FE072": "67a",
		"FE073": "67b",
		"FE074": "67c",
	},
	"Elvish Scout": map[string]string{
		"FE075": "68a",
		"FE076": "68b",
		"FE077": "68c",
	},
	"Farrel's Zealot": map[string]string{
		"FE139": "3a",
		"FE140": "3b",
		"FE141": "3c",
	},
	"Goblin Chirurgeon": map[string]string{
		"FE110": "54a",
		"FE111": "54b",
		"FE112": "54c",
	},
	"Goblin Grenade": map[string]string{
		"1":     "56b",
		"2":     "56c",
		"FE114": "56a",
		"FE115": "56b",
		"FE116": "56c",
	},
	"Goblin War Drums": map[string]string{
		"FE119": "58a",
		"FE120": "58b",
		"FE121": "58c",
		"FE122": "58d",
	},
	"High Tide": map[string]string{
		"FE035": "18a",
		"FE036": "18b",
		"FE037": "18c",
	},
	"Homarid": map[string]string{
		"FE038": "19a",
		"FE039": "19b",
		"FE040": "19c",
		"FE041": "19d",
		"18c":   "19c",
	},
	"Homarid Warrior": map[string]string{
		"FE044": "22a",
		"FE045": "22b",
		"FE046": "22c",
	},
	"Hymn to Tourach": map[string]string{
		"4":     "38a",
		"1":     "38b",
		"2":     "38c",
		"3":     "38d",
		"FE012": "38a",
		"FE013": "38b",
		"FE014": "38c",
		"FE015": "38d",
	},
	"Icatian Infantry": map[string]string{
		"FE144": "7a",
		"FE145": "7b",
		"FE146": "7c",
		"FE147": "7d",
	},
	"Icatian Javelineers": map[string]string{
		"FE148": "8a",
		"FE149": "8b",
		"FE150": "8c",
	},
	"Icatian Moneychanger": map[string]string{
		"FE152": "10a",
		"FE153": "10b",
		"FE154": "10c",
	},
	"Icatian Scout": map[string]string{
		"FE157": "13a",
		"FE158": "13b",
		"FE159": "13c",
		"FE160": "13d",
	},
	"Initiates of the Ebon Hand": map[string]string{
		"FE016": "39a",
		"FE017": "39b",
		"FE018": "39c",
	},
	"Merseine": map[string]string{
		"FE047": "23a",
		"FE048": "23b",
		"FE049": "23c",
		"FE050": "23d",
	},
	"Mindstab Thrull": map[string]string{
		"FE019": "40a",
		"FE020": "40b",
		"FE021": "40c",
	},
	"Necrite": map[string]string{
		"FE022": "41a",
		"FE023": "41b",
		"FE024": "41c",
	},
	"Night Soil": map[string]string{
		"FE080": "71a",
		"FE081": "71b",
		"FE082": "71c",
	},
	"Orcish Spy": map[string]string{
		"FE124": "61a",
		"FE125": "61b",
		"FE126": "61c",
	},
	"Orcish Veteran": map[string]string{
		"FE127": "62a",
		"FE128": "62b",
		"FE129": "62c",
		"FE130": "62d",
	},
	"Order of the Ebon Hand": map[string]string{
		"FE025": "42a",
		"FE026": "42b",
		"FE027": "42c",
	},
	"Order of Leitbur": map[string]string{
		"FE163": "16a",
		"FE164": "16b",
		"FE165": "16c",
		"Facing Right, Bryon Wackwitz":  "16a",
		"Facing Left, Bryon Wackwitz":   "16b",
		"Bryon Wackwitz, Female Knight": "16a",
		"Bryon Wackwitz, Male Knight":   "16b",
	},
	"Spore Cloud": map[string]string{
		"FE083": "72a",
		"62b":   "72b",
		"FE084": "72b",
		"FE085": "72c",
	},
	"Thallid": map[string]string{
		"FE087": "74a",
		"FE088": "74b",
		"FE089": "74c",
		"FE090": "74d",
	},
	"Thorn Thallid": map[string]string{
		"FE096": "80a",
		"FE097": "80b",
		"FE098": "80c",
		"FE099": "80d",
	},
	"Tidal Flats": map[string]string{
		"FE054": "27a",
		"FE055": "27b",
		"FE056": "27c",
		"Rob Alexander Lush Horizon":       "27a",
		"Rob Alexander Sun Through Clouds": "27b",
		"Rob Alexander, Lake":              "27a",
		"Rob Alexander, Sun":               "27b",
	},
	"Vodalian Mage": map[string]string{
		"Poole": "30b",
		"FE059": "30a",
		"FE060": "30b",
		"FE061": "30c",
	},
	"Vodalian Soldiers": map[string]string{
		"FE062": "31a",
		"FE063": "31b",
		"FE064": "31c",
		"FE065": "31d",
	},
}

var ed5Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"A":                             "446",
		"C":                             "447",
		"B":                             "448",
		"D":                             "449",
		"417":                           "446",
		"418 Night":                     "447",
		"419 Blue sky // Yellow Clouds": "448",
		"420 Snow":                      "449",
	},
	"Island": map[string]string{
		"A":   "434",
		"D":   "435",
		"C":   "436",
		"B":   "437",
		"425": "434",
		"426": "435",
		"427": "436",
		"428": "437",
	},
	"Mountain": map[string]string{
		"A":               "442",
		"D":               "443",
		"C":               "444",
		"B":               "445",
		"430":             "442",
		"432 Brown Trees": "443",
		"431 Fog":         "444",
		"433 Flowers":     "445",
	},
	"Plains": map[string]string{
		"A":                         "430",
		"D":                         "431",
		"B":                         "432",
		"C":                         "433",
		"434 Winter":                "430",
		"435 Lone Tree in Distance": "431",
		"436 Wheat":                 "432",
		"437 Rippling Hill":         "433",
	},
	"Swamp": map[string]string{
		"D":                     "438",
		"B":                     "439",
		"A":                     "440",
		"C":                     "441",
		"442 Broken Trees":      "438",
		"443 Center Right Tree": "439",
		"444 Fallen Tree":       "440",
		"445 Center Left Tree":  "441",
	},
}

var ed4Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"A Rocks":                 "376",
		"B Path":                  "377",
		"C Dark Tree":             "378",
		"177 Boulders Foreground": "376",
		"175 Brown Dirt Road":     "377",
		"176 Dark and Gloomy":     "378",
	},
	"Island": map[string]string{
		"A Purple":                "367",
		"B Light Purple":          "368",
		"C Dark Purple":           "369",
		"179 Golden Horizon":      "367",
		"178 Clear Blue Daylight": "368",
		"180 Pink & Orange Dusk":  "369",
	},
	"Mountain": map[string]string{
		"A Small Tree":                   "373",
		"B Snowy":                        "374",
		"C Dark Red":                     "375",
		"183 Grey Mountain / Red Sky":    "373",
		"184 Light Blue Sky/Snow":        "374",
		"182 Dark Green Clouds/Blue Sky": "375",
	},
	"Plains": map[string]string{
		"A Light":                     "364",
		"B Little Trees":              "365",
		"C Dark":                      "366",
		"188 Four Peaks Clear Meadow": "364",
		"187 Six Trees":               "365",
		"186 Pink Horizon":            "366",
	},
	"Swamp": map[string]string{
		"A Light":                  "370",
		"B Two Branches":           "371",
		"C Dark":                   "372",
		"192 Blue and Foggy":       "370",
		"190 Brown and Foggy":      "371",
		"191 Dark Grey Foreground": "372",
	},
}

var prwkVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"Ravnica Weekend Golgari":  "A06",
		"Ravnica Weekend Selesnya": "A09",
	},
	"Island": map[string]string{
		"Ravnica Weekend Dimir": "A01",
		"Ravnica Weekend Izzet": "A03",
	},
	"Mountain": map[string]string{
		"Ravnica Weekend Izzet": "A04",
		"Ravnica Weekend Boros": "A07",
	},
	"Plains": map[string]string{
		"Ravnica Weekend Boros":    "A08",
		"Ravnica Weekend Selesnya": "A10",
	},
	"Swamp": map[string]string{
		"Ravnica Weekend Dimir":   "A02",
		"Ravnica Weekend Golgari": "A05",
	},
}

var hmlVariants = map[string]map[string]string{
	"Abbey Matron": map[string]string{
		"Hood":                    "2a",
		"No Hood":                 "2b",
		"OR003":                   "2a",
		"AbbeyMatron":             "2b",
		"Hair Covered":            "2a",
		"Pointing to Bottom Left": "2b",
	},
	"Aliban's Tower": map[string]string{
		"Glowing Tower":     "61a",
		"Knights on Horses": "61b",
		"OR006":             "61a",
		"AlibansTower":      "61b",
		"Black":             "61a",
		"Horses":            "61b",
	},
	"Ambush Party": map[string]string{
		"Doorway":      "63a",
		"Mountain":     "63b",
		"OR007":        "63a",
		"AmbushParty":  "63b",
		"Torch":        "63a",
		"Mountainside": "63b",
	},
	"Anaba Bodyguard": map[string]string{
		"Alone":          "66a",
		"With Human":     "66b",
		"OR012":          "66a",
		"AnabaBodyguard": "66b",
		"Green Cloak":    "66a",
		"Tongue Out":     "66b",
	},
	"Anaba Shaman": map[string]string{
		"Facing Right": "67b",
		"Facing Left":  "67a",
		"AnabaShaman":  "67a",
		"OR014":        "67b",
	},
	"Aysen Bureaucrats": map[string]string{
		"One Bureaucrat":   "3a",
		"Two Bureaucrats":  "3b",
		"OR023":            "3a",
		"AysenBureaucrats": "3b",
	},
	"Carapace": map[string]string{
		"Purple Carapace": "84a",
		"Red Carapace":    "84b",
		"OR033":           "84a",
		"Carapace":        "84b",
		"In a Tree":       "84a",
		"Sword":           "84b",
	},
	"Cemetery Gate": map[string]string{
		"No Zombie":     "44a",
		"Zombie":        "44b",
		"OR035":         "44a",
		"CemeteryGate":  "44b",
		"Just the Gate": "44a",
		"Vamp in Red":   "44b",
	},
	"Dark Maze": map[string]string{
		"Man Kneeling":     "25a",
		"Man Laying Down":  "25b",
		"DarkMaze":         "25a",
		"OR043":            "25b",
		"Sword & Shield":   "25a",
		"Laying on Ground": "25b",
	},
	"Dry Spell": map[string]string{
		"Fish Bones":      "46a",
		"Skull With Helm": "46b",
		"DrySpell":        "46a",
		"OR050":           "46b",
		"Fish":            "46a",
		"Skull":           "46b",
	},
	"Dwarven Trader": map[string]string{
		"Man and Woman":   "72a",
		"Woman and Horse": "72b",
		"OR054":           "72a",
		"DwarvenTrader":   "72b",
		"Two People":      "72a",
		"Horse":           "72b",
	},
	"Feast of the Unicorn": map[string]string{
		"Goblins":           "47a",
		"Horse Head":        "47b",
		"OR059":             "47a",
		"UnicornFeast":      "47b",
		"Green Creature":    "47a",
		"Head on a Platter": "47b",
	},
	"Folk of An-Havva": map[string]string{
		"Dancing":         "87a",
		"Sitting on Wall": "87b",
		"OR062":           "87a",
		"FolkOfAn":        "87b",
		"Hoedown":         "87a",
		"Pensive":         "87b",
	},
	"Giant Albatross": map[string]string{
		"Ship's Mast":  "27a",
		"Clouds":       "27b",
		"OR068":        "27a",
		"GiantAlbatro": "27b",
		"Over a Ship":  "27a",
		"Over Ocean":   "27b",
		"Ship":         "27a",
		"Saddle":       "27b",
	},
	"Hungry Mist": map[string]string{
		"Lantern":        "88a",
		"No Lantern":     "88b",
		"HungryMist":     "88a",
		"OR075":          "88b",
		"On Roof":        "88a",
		"Attacking Neck": "88b",
	},
	"Labyrinth Minotaur": map[string]string{
		"Maze Background":   "30a",
		"Black Background":  "30b",
		"OR086":             "30a",
		"LabyrinthMinotaur": "30b",
		"Miner":             "30a",
		"Tattooed Face":     "30b",
	},
	"Memory Lapse": map[string]string{
		"Female":       "32a",
		"Male":         "32b",
		"OR093":        "32a",
		"MemoryLapse":  "32b",
		"Puzzle Woman": "32a",
		"Bald man":     "32b",
	},
	"Mesa Falcon": map[string]string{
		"Flying":     "10a",
		"Perched":    "10b",
		"OR096":      "10a",
		"MesaFalcon": "10b",
		"Blue Sky":   "10a",
	},
	"Reef Pirates": map[string]string{
		"Zombies":     "36a",
		"Ships":       "36b",
		"OR104":       "36a",
		"ReefPirates": "36b",
		"Two Pirates": "36a",
		"Two Ships":   "36b",
	},
	"Samite Alchemist": map[string]string{
		"Window":          "13a",
		"Green Beaker":    "13b",
		"OR112":           "13a",
		"SamiteAlchemist": "13b",
		"With Window":     "13a",
		"No Window":       "13b",
	},
	"Sengir Bats": map[string]string{
		"Perching":   "57a",
		"Flying":     "57b",
		"OR118":      "57a",
		"SengirBats": "57b",
		"Perched":    "57a",
		"Hanging":    "57a",
	},
	"Shrink": map[string]string{
		"Man in Shadow":        "97a",
		"Giant Woman":          "97b",
		"OR125":                "97a",
		"Shrink":               "97b",
		"In Shadow Looking Up": "97a",
		"Female with Sword":    "97b",
	},
	"Torture": map[string]string{
		"Man with Markings": "59a",
		"Hooded Figure":     "59b",
		"OR130":             "59a",
		"Torture":           "59b",
		"Back":              "59a",
		"Table and Tools":   "59b",
	},
	"Trade Caravan": map[string]string{
		"Giraffe on Right": "19a",
		"Moon Top Left":    "19b",
		"TradeCaravan":     "19a",
		"OR132":            "19b",
		"No Moon":          "19a",
		"Moon":             "19b",
		"Giraffe":          "19a",
		"Full Moon":        "19b",
	},
	"Willow Faerie": map[string]string{
		"Male":          "99a",
		"Female":        "99b",
		"OR137":         "99a",
		"WillowFaerie":  "99b",
		"Deer":          "99a",
		"Holding Acorn": "99b",
	},
}

var iceVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A": "380",
		"B": "381",
		"C": "382",
		"White Trees, Yellow Sun": "380",
		"Pink Sky, Pink River":    "381",
		"Knobby Trees":            "382",
	},
	"Island": map[string]string{
		"A":                      "368",
		"B":                      "369",
		"C":                      "370",
		"Iceberg":                "368",
		"Icy Island, Green Land": "369",
		"Trees On Snowy Island":  "370",
	},
	"Mountain": map[string]string{
		"A":                "376",
		"B":                "377",
		"C":                "378",
		"Trees Along Base": "376",
		"Barren Tree":      "377",
		"Heavy Snow":       "378",
	},
	"Plains": map[string]string{
		"A": "364",
		"B": "365",
		"C": "366",
		"Creepy Eyes Bottom Left": "364",
		"Branch Bottom Right":     "365",
		"Butterfly":               "366",
	},
	"Swamp": map[string]string{
		"A": "373",
		"B": "374",
		"C": "375",
		"Straight Through Creepy Trees": "373",
		"Tall Grass":                    "374",
		"Stump in Swamp":                "375",
	},
}

var itpVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A Rocks":     "65",
		"B Path":      "66",
		"C Dark Tree": "67",
	},
	"Island": map[string]string{
		"A Purple":       "56",
		"B Light Purple": "57",
		"C Dark Purple":  "58",
	},
	"Mountain": map[string]string{
		"A Small Tree": "62",
		"B Snowy":      "63",
		"C Dark Red":   "64",
	},
	"Plains": map[string]string{
		"A Light":        "53",
		"B Little Trees": "54",
		"C Dark":         "55",
	},
	"Swamp": map[string]string{
		"A Light":        "59",
		"B Two Branches": "60",
		"C Dark":         "61",
	},
}

var leaVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A Rocks":         "294",
		"B Path":          "295",
		"Brown Dirt Road": "295",
	},
	"Island": map[string]string{
		"A Purple":            "288",
		"B Light Purple":      "289",
		"Clear Blue Daylight": "289",
	},
	"Mountain": map[string]string{
		"A Small Tree":            "292",
		"B Snowy":                 "293",
		"Grey Mountain / Red Sky": "292",
	},
	"Plains": map[string]string{
		"A Light":        "286",
		"B Little Trees": "287",
	},
	"Swamp": map[string]string{
		"A Light":         "290",
		"B Two Branches":  "291",
		"Blue and Foggy":  "290",
		"Brown and Foggy": "291",
	},
}

var pmpsVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"The Golgari Swarm":     "303",
		"The Gruul Clans":       "305",
		"The Selesnya Conclave": "304",
		"The Simic Combine":     "306",
	},
	"Island": map[string]string{
		"The Azorius Senate": "291",
		"The House Dimir":    "294",
		"The Izzet League":   "292",
		"The Simic Combine":  "293",
	},
	"Mountain": map[string]string{
		"The Boros Legion":   "302",
		"The Gruul Clans":    "300",
		"The Izzet League":   "301",
		"The Cult of Rakdos": "299",
	},
	"Plains": map[string]string{
		"The Azorius Senate":    "289",
		"The Boros Legion":      "290",
		"The Orzhov Syndicate":  "287",
		"The Selesnya Conclave": "288",
	},
	"Swamp": map[string]string{
		"The House Dimir":      "296",
		"The Golgari Swarm":    "295",
		"The Orzhov Syndicate": "297",
		"The Cult of Rakdos":   "298",
	},
}

var mirVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A": "347",
		"B": "348",
		"C": "349",
		"D": "350",
		"White Flowers Red Pattern": "347",
		"Waterfall Centered":        "348",
		"Waterfall Left Side":       "349",
		"Red Foliage Pink Flowers":  "350",
	},
	"Island": map[string]string{
		"A":                  "335",
		"B":                  "336",
		"C":                  "337",
		"D":                  "338",
		"Palm Tree":          "335",
		"Shallow Foreground": "336",
		"Light Fog":          "337",
		"Pink Sky":           "338",
	},
	"Mountain": map[string]string{
		"A":                  "343",
		"B":                  "344",
		"C":                  "345",
		"D":                  "346",
		"Green Hills":        "343",
		"Blue Sky/Red Dunes": "344",
		"Purple Hue":         "345",
		"Black Foreground":   "346",
	},
	"Plains": map[string]string{
		"A":             "331",
		"B":             "332",
		"C":             "333",
		"D":             "334",
		"Watering Hole": "331",
		"Oxen":          "332",
		"Zebra":         "333",
		"Bird":          "334",
	},
	"Swamp": map[string]string{
		"A":             "339",
		"B":             "340",
		"C":             "341",
		"D":             "342",
		"Sunset":        "339",
		"Moonlight":     "340",
		"Green Light":   "341",
		"Purple Clouds": "342",
	},
}

var ogwVariants = map[string]map[string]string{
	"Wastes": map[string]string{
		"OGW183": "183",
		"OGW185": "183a",
		"OGW184": "184",
		"OGW186": "184a",
	},
}

var po2Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"A": "163",
		"B": "164",
		"C": "165",
		"Waterfall Background": "163",
		"Creek":                "164",
		"Blue Sky":             "165",
	},
	"Island": map[string]string{
		"A":                     "154",
		"B":                     "155",
		"C":                     "156",
		"Dragon":                "154",
		"Hot Air Balloon":       "155",
		"Single Ship Left Side": "156",
	},
	"Mountain": map[string]string{
		"A":                    "160",
		"B":                    "161",
		"C":                    "162",
		"Red Mist":             "160",
		"Fog - Foreground":     "161",
		"Archway - Right Side": "162",
	},
	"Plains": map[string]string{
		"A":                "151",
		"B":                "152",
		"C":                "153",
		"Farmhouses":       "151",
		"Palace at Sunset": "152",
		"Flock of Birds":   "153",
	},
	"Swamp": map[string]string{
		"A": "157",
		"B": "158",
		"C": "159",
		"Ash White Trees Background": "157",
		"Animal Skeleton":            "158",
		"Decrepit Observatory":       "159",
	},
}

var porVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A": "212",
		"B": "213",
		"C": "214",
		"D": "215",
		"Thick Tree Center Foreground":  "212",
		"Leaning Tree Center Midground": "213",
		"Three Dark Trees Foreground":   "214",
		"Violet Sky":                    "215",
	},
	"Island": map[string]string{
		"A":               "200",
		"B":               "201",
		"C":               "202",
		"D":               "203",
		"Waterfall":       "200",
		"Pointed Peaks":   "201",
		"Unbroken Beach":  "202",
		"Sun Upper-Right": "203",
	},
	"Mountain": map[string]string{
		"A": "208",
		"B": "209",
		"C": "210",
		"D": "211",
		"Two Peaks / Distant Trees":  "208",
		"No Peaks Upper-Left":        "209",
		"Big Trees Foreground":       "210",
		"Three Peaks / Left Tallest": "211",
	},
	"Plains": map[string]string{
		"A":                    "196",
		"B":                    "197",
		"C":                    "198",
		"D":                    "199",
		"Many Distant Trees":   "196",
		"Left Tree Cut-Off":    "197",
		"Full Tree Foreground": "198",
		"Branches Upper-Right": "199",
	},
	"Swamp": map[string]string{
		"A":                      "204",
		"B":                      "205",
		"C":                      "206",
		"D":                      "207",
		"Copper Sky":             "204",
		"Gray Sky":               "205",
		"White Tree / Green Sky": "206",
		"Gold Sun Upper-Right":   "207",
	},
}

var ptcVariants = map[string]map[string]string{
	"Circle of Protection: Green": map[string]string{
		"Ice Age Sideboard Bertrand Lestree":     "bl14sb",
		"Ice Age Sideboard Michael Locanto":      "ml14sb",
		"4th Edition Sideboard Bertrand Lestree": "bl16sb",
		"4th Edition Sideboard Michael Locanto":  "ml16sb",
	},
	"Circle of Protection: Red": map[string]string{
		"Ice Age Sideboard Bertrand Lestree":     "bl15sb",
		"Ice Age Sideboard Michael Locanto":      "ml15sb",
		"4th Edition Sideboard Bertrand Lestree": "bl17sb",
		"4th Edition Sideboard Michael Locanto":  "ml17sb",
	},
	"Forest": map[string]string{
		"4th Edition Path Bertrand Lestree 1996":      "bl377",
		"4th Edition Path Preston Poulter 1996":       "pp377",
		"4th Edition Rock Bertrand Lestree 1996":      "bl376",
		"4th Edition Rock Preston Poulter 1996":       "pp376",
		"4th Edition Dark Tree Bertrand Lestree 1996": "bl378",
		"4th Edition Dark Tree Preston Poulter 1996":  "pp378",
	},
	"Island": map[string]string{
		"4th Edition Purple Shawn Hammer Regnier 1996":       "shr367",
		"4th Edition Purple Michael Locanto 1996":            "ml367",
		"4th Edition Light Purple Michael Locanto 1996":      "ml368",
		"4th Edition Light Purple Shawn Hammer Regnier 1996": "shr368",
		"4th Edition Dark Purple Shawn Hammer Regnier 1996":  "shr369",
		"4th Edition Dark Purple Michael Locanto 1996":       "ml369",
	},
	"Mountain": map[string]string{
		"4th Edition Little Trees Eric Tam":     "et373",
		"4th Edition Little Trees Mark Justice": "mj373",
		"4th Edition Snowy Eric Tam":            "et374",
		"4th Edition Snowy Mark Justice":        "mj374",
		"4th Edition Dark Red Eric Tam":         "et375",
		"4th Edition Dark Red Mark Justice":     "mj375",
	},
	"Plains": map[string]string{
		"4th Edition Light Bertrand Lestree 1996":            "bl364",
		"4th Edition Light Eric Tam 1996":                    "et364",
		"4th Edition Light Mark Justice 1996":                "mj364",
		"4th Edition Light Michael Locanto 1996":             "ml364",
		"4th Edition Light Preston Poulter 1996":             "pp364",
		"4th Edition Light Shawn Hammer Regnier 1996":        "shr364",
		"4th Edition Little Trees Bertrand Lestree 1996":     "bl365",
		"4th Edition Little Trees Eric Tam 1996":             "et365",
		"4th Edition Little Trees Mark Justice 1996":         "mj365",
		"4th Edition Little Trees Michael Locanto 1996":      "ml365",
		"4th Edition Little Trees Preston Poulter 1996":      "pp365",
		"4th Edition Little Trees Shawn Hammer Regnier 1996": "shr365",
		"4th Edition Dark Bertrand Lestree 1996":             "bl366",
		"4th Edition Dark Eric Tam 1996":                     "et366",
		"4th Edition Dark Mark Justice 1996":                 "mj366",
		"4th Edition Dark Michael Locanto 1996":              "ml366",
		"4th Edition Dark Preston Poulter 1996":              "pp366",
		"4th Edition Dark Shawn Hammer Regnier 1996":         "shr366",
	},
	"Swamp": map[string]string{
		"4th Edition Light George Baxter 1996":        "gb370",
		"4th Edition Light Leon Lindback 1996":        "ll370",
		"4th Edition Two Branches Leon Lindback 1996": "ll371",
		"4th Edition Two Branches George Baxter 1996": "gb371",
		"4th Edition Dark Leon Lindback 1996":         "ll372",
		"4th Edition Dark George Baxter 1996":         "gb372",
	},
}

var rinVariants = map[string]map[string]string{
	"Urza's Mine": map[string]string{
		"RI053":     "175",
		"miniera53": "176",
		"miniera56": "177",
		"miniera54": "178",
	},
	"Urza's Power Plant": map[string]string{
		"centrale57": "179",
		"centrale60": "180",
		"centrale58": "181",
		"RI054":      "182",
	},
	"Urza's Tower": map[string]string{
		"RI055":   "183",
		"torre63": "184",
		"torre62": "185",
		"torre64": "186",
	},
}

var prw2Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"Ravnica Weekend Gruul": "B08",
		"Ravnica Weekend Simic": "B09",
	},
	"Island": map[string]string{
		"Ravnica Weekend Azorius": "B02",
		"Ravnica Weekend Simic":   "B10",
	},
	"Mountain": map[string]string{
		"Ravnica Weekend Rakdos": "B06",
		"Ravnica Weekend Gruul":  "B07",
	},
	"Plains": map[string]string{
		"Ravnica Weekend Azorius": "B01",
		"Ravnica Weekend Orzhov":  "B03",
	},
	"Swamp": map[string]string{
		"Ravnica Weekend Orzhov": "B04",
		"Ravnica Weekend Rakdos": "B05",
	},
}

var ed3Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"A": "304",
		"B": "305",
		"C": "306",

		"A Rocks":     "304",
		"B Path":      "305",
		"C Dark Tree": "306",

		"B Rocks":            "304",
		"A Pathway":          "305",
		"C Eyes in treehole": "306",

		"Boulders Foreground": "304",
		"Brown Dirt Road":     "305",
		"Dark and Gloomy":     "306",
	},
	"Island": map[string]string{
		"A": "295",
		"B": "296",
		"C": "297",

		"A Purple":       "295",
		"B Light Purple": "296",
		"C Dark Purple":  "297",

		"B Purple island, gold horizon":   "295",
		"A Green island":                  "296",
		"C Purple island, orange horizon": "297",

		"Golden Horizon":      "295",
		"Clear Blue Daylight": "296",
		"Pink & Orange Dusk":  "297",
	},
	"Mountain": map[string]string{
		"A": "301",
		"B": "302",
		"C": "303",

		"A Small Tree": "301",
		"B Snowy":      "302",
		"C Dark Red":   "303",

		"B Gray mountains":            "301",
		"A Blue mountains":            "302",
		"C Brown mountain, green sky": "303",

		"Grey Mountain / Red Sky":    "301",
		"Light Blue Sky/Snow":        "302",
		"Dark Green Clouds/Blue Sky": "303",
	},
	"Plains": map[string]string{
		"A": "292",
		"B": "293",
		"C": "294",

		"A Light":        "292",
		"B Little Trees": "293",
		"C Dark":         "294",

		"C Cliff in background": "292",
		"B No trees on plain":   "293",
		"A Trees on plain":      "294",

		"Four Peaks Clear Meadow": "292",
		"Pink Horizon":            "293",
		"Six Trees":               "294",
	},
	"Swamp": map[string]string{
		"A": "298",
		"B": "299",
		"C": "300",

		"A Light":        "298",
		"B Two Branches": "299",
		"C Dark":         "300",

		"B One branch in foreground": "298",
		"A Brown, two branches":      "299",
		"C Black, two branches":      "300",

		"Blue and Foggy":       "298",
		"Brown and Foggy":      "299",
		"Dark Grey Foreground": "300",
	},
}

var sldVariants = map[string]map[string]string{
	"Serum Visions": map[string]string{
		"Secret Lair 29 Collantes": "29",
		"Secret Lair 30 DXTR":      "30",
		"Secret Lair 31 YS":        "31",
		"Secret Lair 32 Zuverza":   "32",
		"Versione 1":               "29",
		"Versione 2":               "30",
		"Versione 3":               "31",
		"Versione 4":               "32",
	},
}

var soiVariants = map[string]map[string]string{
	"Tamiyo's Journal": map[string]string{
		"":          "265",
		"Foil":      "265†a",
		"Entry 434": "265",
		"Entry 546": "265†",
		"Entry 653": "265†a",
		"Entry 711": "265†b",
		"Entry 855": "265†c",
		"Entry 922": "265†d",
	},
}

var psoiVariants = map[string]map[string]string{
	"Tamiyo's Journal": map[string]string{
		"Prerelease Promo Entry 855":              "265s",
		"Shadows over Innistrad Prerelease Promo": "265s†",
	},
}

var tmpVariants = map[string]map[string]string{
	"Forest": map[string]string{
		"A": "347",
		"B": "348",
		"C": "349",
		"D": "350",
		"Looking up to light":     "347",
		"Thick roots":             "348",
		"Wavy clouds":             "349",
		"Branch going horizontal": "350",
	},
	"Island": map[string]string{
		"A": "335",
		"B": "336",
		"C": "337",
		"D": "338",
		"Island with trailing islands, bright ocean": "335",
		"Cave, crashing waves":                       "336",
		"Lots of islands, bright ocean":              "338",
		"Large island, purple foggy sky":             "337",
	},
	"Mountain": map[string]string{
		"A":                                  "343",
		"B":                                  "344",
		"C":                                  "345",
		"D":                                  "346",
		"Spiky mountains":                    "343",
		"Two spiky mountains pointing right": "344",
		"Arch-like mountain":                 "345",
		"Spiky mountains pointing left":      "346",
	},
	"Plains": map[string]string{
		"A": "331",
		"B": "332",
		"C": "333",
		"D": "334",
		"Black and grey sky, two rocks": "331",
		"Swirly grey sky, barren tree":  "332",
		"Bush on the left, grey sky":    "333",
		"Three tall rocks":              "334",
	},
	"Swamp": map[string]string{
		"A": "339",
		"B": "340",
		"C": "341",
		"D": "342",
		"Two tree stumps, pink sky":          "339",
		"Fallen tree, stump in background":   "340",
		"Rock, yellow fog":                   "341",
		"Tree in far background, yellow fog": "342",
	},
}

var ustVariants = map[string]map[string]string{
	"Amateur Auteur": map[string]string{
		"Ravnica":   "3a",
		"Innistrad": "3b",
		"Theros":    "3c",
		"Zendikar":  "3d",
		"Version 1": "3a",
	},
	"Beast in Show": map[string]string{
		"Tyrranax":  "103a",
		"Gnarlid":   "103b",
		"Baloth":    "103c",
		"Thragtusk": "103d",
		"Version 1": "103a",
	},
	"Everythingamajig": map[string]string{
		"Move":      "147a",
		"Draw":      "147b",
		"Flip":      "147c",
		"Add":       "147d",
		"Sacrifice": "147e",
		"Scry":      "147f",
		"Version 1": "147a",
	},
	"Extremely Slow Zombie": map[string]string{
		"Summer":    "54a",
		"Fall":      "54b",
		"Winter":    "54c",
		"Spring":    "54d",
		"Version 1": "54a",
	},
	"Garbage Elemental": map[string]string{
		"2/4":       "82a",
		"3/1":       "82b",
		"3/2":       "82c",
		"3/3":       "82d",
		"4/3":       "82e",
		"6/5":       "82f",
		"Version 1": "82a",
		"a 2/4":     "82a",
		"B 3/1":     "82b",
		"b 3/1":     "82b",
		"c 3/2":     "82c",
		"d 3/3":     "82d",
		"e 4/3":     "82e",
		"f 6/5":     "82f",
	},
	"Ineffable Blessing": map[string]string{
		"Choose flavor":      "113a",
		"Choose artist":      "113b",
		"Choose border":      "113c",
		"Choose rarity":      "113d",
		"Choose odd or even": "113e",
		"Choose a number":    "113f",
		"Version 1":          "113a",
	},
	"Knight of the Kitchen Sink": map[string]string{
		"Black borders":          "12a",
		"Even collector numbers": "12b",
		"Loose lips":             "12c",
		"Odd collector numbers":  "12d",
		"Two-word names":         "12e",
		"Watermarks":             "12f",
		"Version 1":              "12a",
	},
	"Novellamental": map[string]string{
		"''My grandmother…''": "41a",
		"''This pendant…''":   "41b",
		"''The chain…''":      "41c",
		"''My heart…''":       "41d",
		"Version 1":           "41a",
	},
	"Secret Base": map[string]string{
		"Order of the Widget":      "165a",
		"Agents of S.N.E.A.K.":     "165b",
		"League of Dastardly Doom": "165c",
		"Goblin Explosioneers":     "165d",
		"Crossbreed Labs":          "165e",
		"Version 2":                "165b",
	},
	"Sly Spy": map[string]string{
		"Reveal hand":                   "67a",
		"Destroy creature facing left":  "67b",
		"Lose a finger":                 "67c",
		"Destroy creature facing right": "67d",
		"Reveal top of library":         "67e",
		"Roll six-sided die":            "67f",
		"Version 1":                     "67a",
	},
	"Target Minotaur": map[string]string{
		"Ice":       "98a",
		"Rain":      "98b",
		"Fire":      "98c",
		"Roots":     "98d",
		"Version 1": "98a",
	},
	"Very Cryptic Command": map[string]string{
		"Switch":    "49a",
		"Untap":     "49b",
		"Draw":      "49c",
		"Return":    "49d",
		"Counter":   "49e",
		"Scry":      "49f",
		"Version 2": "49b",
	},
}

var wc97Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"5th Edition A Svend Geertsen 1997": "sg446",
		"5th Edition B Svend Geertsen 1997": "sg447",
		"5th Edition C Svend Geertsen 1997": "sg448",
		"5th Edition D Svend Geertsen 1997": "sg449",
	},
	"Island": map[string]string{
		"5th Edition A Janosch Kuehn 1997": "jk434",
		"5th Edition B Janosch Kuehn 1997": "jk435",
		"5th Edition C Janosch Kuehn 1997": "jk436",
		"5th Edition D Janosch Kuehn 1997": "jk437",
		"5th Edition A Paul McCabe 1997":   "pm434",
		"5th Edition B Paul McCabe 1997":   "pm435",
		"5th Edition C Paul McCabe 1997":   "pm436",
		"5th Edition D Paul McCabe 1997":   "pm437",
	},
	"Mountain": map[string]string{
		"5th Edition A Paul McCabe 1997":   "pm442",
		"5th Edition B Paul McCabe 1997":   "pm443",
		"5th Edition C Paul McCabe 1997":   "pm444",
		"5th Edition D Paul McCabe 1997":   "pm445",
		"5th Edition A Janosch Kuehn 1997": "jk442",
		"5th Edition B Janosch Kuehn 1997": "jk443",
		"5th Edition C Janosch Kuehn 1997": "jk444",
		"5th Edition D Janosch Kuehn 1997": "jk445",
	},
	"Plains": map[string]string{
		"5th Edition A Janosch Kuehn 1997": "jk430",
		"5th Edition B Janosch Kuehn 1997": "jk431",
		"5th Edition C Janosch Kuehn 1997": "jk432",
		"5th Edition D Janosch Kuehn 1997": "jk433",
	},
	"Swamp": map[string]string{
		"5th Edition A Jakub Slemr 1997": "js438",
		"5th Edition B Jakub Slemr 1997": "js439",
		"5th Edition C Jakub Slemr 1997": "js440",
		"5th Edition D Jakub Slemr 1997": "js441",
	},
}

var wc98Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"Tempest A Brian Seldon 1998": "bs347",
		"Tempest B Brian Seldon 1998": "bs348",
		"Tempest C Brian Seldon 1998": "bs349",
		"Tempest D Brian Seldon 1998": "bs350",
	},
	"Island": map[string]string{
		"Tempest A Randy Buehler 1998": "rb335",
		"Tempest B Randy Buehler 1998": "rb336",
		"Tempest C Randy Buehler 1998": "rb337",
		"Tempest D Randy Buehler 1998": "rb338",
	},
	"Mountain": map[string]string{
		"Tempest A Ben Rubin 1998": "br343",
		"Tempest B Ben Rubin 1998": "br344",
		"Tempest C Ben Rubin 1998": "br345",
		"Tempest D Ben Rubin 1998": "br346",
	},
	"Plains": map[string]string{
		"Tempest A Brian Hacker 1998": "bh331",
		"Tempest B Brian Hacker 1998": "bh332",
		"Tempest C Brian Hacker 1998": "bh333",
		"Tempest D Brian Hacker 1998": "bh334",
	},
	"Firestorm": map[string]string{
		"Brian Seldon 1998":        "bs101",
		"Sideboard Ben Rubin 1998": "br101sb",
	},
}

var wc99Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"Tempest A Matt Linde 1999":       "ml347a",
		"6th Edition 347 Matt Linde 1999": "ml347b",
	},
	"Mountain": map[string]string{
		"6th Edition 346 Mark Le Pine 1999": "mlp346a",
		"Urza's Saga 346 Mark Le Pine 1999": "mlp346b",
		"Tempest A Mark Le Pine 1999":       "mlp344a",
		"Tempest B Mark Le Pine 1999":       "mlp344",
		"Tempest A Kai Budde 1999":          "kb343",
		"Tempest B Kai Budde 1999":          "kb344",
		"Tempest C Kai Budde 1999":          "kb345",
	},
	"Swamp": map[string]string{
		"Urza's Saga 346 Jakub Slemr 1999": "js340",
		"Tempest B Jakub Slemr 1999":       "js340a",
		"6th Edition 340 Jakub Slemr 1999": "js340b",
	},
}

var wc01Variants = map[string]map[string]string{
	"Forest": map[string]string{
		"Mercadian Masques 347 Jan Tomcani 2001": "jt347",
		"Invasion 347 Jan Tomcani 2001":          "jt347a",
		"Mercadian Masques 348 Jan Tomcani 2001": "jt348",
		"Invasion 348 Jan Tomcani 2001":          "jt348a",
		"Mercadian Masques 349 Jan Tomcani 2001": "jt349",
		"Invasion 349 Jan Tomcani 2001":          "jt349a",
	},
	"Island": map[string]string{
		"7th Edition 335 Alex Borteh 2001":        "ab335",
		"Invasion 335 Alex Borteh 2001":           "ab335a",
		"Mercadian Masques 335 Alex Borteh 2001":  "ab335b",
		"7th Edition 335 Antoine Ruel 2001":       "ar335",
		"Invasion 335 Antoine Ruel 2001":          "ar335a",
		"Mercadian Masques 335 Antoine Ruel 2001": "ar335b",
		"Invasion 336 Antoine Ruel 2001":          "ar336",
		"Mercadian Masques 336 Antoine Ruel 2001": "ar336a",
		"Mercadian Masques 336 Alex Borteh 2001":  "ab336",
		"Invasion 336 Alex Borteh 2001":           "ab336a",
		"Invasion 337 Alex Borteh 2001":           "ab337",
		"Mercadian Masques 337 Alex Borteh 2001":  "ab337a",
		"Mercadian Masques 338 Alex Borteh 2001":  "ab338",
		"Invasion 338 Alex Borteh 2001":           "ab338a",
	},
	"Mountain": map[string]string{
		"Invasion 343 Jan Tomcani 2001":              "jt343",
		"Mercadian Masques 343 Jan Tomcani 2001":     "jt343a",
		"Invasion 343 Tom van de Logt 2001":          "tvdl343",
		"Mercadian Masques 343 Tom van de Logt 2001": "tvdl343b",
	},
	"Swamp": map[string]string{
		"Invasion 339 Tom van de Logt 2001":          "tvdl339",
		"Mercadian Masques 339 Tom van de Logt 2001": "tvdl339a",
	},
	"Counterspell": map[string]string{
		"7th Edition Alex Borteh 2001":        "ab67",
		"Mercadian Masques Alex Borteh 2001":  "ab69",
		"7th Edition Antoine Ruel 2001":       "ar67",
		"Mercadian Masques Antoine Ruel 2001": "ar69",
	},
}

var wc02Variants = map[string]map[string]string{
	"Island": map[string]string{
		"Odyssey 335 Carlos Romao 2002":     "cr335",
		"Invasion 335 Carlos Romao 2002":    "cr335a",
		"7th Edition 335 Carlos Romao 2002": "cr335b",
		"Invasion 336 Raphael Levy 2002":    "rl336",
		"Odyssey 336 Raphael Levy 2002":     "rl336a",
		"Odyssey 336 Sim Han How 2002":      "shh336a",
		"Invasion 337 Carlos Romao 2002":    "cr337",
		"Odyssey 337 Carlos Romao 2002":     "cr337a",
		"Odyssey 337 Raphael Levy 2002":     "rl337",
		"Invasion 337 Raphael Levy 2002":    "rl337a",
	},
}

var VariantsTable = map[string]map[string]map[string]string{
	"Alliances":                     allVariants,
	"Anthologies":                   athVariants,
	"Antiquities":                   atqVariants,
	"Arena League 2001":             pal01Variants,
	"Asia Pacific Land Program":     palpVariants,
	"Battle Royale Box Set":         brbVariants,
	"Champions of Kamigawa":         chkVariants,
	"Chronicles":                    chrVariants,
	"Collectors’ Edition":           oldLandVariants,
	"Commander Anthology Volume II": cm2Variants,
	"Conspiracy: Take the Crown":    cn2Variants,
	"Deckmasters":                   dkmVariants,
	"Fallen Empires":                femVariants,
	"Fifth Edition":                 ed5Variants,
	"Fourth Edition":                ed4Variants,
	"GRN Ravnica Weekend":           prwkVariants,
	"Homelands":                     hmlVariants,
	"Ice Age":                       iceVariants,
	"Intl. Collectors’ Edition":     oldLandVariants,
	"Introductory Two-Player Set":   itpVariants,
	"Limited Edition Alpha":         leaVariants,
	"Limited Edition Beta":          oldLandVariants,
	"Magic Premiere Shop 2005":      pmpsVariants,
	"Mirage":                        mirVariants,
	"Oath of the Gatewatch":         ogwVariants,
	"Portal Second Age":             po2Variants,
	"Portal":                        porVariants,
	"Pro Tour Collector Set":        ptcVariants,
	"Rinascimento":                  rinVariants,
	"RNA Ravnica Weekend":           prw2Variants,
	"Revised Edition":               ed3Variants,
	"Secret Lair Drop":              sldVariants,
	"Shadows over Innistrad Promos": psoiVariants,
	"Shadows over Innistrad":        soiVariants,
	"Tempest":                       tmpVariants,
	"Unlimited Edition":             oldLandVariants,
	"Unstable":                      ustVariants,
	"World Championship Decks 1997": wc97Variants,
	"World Championship Decks 1998": wc98Variants,
	"World Championship Decks 1999": wc99Variants,
	"World Championship Decks 2001": wc01Variants,
	"World Championship Decks 2002": wc02Variants,
}
