name: riftbound / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket_riftbound]
  schedule:
    - cron: "53 8,20 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardmarket_riftbound
      game: "riftbound"
      datastore-filepath: b2://mtgban-datastore/riftbound/riftbound.json.xz
      mkmids-filepath: b2://mtgban-datastore/riftbound/cardmarket_catalog.json.xz
    secrets: inherit
