name: pokemon / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket_pokemon]
  schedule:
    - cron: "1 1,13 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardmarket_pokemon
      game: "pokemon"
      datastore-filepath: b2://mtgban-datastore/pokemon/pokemon.json.xz
    secrets: inherit
