name: onepiece / coolstuffinc_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [onepiece-coolstuffinc_sealed, onepiece-all]
  schedule:
    - cron: "31 1,13 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-coolstuffinc
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: coolstuffinc_sealed
      game: "onepiece"
      affiliate: ${{ vars.CSI_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/onepiece/onepiece.json.xz
    secrets: inherit
