name: yugioh / tcg_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_sealed_yugioh]
  schedule:
    - cron: "42 8,20 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: tcg_sealed_yugioh
      game: "yugioh"
      datastore-filepath: b2://mtgban-datastore/yugioh/yugioh.json.xz
    secrets: inherit
