name: pokemon / vegassingles

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [vegassingles_pokemon]
  schedule:
    - cron: "30 3,15 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-vegassingles
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: vegassingles_pokemon
      game: "pokemon"
      datastore-filepath: b2://mtgban-datastore/pokemon/pokemon.json.xz
    secrets: inherit
