name: palworld / coolstuffinc

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [palworld-coolstuffinc, palworld-all]
  schedule:
    - cron: "25 3,15 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-coolstuffinc
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: coolstuffinc
      game: "palworld"
      affiliate: ${{ vars.CSI_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/palworld/palworld.json.xz
    secrets: inherit
