name: lorcana / gamenerdz

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [gamenerdz_lorcana]
  schedule:
    - cron: "26 22 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-gamenerdz
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: gamenerdz_lorcana
      game: "lorcana"
      datastore-filepath: b2://mtgban-datastore/lorcana/lorcana.json.xz
    secrets: inherit
