name: gundam / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [gundam-cardmarket, gundam-all]
  schedule:
    - cron: "29 9,21 * * *"

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: cardmarket
      game: "gundam"
      affiliate: ${{ vars.MKM_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/gundam/gundam.json.xz
      cardmarket-catalog-filepath: b2://mtgban-datastore/gundam/cardmarket_catalog.json.xz
    secrets: inherit
