name: lorcana / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket_lorcana]
  schedule:
    - cron: "13 2,14 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardmarket_lorcana
      game: "lorcana"
      datastore-filepath: b2://mtgban-datastore/lorcana/lorcana.json.xz
      mkmids-filepath: b2://mtgban-datastore/lorcana/cardmarket_catalog.json.xz
    secrets: inherit
