name: lorcana / tcg_index

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [lorcana-tcg_index, lorcana-all]
  schedule:
    - cron: "17 1,13 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: tcg_index
      game: "lorcana"
      affiliate: ${{ vars.TCG_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/lorcana/lorcana.json.xz
    secrets: inherit
