name: yugioh / tcg_index

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_index_yugioh]
  schedule:
    - cron: "25 */12 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: tcg_index_yugioh
      game: "yugioh"
      datastore-filepath: b2://mtgban-datastore/yugioh/yugioh.json.xz
    secrets: inherit
