name: lorcana / tcg_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_sealed_lorcana]
  schedule:
    - cron: "40 1,13 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: tcg_sealed_lorcana
      game: "lorcana"
      datastore-filepath: b2://mtgban-datastore/lorcana/lorcana.json.xz
    secrets: inherit
