name: pokemon / tcg_market

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [pokemon-tcg_market, pokemon-all]
  schedule:
    - cron: "14 4,16 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: tcg_market
      game: "pokemon"
      affiliate: ${{ vars.TCG_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/pokemon/pokemon.json.xz
    secrets: inherit
