name: riftbound / cardmarket_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [riftbound-cardmarket_sealed, riftbound-all]
  schedule:
    - cron: "35 11,23 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: cardmarket_sealed
      game: "riftbound"
      affiliate: ${{ vars.MKM_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/riftbound/riftbound.json.xz
    secrets: inherit
