name: tcg_sealed_riftbound

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_sealed_riftbound]
  schedule:
    - cron: "45 */12 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ github.workflow }}
      game: "riftbound"
      datastore-filepath: b2://mtgban-datastore/riftbound/riftbound.json.xz
    secrets: inherit
