name: gundam / cardmarket_market

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket_market_gundam]
  schedule:
    - cron: "41 7 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardmarket_market_gundam
      game: "gundam"
      affiliate: ${{ vars.MKM_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/gundam/gundam.json.xz
      mkmids-filepath: b2://mtgban-datastore/gundam/cardmarket_catalog.json.xz
    secrets: inherit
