name: tcg_market_fleshandblood

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_market_fleshandblood]
  schedule:
    - cron: "30 */12 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ github.workflow }}
      game: "fleshandblood"
      datastore-filepath: b2://mtgban-datastore/fleshandblood/fleshandblood.json.xz
    secrets: inherit
