name: yugioh / cardmarket_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [yugioh-cardmarket_sealed, yugioh-all]
  schedule:
    - cron: "7 11,23 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: cardmarket_sealed
      game: "yugioh"
      affiliate: ${{ vars.MKM_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/yugioh/yugioh.json.xz
    secrets: inherit
