name: riftbound / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [riftbound-cardmarket, riftbound-all]
  schedule:
    - cron: "53 8,20 * * *"

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: cardmarket
      game: "riftbound"
      affiliate: ${{ vars.MKM_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/riftbound/riftbound.json.xz
      cardmarket-catalog-filepath: b2://mtgban-datastore/riftbound/cardmarket_catalog.json.xz
    secrets: inherit
