name: onepiece / tcg_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_sealed_onepiece]
  schedule:
    - cron: "51 5,17 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: tcg_sealed_onepiece
      game: "onepiece"
      datastore-filepath: b2://mtgban-datastore/onepiece/onepiece.json.xz
    secrets: inherit
