name: onepiece / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket_onepiece]
  schedule:
    - cron: "44 9,21 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardmarket_onepiece
      game: "onepiece"
      datastore-filepath: b2://mtgban-datastore/onepiece/onepiece.json.xz
      mkmids-filepath: b2://mtgban-datastore/onepiece/cardmarket_catalog.json.xz
    secrets: inherit
