name: yugioh / cardmarket_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket_sealed_yugioh]
  schedule:
    - cron: "7 11,23 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardmarket_sealed_yugioh
      game: "yugioh"
      datastore-filepath: b2://mtgban-datastore/yugioh/yugioh.json.xz
    secrets: inherit
