name: onepiece / vegassingles

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [vegassingles_onepiece]
  schedule:
    - cron: "34 4,16 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-vegassingles
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: vegassingles_onepiece
      game: "onepiece"
      datastore-filepath: b2://mtgban-datastore/onepiece/onepiece.json.xz
    secrets: inherit
