name: pokemon / coolstuffinc_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [pokemon-coolstuffinc_sealed, pokemon-all]
  schedule:
    - cron: "27 9,21 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-coolstuffinc
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: coolstuffinc_sealed
      game: "pokemon"
      affiliate: ${{ vars.CSI_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/pokemon/pokemon.json.xz
    secrets: inherit
