name: fleshandblood / strikezone

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [strikezone_fleshandblood]
  schedule:
    - cron: "45 */12 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-strikezone
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: strikezone_fleshandblood
      game: "fleshandblood"
      datastore-filepath: b2://mtgban-datastore/fleshandblood/fleshandblood.json.xz
    secrets: inherit
