name: gundam / cardtrader_sealed

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardtrader_sealed_gundam]
  schedule:
    - cron: "55 3,15 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardtrader
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardtrader_sealed_gundam
      game: "gundam"
      datastore-filepath: b2://mtgban-datastore/gundam/gundam.json.xz
    secrets: inherit
