name: fleshandblood / cardmarket_market

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket_market_fleshandblood]
  schedule:
    - cron: "55 10 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardmarket_market_fleshandblood
      game: "fleshandblood"
      datastore-filepath: b2://mtgban-datastore/fleshandblood/fleshandblood.json.xz
      mkmids-filepath: b2://mtgban-datastore/fleshandblood/cardmarket_catalog.json.xz
    secrets: inherit
