name: gundam / cardtrader

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [gundam-cardtrader, gundam-all]
  schedule:
    - cron: "35 3,15 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardtrader
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: cardtrader
      game: "gundam"
      affiliate: ${{ vars.CT_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/gundam/gundam.json.xz
    secrets: inherit
