name: riftbound / merlion

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [riftbound-merlion, riftbound-all]
  schedule:
    - cron: "22 */12 * * *"

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: merlion
      game: "riftbound"
      datastore-filepath: b2://mtgban-datastore/riftbound/riftbound.json.xz
    secrets: inherit
