name: lorcana / strikezone

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [strikezone_lorcana]
  schedule:
    - cron: "17 3,15 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-strikezone
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: strikezone_lorcana
      game: "lorcana"
      datastore-filepath: b2://mtgban-datastore/lorcana/lorcana.json.xz
    secrets: inherit
