name: tcg_index_lorcana

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_index_lorcana]
  schedule:
    - cron: "15 */12 * * *"

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false

jobs:
  cache-datastore:
    uses: ./.github/workflows/cache-file.yml
    with:
      url: ${{ vars.DATASTORE_LORCANA }}
      path: "datastore/"
      game: "lorcana"
    secrets: inherit

  deploy:
    name: ${{ github.workflow }}
    needs: [cache-datastore]
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ github.workflow }}
      game: "lorcana"
      datastore-filepath: ${{ needs.cache-datastore.outputs.filepath }}
      datastore-cache-key: ${{ needs.cache-datastore.outputs.key }}
    secrets: inherit
