name: vegassingles_onepiece

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [vegassingles_onepiece]
  schedule:
    - cron: "8 */12 * * *"

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ github.workflow }}
      game: "onepiece"
      datastore-filepath: b2://mtgban-datastore/onepiece/onepiece.json.xz
    secrets: inherit
