name: gundam / vegassingles

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [vegassingles_gundam]
  schedule:
    - cron: "16 3,15 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-vegassingles
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: vegassingles_gundam
      game: "gundam"
      datastore-filepath: b2://mtgban-datastore/gundam/gundam.json.xz
    secrets: inherit
