name: cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket]
  schedule:
    - cron: "59 19 * * *"

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false

jobs:
  cache-datastore:
    uses: ./.github/workflows/cache-file.yml
    with:
      url: ${{ vars.DATASTORE_MAGIC }}
      path: "datastore/"

  deploy:
    name: Deploy ${{ github.workflow }}
    needs: [cache-datastore]
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ github.workflow }}
      game: "magic"
      datastore-filepath: ${{ needs.cache-datastore.outputs.filepath }}
      datastore-cache-key: ${{ needs.cache-datastore.outputs.key }}
    secrets: inherit
