name: lorcana / coolstuffinc

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [coolstuffinc_lorcana]
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: coolstuffinc_lorcana
      game: "lorcana"
      datastore-filepath: b2://mtgban-datastore/lorcana/lorcana.json.xz
    secrets: inherit
