name: yugioh / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardmarket_yugioh]
  schedule:
    - cron: "0 0,12 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardmarket
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardmarket_yugioh
      game: "yugioh"
      datastore-filepath: b2://mtgban-datastore/yugioh/yugioh.json.xz
      mkmids-filepath: b2://mtgban-datastore/yugioh/cardmarket_catalog.json.xz
    secrets: inherit
