name: fleshandblood / starcitygames

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [starcitygames_fleshandblood]
  schedule:
    - cron: "6 10,22 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-starcitygames
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: starcitygames_fleshandblood
      game: "fleshandblood"
      datastore-filepath: b2://mtgban-datastore/fleshandblood/fleshandblood.json.xz
    secrets: inherit
