name: fleshandblood / tcg_index

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_index_fleshandblood]
  schedule:
    - cron: "52 4,16 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: tcg_index_fleshandblood
      game: "fleshandblood"
      datastore-filepath: b2://mtgban-datastore/fleshandblood/fleshandblood.json.xz
    secrets: inherit
