name: fleshandblood / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [fleshandblood-cardmarket, fleshandblood-all]
  schedule:
    - cron: "20 4,16 * * *"

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: cardmarket
      game: "fleshandblood"
      affiliate: ${{ vars.MKM_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/fleshandblood/fleshandblood.json.xz
      cardmarket-catalog-filepath: b2://mtgban-datastore/fleshandblood/cardmarket_catalog.json.xz
    secrets: inherit
