name: pokemon / cardtrader

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [cardtrader_pokemon]
  schedule:
    - cron: "43 2,14 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-cardtrader
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: cardtrader_pokemon
      game: "pokemon"
      datastore-filepath: b2://mtgban-datastore/pokemon/pokemon.json.xz
    secrets: inherit
