name: yugioh / cardmarket

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [yugioh-cardmarket, yugioh-all]
  schedule:
    - cron: "0 0,12 * * *"

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: cardmarket
      game: "yugioh"
      affiliate: ${{ vars.MKM_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/yugioh/yugioh.json.xz
      mkmids-filepath: b2://mtgban-datastore/yugioh/cardmarket_catalog.json.xz
    secrets: inherit
