name: lorcana / coolstuffinc

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [lorcana-coolstuffinc, lorcana-all]
  schedule:
    - cron: "2 1,13 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-coolstuffinc
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: coolstuffinc
      game: "lorcana"
      affiliate: ${{ vars.CSI_PARTNER }}
      datastore-filepath: b2://mtgban-datastore/lorcana/lorcana.json.xz
    secrets: inherit
