name: onepiece / gamenerdz

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [onepiece-gamenerdz, onepiece-all]
  schedule:
    - cron: "36 22 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-gamenerdz
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      store: gamenerdz
      game: "onepiece"
      datastore-filepath: b2://mtgban-datastore/onepiece/onepiece.json.xz
    secrets: inherit
