name: gundam / tcg_market

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [tcg_market_gundam]
  schedule:
    - cron: "13 3,15 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-tcgplayer
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: tcg_market_gundam
      game: "gundam"
      datastore-filepath: b2://mtgban-datastore/gundam/gundam.json.xz
    secrets: inherit
