name: pokemon / gamenerdz

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [gamenerdz_pokemon]
  schedule:
    - cron: "31 22 * * *"

permissions:
  contents: read

concurrency:
  group: bantool-gamenerdz
  cancel-in-progress: false
  queue: max

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: gamenerdz_pokemon
      game: "pokemon"
      datastore-filepath: b2://mtgban-datastore/pokemon/pokemon.json.xz
    secrets: inherit
