name: lorcana / starcitygames

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [starcitygames_lorcana]
  schedule:
    - cron: "50 1-23/12 * * *"

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ github.workflow }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: starcitygames_lorcana
      game: "lorcana"
      datastore-filepath: b2://mtgban-datastore/lorcana/lorcana.json.xz
    secrets: inherit
