name: Bantool Runner (daily)
run-name: Bantool (${{ github.event.client_payload.target || github.event.inputs.target || 'all' }})

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - sealed_ev
          - abugames
          - abugames_sealed
          - cardmarket
          - cardmarket_sealed
          - cardtrader
          - cardtrader_sealed
          - mintcard
          - mtgseattle
          - magiccorner
          - miniaturemarket_sealed
          - tcg_syplist
  repository_dispatch:
    types: [bantool_magic]
  schedule:
    - cron: "30 19 * * *" # just after the advertised mtgjson release

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: |
          ALL_TARGETS='[
            "sealed_ev",
            "abugames",
            "abugames_sealed",
            "cardmarket",
            "cardmarket_sealed",
            "cardtrader",
            "cardtrader_sealed",
            "mintcard",
            "mtgseattle",
            "magiccorner",
            "miniaturemarket_sealed",
            "tcg_syplist"
          ]'

          TARGET_JSON="{\"target\":$ALL_TARGETS}"

          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.target }}" != "all" ];
          then
            TARGET_JSON="{\"target\":[\"${{ github.event.inputs.target }}\"]}"
          elif [ "${{ github.event_name }}" = "repository_dispatch" ];
          then
            # Check payload
            PAYLOAD_TARGET="${{ github.event.client_payload.target }}"
            if [ -z "$PAYLOAD_TARGET" ]; then
              echo "Error: repository_dispatch event must include client_payload.target" >&2
              exit 1
            fi

            # Validate against ALL_TARGETS
            if echo "$ALL_TARGETS" | jq -e --arg t "$PAYLOAD_TARGET" '.[] | select(. == $t)' > /dev/null;
            then
              TARGET_JSON="{\"target\":[\"$PAYLOAD_TARGET\"]}"
            else
              echo "Error: Invalid target '$PAYLOAD_TARGET'. Must be one of: $(echo $ALL_TARGETS | jq -r '.[]' | tr '\n' ' ')" >&2
              TARGET_JSON="{\"target\":[]}"
            fi
          fi

          # Escape for $GITHUB_OUTPUT
          ESCAPED_JSON=$(echo "$TARGET_JSON" | jq -c .)
          echo "matrix=$ESCAPED_JSON" >> $GITHUB_OUTPUT

  cache-datastore:
    uses: ./.github/workflows/cache-file.yml
    with:
      url: "https://www.mtgjson.com/api/v5/AllPrintings.json.xz"
      path: "datastore/"

  deploy:
    name: Deploy ${{ matrix.target }}
    needs: [prepare-matrix, cache-datastore]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    if: ${{ fromJSON(needs.prepare-matrix.outputs.matrix).target[0] != '' }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ matrix.target }}
      game: "magic"
      datastore-filepath: ${{ needs.cache-datastore.outputs.filepath }}
      datastore-cache-key: ${{ needs.cache-datastore.outputs.key }}
    secrets: inherit
