name: Bantool Runner (daily)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - sealed_ev
          - abugames
          - abugames_sealed
          - cardmarket
          - cardmarket_sealed
          - cardtrader
          - cardtrader_sealed
          - mintcard
          - mtgseattle
          - magiccorner
          - miniaturemarket_sealed
          - tcg_syplist
  schedule:
    - cron: "30 19 * * *" # just after the advertised mtgjson release

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: |
          ALL_TARGETS='[
            "sealed_ev",
            "abugames",
            "abugames_sealed",
            "cardmarket",
            "cardmarket_sealed",
            "cardtrader",
            "cardtrader_sealed",
            "mintcard",
            "mtgseattle",
            "magiccorner",
            "miniaturemarket_sealed",
            "tcg_syplist"
          ]'
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.target }}" != "all" ];
          then
            TARGET_JSON="{\"target\":[\"${{ github.event.inputs.target }}\"]}"
          else
            TARGET_JSON="{\"target\":$ALL_TARGETS}"
          fi

          # Escape for $GITHUB_OUTPUT
          ESCAPED_JSON=$(echo "$TARGET_JSON" | jq -c .)
          echo "matrix=$ESCAPED_JSON" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy ${{ matrix.target }}
    needs: prepare-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ matrix.target }}
      game: "magic"
    secrets: inherit
