name: Bantool Runner (every 4 hours)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - coolstuffinc
          - coolstuffinc_sealed
          - starcitygames
          - starcitygames_sealed
          - strikezone
          - trollandtoad
  schedule:
    - cron: "20 0/4 * * *"

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: |
          ALL_TARGETS='[
            "coolstuffinc",
            "coolstuffinc_sealed",
            "starcitygames",
            "starcitygames_sealed",
            "strikezone",
            "trollandtoad"
          ]'
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.target }}" != "all" ];
          then
            TARGET_JSON="{\"target\":[\"${{ github.event.inputs.target }}\"]}"
          else
            TARGET_JSON="{\"target\":$ALL_TARGETS}"
          fi

          # Escape for $GITHUB_OUTPUT
          ESCAPED_JSON=$(echo "$TARGET_JSON" | jq -c .)
          echo "matrix=$ESCAPED_JSON" >> $GITHUB_OUTPUT

  cache-allprintings:
    uses: ./.github/workflows/cache-file.yml
    with:
      url: "https://www.mtgjson.com/api/v5/AllPrintings.json.xz"
      path: "datastore/"

  deploy:
    name: Deploy ${{ matrix.target }}
    needs: [prepare-matrix, cache-allprintings]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ matrix.target }}
      game: "magic"
      datastore-filepath: ${{ needs.cache-allprintings.outputs.filepath }}
      datastore-cache-key: ${{ needs.cache-allprintings.outputs.key }}
    secrets: inherit
