name: Bantool Runner for Lorcana (twice a day)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - cardmarket_lorcana
          - cardtrader_lorcana
          - coolstuffinc_lorcana
          - starcitygames_lorcana
          - strikezone_lorcana
          - tcg_index_lorcana
          - tcg_market_lorcana
  schedule:
    - cron: "50 */12 * * *"

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: |
          ALL_TARGETS='[
            "cardmarket_lorcana",
            "cardtrader_lorcana",
            "coolstuffinc_lorcana",
            "starcitygames_lorcana",
            "strikezone_lorcana",
            "tcg_index_lorcana",
            "tcg_market_lorcana"
          ]'
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.target }}" != "all" ];
          then
            TARGET_JSON="{\"target\":[\"${{ github.event.inputs.target }}\"]}"
          else
            TARGET_JSON="{\"target\":$ALL_TARGETS}"
          fi

          # Escape for $GITHUB_OUTPUT
          ESCAPED_JSON=$(echo "$TARGET_JSON" | jq -c .)
          echo "matrix=$ESCAPED_JSON" >> $GITHUB_OUTPUT

  cache-datastore:
    uses: ./.github/workflows/cache-file.yml
    with:
      url: "https://lorcanajson.org/files/current/en/allCards.json"
      path: "datastore/"

  deploy:
    name: Deploy ${{ matrix.target }}
    needs: [prepare-matrix, cache-datastore]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    uses: ./.github/workflows/run-bantool.yml
    with:
      target: ${{ matrix.target }}
      game: "lorcana"
      datastore-filepath: ${{ needs.cache-datastore.outputs.filepath }}
      datastore-cache-key: ${{ needs.cache-datastore.outputs.key }}
    secrets: inherit
